#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/WeChatManage/Views/App/FormNews.cshtml")]
    public partial class _Areas_WeChatManage_Views_App_FormNews_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_WeChatManage_Views_App_FormNews_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\WeChatManage\Views\App\FormNews.cshtml"
  
    ViewBag.Title = "消息型应用";
    Layout = "~/Views/Shared/_Form.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<!--jqgrid表格组件start-->\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 111), Tuple.Create("\"", 161)
, Tuple.Create(Tuple.Create("", 118), Tuple.Create<System.Object, System.Int32>(Href("~/Content/scripts/plugins/jqgrid/jqgrid.css")
, 118), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

            
            #line 7 "..\..\Areas\WeChatManage\Views\App\FormNews.cshtml"
Write(System.Web.Optimization.Scripts.Render("~/Content/scripts/plugins/jqgrid/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<!--表格组件end-->\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 287), Tuple.Create("\"", 346)
, Tuple.Create(Tuple.Create("", 293), Tuple.Create<System.Object, System.Int32>(Href("~/Content/scripts/plugins/uploadify/ajaxfileupload.js")
, 293), false)
);

WriteLiteral("></script>\r\n<script>\r\n    var keyValue = learun.request(\'keyValue\');\r\n    var f =" +
" null;\r\n    $(function () {\r\n        initialPage();\r\n        getGridMenu()\r\n    " +
"})\r\n    //初始化页面\r\n    function initialPage() {\r\n        //加载导向\r\n        $(\'#wizar" +
"d\').wizard().on(\'change\', function (e, data) {\r\n            var $finish = $(\"#bt" +
"n_finish\");\r\n            var $next = $(\"#btn_next\");\r\n            if (data.direc" +
"tion == \"next\") {\r\n                if (data.step == 1) {\r\n                    $f" +
"inish.removeAttr(\'disabled\');\r\n                    $next.attr(\'disabled\', \'disab" +
"led\');\r\n                } else {\r\n                    $finish.attr(\'disabled\', \'" +
"disabled\');\r\n                }\r\n            } else {\r\n                $finish.at" +
"tr(\'disabled\', \'disabled\');\r\n                $next.removeAttr(\'disabled\');\r\n    " +
"        }\r\n        });\r\n        if (!!keyValue) {\r\n            learun.setForm({\r" +
"\n                url: \"../../WeChatManage/App/GetFormJson\",\r\n                par" +
"am: { keyValue: keyValue },\r\n                success: function (data) {\r\n       " +
"             $(\"#form1\").setWebControls(data);\r\n                    if (data.F_M" +
"enuJson != null)\r\n                    {\r\n                        menuJson = JSON" +
".parse(data.F_MenuJson);\r\n                    }\r\n                    document.ge" +
"tElementById(\'uploadPreview\').src = top.contentPath + data.F_AppLogo;\r\n         " +
"       }\r\n            });\r\n        };\r\n        $(\'#uploadFile\').change(function " +
"() {\r\n            f = document.getElementById(\'uploadFile\').files[0]\r\n          " +
"  var src = window.URL.createObjectURL(f);\r\n            document.getElementById(" +
"\'uploadPreview\').src = src;\r\n        });\r\n    }\r\n    //自定义菜单\r\n    var menuJson =" +
" [];\r\n    function getGridMenu() {\r\n        var selectedRowIndex = 0;\r\n        v" +
"ar $grid = $(\"#gridTable-menu\");\r\n        $grid.jqGrid({\r\n            unwritten:" +
" false,\r\n            height: $(window).height() - 166,\r\n            width: $(win" +
"dow).width() - 12,\r\n            colModel: [\r\n                { label: \"主键\", name" +
": \"F_MenuId\", hidden: true },\r\n                { label: \"&nbsp;&nbsp;&nbsp;&nbsp" +
";名称\", name: \"F_MenuName\", width: 100, align: \"left\", sortable: false },\r\n       " +
"         { label: \"类型\", name: \"F_MenuTypeName\", width: 80, align: \"left\", sortab" +
"le: false },\r\n                { label: \"地址\", name: \"F_MenuUrl\", width: 200, alig" +
"n: \"left\", sortable: false },\r\n            ],\r\n            treeGrid: true,\r\n    " +
"        treeGridModel: \"nested\",\r\n            ExpandColumn: \"F_MenuTypeName\",\r\n " +
"           rowNum: \"all\",\r\n            rownumbers: true,\r\n            onSelectRo" +
"w: function () {\r\n                selectedRowIndex = $(\"#\" + this.id).getGridPar" +
"am(\'selrow\');\r\n            },\r\n            gridComplete: function () {\r\n        " +
"        $(\"#\" + this.id).setSelection(selectedRowIndex, false);\r\n            }\r\n" +
"        });\r\n        if (!!keyValue) {\r\n            MenuListToListTreeJson(menuJ" +
"son);\r\n        }\r\n        function MenuListToListTreeJson(menuJson) {\r\n         " +
"   $.ajax({\r\n                url: \"../../WeChatManage/App/MenuListToListTreeJson" +
"\",\r\n                data: { menuJson: JSON.stringify(menuJson) },\r\n             " +
"   type: \"post\",\r\n                dataType: \"json\",\r\n                success: fu" +
"nction (data) {\r\n                    $grid.clearGridData();\r\n                   " +
" $grid[0].addJSONData(data);\r\n                },\r\n            });\r\n        }\r\n  " +
"      //新增\r\n        $(\"#lr-add-menu\").click(function () {\r\n            var paren" +
"tId = $(\"#gridTable-menu\").jqGridRowValue(\"F_MenuId\");\r\n            learun.dialo" +
"gOpen({\r\n                id: \"FormMenu\",\r\n                title: \'添加菜单\',\r\n      " +
"          url: \'/WeChatManage/App/FormMenu?parentId=\' + parentId,\r\n             " +
"   width: \"450px\",\r\n                height: \"300px\",\r\n                callBack: " +
"function (iframeId) {\r\n                    top.frames[iframeId].AcceptClick(func" +
"tion (data) {\r\n                        menuJson.push(data);\r\n                   " +
"     MenuListToListTreeJson(menuJson);\r\n                    });\r\n               " +
" }\r\n            });\r\n        });\r\n        //编辑\r\n        $(\"#lr-edit-menu\").click" +
"(function () {\r\n            var menuId = $(\"#gridTable-menu\").jqGridRowValue(\"F_" +
"MenuId\");\r\n            if (learun.checkedRow(menuId)) {\r\n                learun." +
"dialogOpen({\r\n                    id: \"FormMenu\",\r\n                    title: \'编" +
"辑菜单\',\r\n                    url: \'/WeChatManage/App/FormMenu?menuId=\' + menuId,\r\n" +
"                    width: \"450px\",\r\n                    height: \"300px\",\r\n     " +
"               callBack: function (iframeId) {\r\n                        top.fram" +
"es[iframeId].AcceptClick(function (data) {\r\n                            $.each(m" +
"enuJson, function (i) {\r\n                                if (menuJson[i].F_MenuI" +
"d == menuId) {\r\n                                    menuJson[i] = data;\r\n       " +
"                         }\r\n                            });\r\n                   " +
"         MenuListToListTreeJson(menuJson);\r\n                        });\r\n       " +
"             }\r\n                });\r\n            }\r\n        });\r\n        //删除\r\n " +
"       $(\"#lr-delete-menu\").click(function () {\r\n            var menuId = $(\"#gr" +
"idTable-menu\").jqGridRowValue(\"F_MenuId\");\r\n            if (learun.checkedRow(me" +
"nuId)) {\r\n                $.each(menuJson, function (i) {\r\n                    i" +
"f (menuJson[i].F_MenuId == menuId) {\r\n                        menuJson.splice(i," +
" 1);\r\n                        MenuListToListTreeJson(menuJson);\r\n               " +
"         return false;\r\n                    }\r\n                });\r\n            " +
"}\r\n        });\r\n    }\r\n    //保存表单\r\n    function AcceptClick() {\r\n        var App" +
"Id = $(\"#AppId\").val();\r\n        if (document.getElementById(\'uploadFile\').src =" +
"= \"~/Content/images/logo-headere47d5.png\") {\r\n            top.learun.dialogTop({" +
" msg: \'请添加应用Logo\', type: \'error\' });\r\n            return false;\r\n        } else " +
"{\r\n            if (!$(\'#form1\').Validform()) {\r\n                return false;\r\n " +
"           }\r\n            if (f != null) {\r\n                //上传应用图标\r\n          " +
"      $.ajaxFileUpload({\r\n                    url: \"../../WeChatManage/App/Uploa" +
"dFile?AppId=\" + AppId,\r\n                    secureuri: false,\r\n                 " +
"   fileElementId: \'uploadFile\',\r\n                    dataType: \'json\',\r\n        " +
"            success: function (data) {\r\n                        var postData = $" +
"(\"#form1\").getWebControls(\"\");\r\n                        postData[\"F_AppLogo\"] = " +
"data.message;\r\n                        postData[\"F_MenuJson\"] = JSON.stringify(m" +
"enuJson);\r\n                        learun.saveForm({\r\n                          " +
"  url: \"../../WeChatManage/App/SaveForm?keyValue=\" + keyValue,\r\n                " +
"            param: postData,\r\n                            loading: \"正在保存数据...\",\r" +
"\n                            success: function () {\r\n                           " +
"     learun.currentIframe().learun.reload();\r\n                            }\r\n   " +
"                     });\r\n                    }\r\n                });\r\n          " +
"  }\r\n            else {\r\n                var postData = $(\"#form1\").getWebContro" +
"ls(\"\");\r\n                postData[\"F_MenuJson\"] = JSON.stringify(menuJson);\r\n   " +
"             learun.saveForm({\r\n                    url: \"../../WeChatManage/App" +
"/SaveForm?keyValue=\" + keyValue,\r\n                    param: postData,\r\n        " +
"            loading: \"正在保存数据...\",\r\n                    success: function () {\r\n " +
"                       learun.currentIframe().learun.reload();\r\n                " +
"    }\r\n                });\r\n            }\r\n           \r\n        }\r\n    }\r\n</scri" +
"pt>\r\n<div");

WriteLiteral(" class=\"widget-body\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"wizard\"");

WriteLiteral(" class=\"wizard\"");

WriteLiteral(" data-target=\"#wizard-steps\"");

WriteLiteral(" style=\"border-left: none; border-top: none; border-right: none;\"");

WriteLiteral(">\r\n        <ul");

WriteLiteral(" class=\"steps\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" data-target=\"#step-1\"");

WriteLiteral(" class=\"active\"");

WriteLiteral("><span");

WriteLiteral(" class=\"step\"");

WriteLiteral(">1</span>基本信息<span");

WriteLiteral(" class=\"chevron\"");

WriteLiteral("></span></li>\r\n            <li");

WriteLiteral(" data-target=\"#step-2\"");

WriteLiteral("><span");

WriteLiteral(" class=\"step\"");

WriteLiteral(">2</span>自定义菜单<span");

WriteLiteral(" class=\"chevron\"");

WriteLiteral("></span></li>\r\n        </ul>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"step-content\"");

WriteLiteral(" id=\"wizard-steps\"");

WriteLiteral(" style=\"border-left: none; border-bottom: none; border-right: none;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"step-pane active\"");

WriteLiteral(" id=\"step-1\"");

WriteLiteral(" style=\"margin-left: 0px; margin-top: 15px; margin-right: 30px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"applogo \"");

WriteLiteral(" style=\"text-align: center; margin-bottom: 5px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"file\"");

WriteLiteral(" style=\"width: 100px; height: 100px;\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" id=\"uploadPreview\"");

WriteLiteral(" style=\"width: 100px; height: 100px; border-radius: 100px;\"");

WriteAttribute("src", Tuple.Create(" src=\"", 8805), Tuple.Create("\"", 8848)
, Tuple.Create(Tuple.Create("", 8811), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/logo-headere47d5.png")
, 8811), false)
);

WriteLiteral(" />\r\n                    <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" name=\"uploadFile\"");

WriteLiteral(" id=\"uploadFile\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n            <table");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n                <tr>\r\n                    <th");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">应用名称</th>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"F_AppId\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 9183), Tuple.Create("\"", 9217)
            
            #line 218 "..\..\Areas\WeChatManage\Views\App\FormNews.cshtml"
, Tuple.Create(Tuple.Create("", 9191), Tuple.Create<System.Object, System.Int32>(Guid.NewGuid().ToString()
            
            #line default
            #line hidden
, 9191), false)
);

WriteLiteral(" />\r\n                        <input");

WriteLiteral(" id=\"F_AppName\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"2-16个字\"");

WriteLiteral(" isvalid=\"yes\"");

WriteLiteral(" checkexpession=\"NotNull\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">可信域名</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"F_RedirectDomain\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"填写应用的域名地址，如：qy.weixin.qq.com:8080\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <th");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" style=\"padding-top: 4px;\"");

WriteLiteral(">应用介绍\r\n                    </th>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" id=\"F_Description\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" style=\"height: 70px;\"");

WriteLiteral(" placeholder=\"描述该应用的功能与特色，内容为4-120个字\"");

WriteLiteral("></textarea>\r\n                    </td>\r\n                </tr>\r\n            </tab" +
"le>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"step-pane\"");

WriteLiteral(" id=\"step-2\"");

WriteLiteral(" style=\"margin: 5px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" style=\"height: 40px; line-height: 33px; text-align: right;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" id=\"lr-add-menu\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-plus\"");

WriteLiteral("></i>&nbsp;新增</a>\r\n                    <a");

WriteLiteral(" id=\"lr-edit-menu\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-pencil-square-o\"");

WriteLiteral("></i>&nbsp;编辑</a>\r\n                    <a");

WriteLiteral(" id=\"lr-delete-menu\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-trash-o\"");

WriteLiteral("></i>&nbsp;删除</a>\r\n                </div>\r\n            </div>\r\n            <table" +
"");

WriteLiteral(" id=\"gridTable-menu\"");

WriteLiteral("></table>\r\n        </div>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"form-button\"");

WriteLiteral(" id=\"wizard-actions\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btn_last\"");

WriteLiteral(" disabled");

WriteLiteral(" class=\"btn btn-default btn-prev\"");

WriteLiteral(">上一步</a>\r\n    <a");

WriteLiteral(" id=\"btn_next\"");

WriteLiteral(" class=\"btn btn-default btn-next\"");

WriteLiteral(">下一步</a>\r\n    <a");

WriteLiteral(" id=\"btn_finish\"");

WriteLiteral(" disabled");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(" onclick=\"AcceptClick()\"");

WriteLiteral(@">完成</a>
</div>


<style>
    .file {
        position: relative;
        display: inline-block;
        overflow: hidden;
        text-decoration: none;
        text-indent: 0;
        cursor: pointer !important;
    }

        .file input {
            position: absolute;
            font-size: 100px;
            right: 0;
            top: 0;
            opacity: 0;
            cursor: pointer !important;
        }

        .file:hover {
            text-decoration: none;
            cursor: pointer !important;
        }
</style>
");

        }
    }
}
#pragma warning restore 1591
