#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/MONITORPOINT/Views/TBL_DMCJ_MONITORPOINTSELECT/TBL_DMCJ_MONITORIndex.csht" +
        "ml")]
    public partial class _Areas_MONITORPOINT_Views_TBL_DMCJ_MONITORPOINTSELECT_TBL_DMCJ_MONITORIndex_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_MONITORPOINT_Views_TBL_DMCJ_MONITORPOINTSELECT_TBL_DMCJ_MONITORIndex_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\MONITORPOINT\Views\TBL_DMCJ_MONITORPOINTSELECT\TBL_DMCJ_MONITORIndex.cshtml"
  
    ViewBag.Title = "列表页面";
    Layout = "~/Views/Shared/_IndexMap.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 107), Tuple.Create("\"", 181)
, Tuple.Create(Tuple.Create("", 114), Tuple.Create<System.Object, System.Int32>(Href("~/Content/scripts/plugins/JQueryzTree/css/zTreeStyle/zTreeStyle.css")
, 114), false)
);

WriteLiteral(" type=\"text/css\"");

WriteLiteral(@" />
 <style>
    .ui-layout-center {
       overflow-x: hidden !important;
    }
    .ui-layout-resizer {
        background-color:#f0f3f4 !important;
    }
    .bbit-tree-node a:hover{
        text-decoration:none !important;
    }
     .fa-folder-open {
        color: transparent !important;
        background: url(""../../Content/images/zTreeStandard.png"") no-repeat;
        background-position: -110px -16px;
        margin-right: 2px;
        width: 16px !important;
        height: 16px !important;
    }

    .fa-folder {
        color: transparent !important;
        background: url(""../../Content/images/zTreeStandard.png"") no-repeat;
        background-position: -110px 0;
        margin-right: 2px;
        width: 16px !important;
        height: 16px !important;
    }

    .fa-file-o {
        color: transparent !important;
        background: url(""../../Content/images/zTreeStandard.png"") no-repeat;
        background-position: -110px -32px;
        width: 16px !important;
        height: 16px !important;
    }
    .bbit-tree-arrows .bbit-tree-elbow-plus, .bbit-tree-arrows .bbit-tree-elbow-end-minus {
        margin-top: 5px !important;
    }
 .ui-layout-north {
    overflow:hidden!important;
    }
 .color:hover{
            color:#23527c !important;
        }
   #ui_center{
        overflow:hidden!important;
    }
</style>
      
<div");

WriteLiteral(" class=\"ui-layout\"");

WriteLiteral(" id=\"layout\"");

WriteLiteral(" style=\"height: 100%; width: 100%;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui-layout-west\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"west-Panel\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel-Title\"");

WriteLiteral(">行政区划信息</div>\r\n            <div");

WriteLiteral(" id=\"itemTree\"");

WriteLiteral(" style=\"overflow:auto;\"");

WriteLiteral("></div>\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"ui-layout-center\"");

WriteLiteral(" id=\"ui_center\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"center-Panel\"");

WriteLiteral(" style=\"height: 100%;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui-layout\"");

WriteLiteral(" id=\"layout2\"");

WriteLiteral(" style=\"height: 100%; width: 100%;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui-layout-north\"");

WriteLiteral(" id=\"ui_map\"");

WriteLiteral(" style=\"height: 432px;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"panel-Title\"");

WriteLiteral(" style=\"background: #ECF7FF;height:33px;\"");

WriteLiteral(" id=\"filter-form\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" style=\"position: absolute; width: 99%;\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" style=\"float:left;\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"title-search\"");

WriteLiteral(">\r\n                                    <table>\r\n                                 " +
"       <tr>\r\n                                            <td");

WriteLiteral(" style=\"font-size:14px; color: #000; padding: 0px 6px 0px 0px;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-bars\"");

WriteLiteral(" style=\"margin-right:10px;\"");

WriteLiteral("></i>查询条件:</td>\r\n                                            <td>\r\n              " +
"                                  <div");

WriteLiteral(" id=\"XZQHCODE\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral("></div>\r\n                                            </td>\r\n                     " +
"                       <td>\r\n                                                <in" +
"put");

WriteLiteral(" id=\"MIXTURE\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"请输入监测点名称，编号\"");

WriteLiteral(" style=\"font-weight:normal !important;width: 200px; height:28px; outline:none; ma" +
"rgin:0px 10px 0px 20px;\"");

WriteLiteral(" />\r\n                                            </td>\r\n                         " +
"                   <td");

WriteLiteral(" style=\"font-size:14px; color: #000; padding: 0px 6px 0px 0px;font-weight:normal " +
"!important;\"");

WriteLiteral(">监测时间:</td>\r\n                                            <td>\r\n                  " +
"                              <input");

WriteLiteral(" id=\"STARTTIME\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control input-wdatepicker\"");

WriteLiteral(" placeholder=\"\"");

WriteLiteral(" style=\"font-weight:normal !important;width: 200px; height:28px; outline:none; ma" +
"rgin:0px 10px 0px 20px;\"");

WriteLiteral(" onfocus=\"WdatePicker({ dateFmt: \'yyyy\' })\"");

WriteLiteral(" />\r\n                                            </td>\r\n                         " +
"                   <td");

WriteLiteral(" style=\"padding-left: 10px;\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" id=\"btn_Search\"");

WriteLiteral(" style=\"font-size:16px; cursor:pointer;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral(" style=\"margin: -9px 10px 0px 0px\"");

WriteLiteral(@"></i></a>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                        </div>
                    ");

WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"ui-layout-center\"");

WriteLiteral(" id=\"ui_grid\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"titlePanel\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"title-search\"");

WriteLiteral(" id=\"filter-form-detail\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" style=\"font-weight:bold; font-size:14px;\"");

WriteLiteral(">数据列表</span>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"toolbar\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" id=\"btn_export\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" onclick=\"btn_export()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-sign-in\"");

WriteLiteral("></i>&nbsp;导出</a>\r\n                                ");

WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" style=\"clear:both;\"");

WriteLiteral("></div>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"gridPanel\"");

WriteLiteral(">\r\n                        <table");

WriteLiteral(" id=\"gridTable\"");

WriteLiteral("></table>\r\n                        <div");

WriteLiteral(" id=\"gridPager\"");

WriteLiteral("></div>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n" +
"        </div>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 6225), Tuple.Create("\"", 6284)
, Tuple.Create(Tuple.Create("", 6231), Tuple.Create<System.Object, System.Int32>(Href("~/Content/scripts/plugins/districts/multiDistricts.js")
, 6231), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 6304), Tuple.Create("\"", 6379)
, Tuple.Create(Tuple.Create("", 6310), Tuple.Create<System.Object, System.Int32>(Href("~/Content/scripts/plugins/JQueryzTree/js/jquery.ztree.core-3.5.min.js")
, 6310), false)
);

WriteLiteral("></script>\r\n<script>\r\n    var layout2NorthH = 1;\r\n    var authToken = getAuthoriz" +
"ationToken();\r\n    $(function () {\r\n        mapshow = true;\r\n        InitialPage" +
"();\r\n        GetTree();\r\n        //GetMapData();\r\n        GetGrid();\r\n        //" +
"initControl();\r\n        //查询点击事件  \r\n        $(\"#btn_Search\").click(function () {" +
"\r\n            var queryJson = $.extend($(\".title-search\").getWebControls(), $(\"#" +
"itemTree\").getWebControls());\r\n            queryJson[\"PROVINCE\"] = PROVINCE;\r\n  " +
"          queryJson[\"CITY\"] = CITY;\r\n            queryJson[\"COUNTY\"] = COUNTY;\r\n" +
"           \r\n            SearchEvent(queryJson);\r\n        }); \r\n        $(\"#MIXT" +
"URE\").keydown(function (event) {\r\n            if (event.keyCode == \"13\") {\r\n    " +
"            var queryJson = $.extend($(\".title-search\").getWebControls(), $(\"#it" +
"emTree\").getWebControls());\r\n                queryJson[\"PROVINCE\"] = PROVINCE;\r\n" +
"                queryJson[\"CITY\"] = CITY;\r\n                queryJson[\"COUNTY\"] =" +
" COUNTY;\r\n\r\n                SearchEvent(queryJson);\r\n            }\r\n        })\r\n" +
"        $(\"#MONITORTIME\").keydown(function (event) {\r\n            if (event.keyC" +
"ode == \"13\") {\r\n                var queryJson = $.extend($(\".title-search\").getW" +
"ebControls(), $(\"#itemTree\").getWebControls());\r\n                queryJson[\"PROV" +
"INCE\"] = PROVINCE;\r\n                queryJson[\"CITY\"] = CITY;\r\n                q" +
"ueryJson[\"COUNTY\"] = COUNTY;\r\n                \r\n                SearchEvent(quer" +
"yJson);\r\n            }\r\n        })\r\n    });\r\n    //初始化页面\r\n    //初始化页面\r\n    funct" +
"ion InitialPage() {\r\n        $(\'#ui_map\').height($(window).height() * 0.53)\r\n   " +
"     $(\'#mapControl\').height($(window).height() * 0.53)\r\n        //layout布局\r\n   " +
"     $(\'#layout\').layout({\r\n            applyDemoStyles: true,\r\n            west" +
"__size: 190,\r\n            onresize: function () {\r\n                if (isResize " +
"< 10) {\r\n                    isResize++;\r\n                }\r\n                res" +
"ize();\r\n            }\r\n        });\r\n        var isResize = 0;\r\n        var count" +
" = 0;\r\n        var resized = 0;\r\n        $(\'#layout2\').layout({\r\n            app" +
"lyDemoStyles: true,\r\n            onresize: function () {\r\n                resize" +
"($(\'.panel-Title\').height());\r\n                if (isResize > 1) {\r\n            " +
"        resized = 1;\r\n                } else {\r\n                    if (count ==" +
" 1 || resized == 0) {\r\n                        $(\'#layout2 .ui-layout-center\').h" +
"eight($(\'#layout2 .ui-layout-center\').height() - 18);\r\n                    }\r\n  " +
"              }\r\n                count++;\r\n            }\r\n        });\r\n        /" +
"/resize重设布局;\r\n        $(window).resize(function (e) {\r\n            if (isResize " +
"< 10) {\r\n                isResize++;\r\n            }\r\n            resize($(\'.pane" +
"l-Title\').height());\r\n            e.stopPropagation();\r\n        });\r\n        fun" +
"ction resize() {\r\n            window.setTimeout(function () {\r\n                i" +
"f (mapCtlExt != null) {\r\n                    mapCtlExt.setHeight($(\'#mapControl\'" +
").parent().height() - 4);\r\n                }\r\n                $(\'#gridTable\').se" +
"tGridWidth(($(\'.gridPanel\').width()));\r\n                $(\'#layout2 .ui-layout-c" +
"enter\').width($(\'#layout2 .ui-layout-center\').parent().width());\r\n              " +
"  $(\'#layout2 .ui-layout-resizer\').width($(\'#layout2 .ui-layout-center\').parent(" +
").width());\r\n                $(\'#gridTable\').setGridHeight($(window).height() - " +
"$(\'#mapControl\').height() - $(\'.panel-Title\').height());\r\n                $(\'#gr" +
"idTable\').setGridHeight($(\'#layout2 .ui-layout-center\').height() - 60 - 60);\r\n  " +
"              $(\'.ui-jqgrid-bdiv\').height($(\'#layout2 .ui-layout-center\').height" +
"() - 60 - 60);\r\n                $(\'#layout2 .ui-layout-center\').height($(\'#layou" +
"t2\').height() - $(\'#layout2 .ui-layout-north\').height());\r\n                $(\'#g" +
"ridTable\').setGridHeight($(\'#layout2 .ui-layout-center\').height() - 123 -10);\r\n " +
"               $(\'#layout2 .ui-layout-center\').css(\'overflow\', \'hidden\');\r\n     " +
"           $(\"#itemTree\").height($(\'.ui-layout-west\').height() - 45);\r\n         " +
"   }, 200);\r\n        };\r\n        $(window).resize();\r\n        $(\'#layout2 .ui-la" +
"yout-center\').height($(\'#layout2 .ui-layout-center\').height() - 18);\r\n        la" +
"yout2NorthH = $(\"#layout2 .ui-layout-north\").height();\r\n    }\r\n    //加载行政区划树\r\n  " +
"  var PROVINCE = \"\", CITY = \"\", COUNTY = \"\";\r\n    function GetTree() {\r\n        " +
"var item = {\r\n            height: $(window).height() - 52,\r\n            isAllExp" +
"and: false,\r\n            url: \"../../Map/GetTreeJsonForMap\",\r\n            onnode" +
"click: function (item) {\r\n                AreaCode = item.id;\r\n                v" +
"ar level = item.value.split(\',\')[1];\r\n                var data = [{\r\n           " +
"         latitude: item.value.split(\',\')[3],\r\n                    longitude: ite" +
"m.value.split(\',\')[2],\r\n                }]\r\n                if (level == -1) {\r\n" +
"                    PROVINCE = \"\";\r\n                    CITY = \"\";\r\n            " +
"        COUNTY = \"\";\r\n                } else if (level == 1) {\r\n                " +
"    PROVINCE = item.id;\r\n                    CITY = \"\";\r\n                    COU" +
"NTY = \"\";\r\n                } else if (level == 2) {\r\n                    PROVINC" +
"E = item.id.substring(0, 2) + \"0000\";\r\n                    CITY = item.id;\r\n    " +
"                COUNTY = \"\";\r\n                } else if (level == 3) {\r\n        " +
"            PROVINCE = item.id.substring(0, 2) + \"0000\";\r\n                    CI" +
"TY = item.id.substring(0, 4) + \"00\";\r\n                    COUNTY = item.id;\r\n   " +
"             }\r\n               // mapCtlExt.addLocation(data,false,level);\r\n    " +
"            $(\'#btn_Search\').trigger(\"click\");\r\n            },\r\n        };\r\n    " +
"    //初始化\r\n        $(\"#itemTree\").treeview(item);\r\n    };\r\n    //加载地图\r\n    var m" +
"apCtlExt = null;\r\n    function GetMapData() {\r\n        mapCtlExt = $(\"#mapContro" +
"l\").mapCtl(\r\n            cfGetMapData({})\n        );\r\n    };\r\n    //加载表格\r\n    fu" +
"nction GetGrid() {\r\n        var selectedRowIndex = 0;\r\n        var queryJson = {" +
"};\r\n        var $gridTable = $(\'#gridTable\');\r\n        $gridTable.jqGrid({\r\n    " +
"        autowidth: true,\r\n            postData: { queryJson: JSON.stringify(quer" +
"yJson) },\r\n           // height: $(window).height() - 570,\r\n            url: \".." +
"/../api/MONITORPOINT/TBL_DMCJ_MONITORDATA/GetPageListJson\",\r\n            loadBef" +
"oreSend: function (request) {\r\n                request.setRequestHeader(\"Authori" +
"zation\", authToken);\r\n            },\r\n            datatype: \"json\",\r\n           " +
" colModel: [\r\n                { label: \'监测点编号\', name: \'MONITORPOINTID\', index: \'" +
"MONITORPOINTID\', width: 230, align: \'left\',sortable: true  },\r\n                {" +
" label: \'监测点名称\', name: \'MONITORPOINTNAME\', index: \'MONITORPOINTNAME\', width: 300" +
", align: \'left\', sortable: true },\r\n                {\r\n                    label" +
": \'监测时间\', name: \'MONITORTIME\', index: \'MONITORTIME\', width: 230, align: \'left\', " +
"sortable: true,\r\n                    formatter: function (cellvalue) {\r\n        " +
"                if (cellvalue) { return learun.formatDate(cellvalue, \'yyyy-MM-dd" +
"\'); } else { return \'\' }\r\n                    }\r\n                },\r\n           " +
"     { label: \'大地高程（m）\', name: \'VALUE\', index: \'VALUE\', width: 230, align: \'left" +
"\', sortable: true },\r\n                \r\n            ],\r\n            viewrecords:" +
" true,\r\n            rowNum: 30,\r\n            rowList: [30, 50, 100],\r\n          " +
"  pager: \"#gridPager\",\r\n            sortname: \'a.MONITORPOINTID\',\r\n            s" +
"ortorder: \'desc\',\r\n            rownumbers: true,\r\n            shrinkToFit: true," +
"\r\n            gridview: true,\r\n            altRows: true,\r\n            onSelectR" +
"ow: function (rowId, status) {\r\n                selectedRowIndex = $(\'#\' + this." +
"id).getGridParam(\'selrow\');\r\n                var dt = $gridTable.jqGrid(\"getRowD" +
"ata\", rowId);\r\n                var objArr = { guid: dt.GUID, name: dt.MONITORPOI" +
"NTNAME, code: dt.MONITORPOINTID, jd: dt.LONGITUDE, wd: dt.LATITUDE, };\r\n        " +
"        //var html = GetHtml(objArr);\r\n                var data = [];\r\n         " +
"       //data.push({ longitude: dt.LONGITUDE, latitude: dt.LATITUDE, popupHtml: " +
"html });\r\n                //map.getView().setZoom(8);\r\n                //if (isM" +
"arkerClick) {\r\n                //    isMarkerClick = false;\r\n                // " +
"   //cfShowGDZBArea(dt.KQGD, mapCtlExt);\r\n                //    return;\r\n       " +
"         //}\r\n                //else if (dt.LONGITUDE && dt.LATITUDE) {\r\n       " +
"             \r\n                //    //cfShowGDZBArea(dt.KQGD, mapCtlExt);\r\n    " +
"            //}\r\n            },\r\n            gridComplete: function () {\r\n      " +
"          $(\'#\' + this.id).setSelection(selectedRowIndex, false);\r\n            }" +
"\r\n        });\r\n    }\r\n      //查询表格函数\r\n    function SearchEvent(queryJson) {\r\n   " +
"     //var queryJson = $(\"#filter-form\").getWebControls();\r\n            $(\"#grid" +
"Table\").jqGrid(\'setGridParam\', {\r\n                //postData: { queryJson: JSON." +
"stringify(queryJson) },\r\n                postData: { queryJson: JSON.stringify($" +
".extend($(\'.title-search\').getWebControls(), { PROVINCE: PROVINCE, CITY: CITY, C" +
"OUNTY: COUNTY })) },\r\n                url: \"../../api/MONITORPOINT/TBL_DMCJ_MONI" +
"TORDATA/GetPageListJson\",\r\n                  page: 1\r\n            }).trigger(\'re" +
"loadGrid\');\r\n        }\r\n      function ColDataGrid() {\r\n        var centerHeight" +
" = $(\"#layout2\").height();\r\n        var layout2 = $(\'#layout2\').layout();\r\n     " +
"   if ($(\"#lr-colgrid i\").hasClass(\"fa-chevron-down\")) {\r\n             var north" +
"H = centerHeight - 65;\r\n             layout2.sizePane(\"north\", northH);\r\n       " +
"      $(\"#lr-colgrid i\").removeClass(\"fa-chevron-down\");\r\n             $(\"#lr-co" +
"lgrid i\").addClass(\"fa-chevron-up\");\r\n             if ($(\"#lr-colmap i\").hasClas" +
"s(\"fa-chevron-down\")) {\r\n                  $(\"#lr-colmap i\").removeClass(\"fa-che" +
"vron-down\");\r\n                  $(\"#lr-colmap i\").addClass(\"fa-chevron-up\");\r\n  " +
"           }\r\n        }\r\n        else {\r\n             layout2.sizePane(\"north\", " +
"layout2NorthH);\r\n             $(\"#lr-colgrid i\").removeClass(\"fa-chevron-up\");\r\n" +
"             $(\"#lr-colgrid i\").addClass(\"fa-chevron-down\");\r\n        }\r\n       " +
" map.updateSize();\r\n      }\r\n      function ColMapDiv() {\r\n        var layout2 =" +
" $(\'#layout2\').layout();\r\n        if ($(\"#lr-colmap i\").hasClass(\"fa-chevron-up\"" +
")) {\r\n            layout2.sizePane(\"north\", 1);\r\n            $(\"#lr-colmap i\").r" +
"emoveClass(\"fa-chevron-up\");\r\n            $(\"#lr-colmap i\").addClass(\"fa-chevron" +
"-down\");\r\n            if ($(\"#lr-colgrid i\").hasClass(\"fa-chevron-up\")) {\r\n     " +
"           $(\"#lr-colgrid i\").removeClass(\"fa-chevron-up\");\r\n                $(\"" +
"#lr-colgrid i\").addClass(\"fa-chevron-down\");\r\n            }\r\n        }\r\n        " +
"else {\r\n            layout2.sizePane(\"north\", layout2NorthH);\r\n            $(\"#l" +
"r-colmap i\").removeClass(\"fa-chevron-down\");\r\n            $(\"#lr-colmap i\").addC" +
"lass(\"fa-chevron-up\");\r\n            if (mapCtlExt != null) {\r\n                ma" +
"pCtlExt.setHeight($(\"#mapControl\").parent().height() - 32 - 4);\r\n            }\r\n" +
"        }\r\n        map.updateSize();\r\n      }\r\n      \r\n      //重置\r\n      functio" +
"n reset() {\r\n          $(\"#MIXTURE\").val(\"\");\r\n          $(\"#STARTTIME\").comboBo" +
"xSetValue(\"\");\r\n      }\r\n\r\n      \r\n      //导出excel\r\n      function btn_export() " +
"{\r\n          var queryJson = $.extend($(\".title-search\").getWebControls(), $(\"#i" +
"temTree\").getWebControls());\r\n          queryJson[\"PROVINCE\"] = PROVINCE;\r\n     " +
"     queryJson[\"CITY\"] = CITY;\r\n          queryJson[\"COUNTY\"] = COUNTY;\r\n       " +
"   if (!queryJson) {\r\n              return;\r\n          }\r\n          var outColum" +
"n = \"MONITORPOINTID,MONITORPOINTNAME,MONITORTIME,VALUE\";\r\n          location.hre" +
"f = \"../../MONITORPOINT/TBL_DMCJ_MONITORDATA/ExcelDownload_Data?queryJson=\" + JS" +
"ON.stringify(queryJson) + \"&outColumn=\" + outColumn;\r\n      };\r\n</script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
