#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/UIManage/Views/UIDesign/TaskIndex.cshtml")]
    public partial class _Areas_UIManage_Views_UIDesign_TaskIndex_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_UIManage_Views_UIDesign_TaskIndex_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\UIManage\Views\UIDesign\TaskIndex.cshtml"
  
    ViewBag.Title = "任务调度接口配置";
    Layout = "~/Views/Shared/_Index.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n    .orm_title {\r\n        color: #666666;\r\n        font-size: 16px;\r\n        h" +
"eight: 36px;\r\n        line-height: 36px;\r\n        margin-left: 15px;\r\n        fo" +
"nt-weight: bold;\r\n        padding-top: 5px;\r\n    }\r\n\r\n    .orm_title_note {\r\n   " +
"     color: #999999;\r\n        height: 24px;\r\n        line-height: 24px;\r\n       " +
" margin: 0 15px;\r\n        border-bottom: 1px solid #ededed;\r\n    }\r\n\r\n    .actio" +
"n_title1 {\r\n        color: #666666;\r\n        font-size: 14px;\r\n        height: 4" +
"0px;\r\n        line-height: 40px;\r\n        padding-left: 25px;\r\n    }\r\n\r\n    .but" +
"ton_style a {\r\n        display: inline-block;\r\n        height: 40px;\r\n        li" +
"ne-height: 40px;\r\n        padding: 0 25px;\r\n        color: #fff;\r\n    }\r\n\r\n    ." +
"button_style {\r\n        border-bottom: 1px solid #ededed;\r\n        margin: 0 25p" +
"x;\r\n    }\r\n\r\n    .orm_table {\r\n        width: 100%;\r\n    }\r\n\r\n        .orm_table" +
" tr th {\r\n            color: #5b5b60;\r\n            height: 30px;\r\n            li" +
"ne-height: 30px;\r\n            font-size: 14px;\r\n        }\r\n\r\n        .orm_table " +
"tr td {\r\n            vertical-align: top;\r\n            text-align: center;\r\n    " +
"    }\r\n\r\n    .orm_item {\r\n        border: 1px solid #eeeeee;\r\n        margin: 10" +
"px;\r\n        text-align: center;\r\n        padding: 20px;\r\n    }\r\n\r\n    .orm_item" +
"_title {\r\n        background: #007aff;\r\n        padding: 10px 20px;\r\n        bor" +
"der-radius: 8px;\r\n        display: inline-block;\r\n        font-style: italic;\r\n " +
"       color: #fff;\r\n        font-size: 24px;\r\n        font-weight: bold;\r\n    }" +
"\r\n\r\n    .orm_item_title_note {\r\n        font-size: 18px;\r\n        height: 48px;\r" +
"\n        line-height: 48px;\r\n    }\r\n\r\n    .orm_item_title_note1 {\r\n        color" +
": #333;\r\n        line-height: 32px;\r\n    }\r\n\r\n    .orm_action1 {\r\n        margin" +
": 10px;\r\n    }\r\n\r\n    .orm_action {\r\n        width: 100%;\r\n    }\r\n\r\n        .orm" +
"_action tr td {\r\n            border: 1px solid #eeeeee;\r\n            width: 100%" +
";\r\n        }\r\n\r\n    .orm_action_title {\r\n        height: 36px;\r\n        line-hei" +
"ght: 36px;\r\n        font-weight: bold;\r\n        padding-left: 15px;\r\n        fon" +
"t-size: 14px;\r\n        color: #5b5b60;\r\n    }\r\n</style>\r\n\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">


    //$(function () {
    //    InitialPage();




    //});
    //初始化页面
    //function InitialPage() {

    //    $(window).resize(function (e) {
    //        window.setTimeout(function () {
    //            $('#abc').height($(window).height() - 20);
    //        }, 200);
    //        e.stopPropagation();
    //    });
    //}



</script>





<div");

WriteLiteral(" style=\" margin:10px;\"");

WriteLiteral(" id=\"abc\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" style=\"background:#fff; \"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"orm_title\"");

WriteLiteral(">任务调度接口及MQ配置说明</div>\r\n\r\n\r\n        <div");

WriteLiteral(" style=\"border-bottom:2px solid #ee8339; margin-top:15px;\"");

WriteLiteral("></div>\r\n\r\n\r\n    </div>\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"background: #fff; margin-bottom: 10px; \"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"orm_action1\"");

WriteLiteral(">\r\n\r\n\r\n            <table");

WriteLiteral(" class=\"orm_action\"");

WriteLiteral(">\r\n\r\n\r\n                <tr>\r\n                    <td");

WriteLiteral(" class=\"orm_action_title\"");

WriteLiteral(">\r\n                        一、MQ配置相关说明\r\n                    </td>\r\n\r\n             " +
"   </tr>\r\n                <tr>\r\n                    <td>\r\n                      " +
"  <div");

WriteLiteral(" style=\"padding:15px;\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(" style=\"font-weight:bold;\"");

WriteLiteral(">\r\n                                Web.config中配置相关的MQ信息，如下图所示：\r\n\r\n\r\n\r\n\r\n         " +
"                   </p>\r\n\r\n\r\n\r\n                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(">\r\n\r\n                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3610), Tuple.Create("\"", 3652)
, Tuple.Create(Tuple.Create("", 3616), Tuple.Create<System.Object, System.Int32>(Href("~/Content/adminDefault/img/task0.png")
, 3616), false)
);

WriteLiteral(" /> <!--业务系统名称-->\r\n                            </p>\r\n\r\n                          " +
"  <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(" style=\"color:green;\"");

WriteLiteral(">     注意：上面的虚拟主机一定要事先创建，在使用接口之前</p>\r\n\r\n</div>\r\n                    </td>\r\n       " +
"             <td></td>\r\n                </tr>\r\n\r\n            </table>\r\n\r\n\r\n     " +
"   </div>\r\n\r\n\r\n\r\n\r\n\r\n\r\n    </div>\r\n\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"background: #fff; margin-bottom: 10px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"orm_action1\"");

WriteLiteral(">\r\n\r\n\r\n            <table");

WriteLiteral(" class=\"orm_action\"");

WriteLiteral(">\r\n\r\n\r\n                <tr>\r\n                    <td");

WriteLiteral(" class=\"orm_action_title\"");

WriteLiteral(">\r\n                        二、任务调度大体流程\r\n                    </td>\r\n\r\n             " +
"   </tr>\r\n                <tr>\r\n                    <td>\r\n                      " +
"  <div");

WriteLiteral(" style=\"padding:15px;\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(" style=\"font-weight:bold;\"");

WriteLiteral(">1)\t关联模型与队列的相关信息，调用SaveModelQueueInfo方法关联   </p>\r\n                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(" style=\"font-weight:bold;\"");

WriteLiteral(">\r\n                                2)\t新建任务时，要相应的添加此任务的调度信息，调用SaveTaskInfo方法添加，此时该" +
"方法会向相应的消息队列中发送消息，供后台读取\r\n                            </p>\r\n                      " +
"      <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(" style=\"font-weight:bold;\"");

WriteLiteral(">\r\n                                3)\t后台读取消息，处理消息，在处理过程中可以随时更新任务状态，调用ChangeTaskSt" +
"atus方法\r\n                            </p>\r\n                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(" style=\"font-weight:bold;\"");

WriteLiteral(">\r\n                                4)\t任务处理完成后，调用UpdataTaskTimeInfo方法更新任务结束时间和总耗时信" +
"息，也要更新任务状态(同3)\r\n                            </p>\r\n                            <p" +
"");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(" style=\"font-weight:bold;\"");

WriteLiteral(@">
                                5)	任务处理的过程中，可以随时获取任务的状态，调用GetTaskInfoByTaskIds方法
                            </p>


                     




                        </div>
                    </td>

                </tr>

            </table>


        </div>






    </div>



    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"background: #fff; margin-bottom: 10px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"orm_action1\"");

WriteLiteral(">\r\n\r\n\r\n            <table");

WriteLiteral(" class=\"orm_action\"");

WriteLiteral(">\r\n\r\n\r\n                <tr>\r\n                    <td");

WriteLiteral(" class=\"orm_action_title\"");

WriteLiteral(">\r\n                        三、任务调度接口说明\r\n                    </td>\r\n\r\n             " +
"   </tr>\r\n                <tr>\r\n                    <td>\r\n                      " +
"  <div");

WriteLiteral(" style=\"padding:15px;\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(" style=\"font-weight:bold;\"");

WriteLiteral(">1)\t模型与队列关联的接口</p>\r\n\r\n                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(">\r\n                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 6205), Tuple.Create("\"", 6247)
, Tuple.Create(Tuple.Create("", 6211), Tuple.Create<System.Object, System.Int32>(Href("~/Content/adminDefault/img/task1.png")
, 6211), false)
);

WriteLiteral(" />\r\n                            </p>\r\n                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(">\r\n                                ModelQueueDTO信息：\r\n                            " +
"</p>\r\n                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(">\r\n                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 6531), Tuple.Create("\"", 6573)
, Tuple.Create(Tuple.Create("", 6537), Tuple.Create<System.Object, System.Int32>(Href("~/Content/adminDefault/img/task2.png")
, 6537), false)
);

WriteLiteral(" />\r\n                            </p>\r\n                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(" style=\"font-weight:bold;\"");

WriteLiteral(">\r\n                                2)\t任务调度信息的相关接口\r\n                            </" +
"p>\r\n                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(">\r\n                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 6881), Tuple.Create("\"", 6923)
, Tuple.Create(Tuple.Create("", 6887), Tuple.Create<System.Object, System.Int32>(Href("~/Content/adminDefault/img/task3.png")
, 6887), false)
);

WriteLiteral(" />\r\n                            </p>\r\n                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(">\r\n                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 7061), Tuple.Create("\"", 7103)
, Tuple.Create(Tuple.Create("", 7067), Tuple.Create<System.Object, System.Int32>(Href("~/Content/adminDefault/img/task4.png")
, 7067), false)
);

WriteLiteral(" />\r\n                            </p>\r\n                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(">\r\n                                TaskDTO信息：\r\n                            </p>\r\n" +
"                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(">\r\n                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 7381), Tuple.Create("\"", 7423)
, Tuple.Create(Tuple.Create("", 7387), Tuple.Create<System.Object, System.Int32>(Href("~/Content/adminDefault/img/task5.png")
, 7387), false)
);

WriteLiteral(" />\r\n                            </p>\r\n                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(">\r\n                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 7561), Tuple.Create("\"", 7603)
, Tuple.Create(Tuple.Create("", 7567), Tuple.Create<System.Object, System.Int32>(Href("~/Content/adminDefault/img/task6.png")
, 7567), false)
);

WriteLiteral(" />\r\n                            </p>\r\n                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(">\r\n                                TaskUpdateInfoDTO信息：\r\n                        " +
"    </p>\r\n                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(">\r\n                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 7891), Tuple.Create("\"", 7933)
, Tuple.Create(Tuple.Create("", 7897), Tuple.Create<System.Object, System.Int32>(Href("~/Content/adminDefault/img/task7.png")
, 7897), false)
);

WriteLiteral(" />\r\n                            </p>\r\n                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral(" style=\"color:green;\"");

WriteLiteral(">    注意：以上接口的相关WebApi信息可参照基础信息平台服务注册中的任务调度模块的Api信息，服务注册中有详细的Api说明。</p>\r\n</div>\r\n " +
"                   </td>\r\n\r\n                </tr>\r\n\r\n            </table>\r\n\r\n\r\n " +
"       </div>\r\n\r\n\r\n\r\n\r\n\r\n\r\n    </div>\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"background: #fff; margin-bottom: 10px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"orm_action1\"");

WriteLiteral(">\r\n\r\n\r\n            <table");

WriteLiteral(" class=\"orm_action\"");

WriteLiteral(">\r\n\r\n\r\n                <tr>\r\n                    <td");

WriteLiteral(" class=\"orm_action_title\"");

WriteLiteral(">\r\n                        四、简单示例\r\n                    </td>\r\n\r\n                <" +
"/tr>\r\n                <tr>\r\n                    <td>\r\n                        <d" +
"iv");

WriteLiteral(" style=\"padding:15px;\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" class=\"orm_item_title_note1\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 8732), Tuple.Create("\"", 8774)
, Tuple.Create(Tuple.Create("", 8738), Tuple.Create<System.Object, System.Int32>(Href("~/Content/adminDefault/img/task8.png")
, 8738), false)
);

WriteLiteral(" /></p>\r\n\r\n                         \r\n                        </div>\r\n           " +
"         </td>\r\n\r\n                </tr>\r\n\r\n            </table>\r\n\r\n\r\n        </d" +
"iv>\r\n\r\n\r\n\r\n\r\n\r\n\r\n    </div>\r\n\r\n    \r\n\r\n</div>\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
