#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/SystemManage/Views/ExcelImportTemplate/SetFieldForm.cshtml")]
    public partial class _Areas_SystemManage_Views_ExcelImportTemplate_SetFieldForm_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_SystemManage_Views_ExcelImportTemplate_SetFieldForm_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\SystemManage\Views\ExcelImportTemplate\SetFieldForm.cshtml"
  
    ViewBag.Title = "用户组管理";
    Layout = "~/Views/Shared/_Form.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\n    .dataSources {\r\n        display: none;\r\n    }\r\n</style>\r\n<div");

WriteLiteral(" style=\" margin-top: 20px; margin-right: 20px;\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">设置字段<font");

WriteLiteral(" face=\"宋体\"");

WriteLiteral(">*</font></th>\r\n            <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"F_FliedLabel\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" isvalid=\"yes\"");

WriteLiteral(" checkexpession=\"NotNull\"");

WriteLiteral(" readonly />\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">关联类型<font");

WriteLiteral(" face=\"宋体\"");

WriteLiteral(">*</font></th>\r\n            <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"F_RelationType\"");

WriteLiteral(" type=\"select\"");

WriteLiteral(" class=\"ui-select\"");

WriteLiteral(" isvalid=\"yes\"");

WriteLiteral(" checkexpession=\"NotNull\"");

WriteLiteral(">\r\n                </div>\r\n            </td>\r\n        </tr>\r\n        <tr");

WriteLiteral(" class=\"dataSources dataValue\"");

WriteLiteral(">\r\n            <th");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">固定数值<font");

WriteLiteral(" face=\"宋体\"");

WriteLiteral(">*</font></th>\r\n            <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"F_Value\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n        <tr");

WriteLiteral(" class=\"dataSources dataDataItem\"");

WriteLiteral(">\r\n            <th");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">数据字典<font");

WriteLiteral(" face=\"宋体\"");

WriteLiteral(">*</font></th>\r\n            <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"F_DataItemEncode\"");

WriteLiteral(" type=\"selectTree\"");

WriteLiteral(" class=\"ui-select\"");

WriteLiteral("></div>\r\n            </td>\r\n        </tr>\r\n        <tr");

WriteLiteral(" class=\"dataSources dataDataDb\"");

WriteLiteral(">\r\n            <th");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">数据库<font");

WriteLiteral(" face=\"宋体\"");

WriteLiteral(">*</font></th>\r\n            <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"F_DbId\"");

WriteLiteral(" type=\"select\"");

WriteLiteral(" class=\"ui-select\"");

WriteLiteral("></div>\r\n            </td>\r\n        </tr>\r\n        <tr");

WriteLiteral(" class=\"dataSources dataDataDb\"");

WriteLiteral(">\r\n            <th");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">数据表<font");

WriteLiteral(" face=\"宋体\"");

WriteLiteral(">*</font></th>\r\n            <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"F_DbTable\"");

WriteLiteral(" type=\"select\"");

WriteLiteral(" class=\"ui-select\"");

WriteLiteral(" ></div>\r\n            </td>\r\n        </tr>\r\n        <tr");

WriteLiteral(" class=\"dataSources dataDataDb\"");

WriteLiteral(">\r\n            <th");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">对应字段<font");

WriteLiteral(" face=\"宋体\"");

WriteLiteral(">*</font></th>\r\n            <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"F_DbRelationFlied\"");

WriteLiteral(" type=\"select\"");

WriteLiteral(" class=\"ui-select\"");

WriteLiteral("></div>\r\n            </td>\r\n        </tr>\r\n        <tr");

WriteLiteral(" class=\"dataSources dataDataDb\"");

WriteLiteral(">\r\n            <th");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">保存字段<font");

WriteLiteral(" face=\"宋体\"");

WriteLiteral(">*</font></th>\r\n            <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"F_DbSaveFlied\"");

WriteLiteral(" type=\"select\"");

WriteLiteral(" class=\"ui-select\"");

WriteLiteral(" ></div>\r\n            </td>\r\n        </tr>\r\n    </table>\r\n</div>\r\n<script>\r\n    v" +
"ar data = {};\r\n    data.F_FliedLabel = decodeURI(request(\'F_FliedLabel\'));\r\n    " +
"data.F_RelationType = decodeURI(request(\'F_RelationType\'));\r\n    data.F_DataItem" +
"Encode = decodeURI(request(\'F_DataItemEncode\'));\r\n    data.F_Value = decodeURI(r" +
"equest(\'F_Value\'));\r\n    data.F_DbId = decodeURI(request(\'F_DbId\'));\r\n    data.F" +
"_DbTable = decodeURI(request(\'F_DbTable\'));\r\n    data.F_DbSaveFlied = decodeURI(" +
"request(\'F_DbSaveFlied\'));\r\n    data.F_DbRelationFlied = decodeURI(request(\'F_Db" +
"RelationFlied\'));\r\n\r\n    $(function () {\r\n        initControl();\r\n        $(\'#fo" +
"rm1\').setWebControls(data);\r\n    })\r\n    //初始化控件\r\n    function initControl() {\r\n" +
"        //关联类型0:无关联,1:GUID,2:数据字典3:数据表\r\n        $(\"#F_RelationType\").comboBox({\r" +
"\n            data: [{ \"id\": 0, \"text\": \"无关联\" }, { \"id\": 1, \"text\": \"GUID\" }, { \"" +
"id\": 2, \"text\": \"数据字典\" }, { \"id\": 3, \"text\": \"数据表\" }, { \"id\": 4, \"text\": \"固定数据\" " +
"}, { \"id\": 5, \"text\": \"操作人ID\" }, { \"id\": 6, \"text\": \"操作人名字\" }, { \"id\": 7, \"text\"" +
": \"操作时间\" }],\r\n            id: \"id\",\r\n            text: \"text\",\r\n            sele" +
"ctOne: true,\r\n            description: \"\",\r\n            maxHeight: \"140px\",\r\n   " +
"     }).bind(\'change\', function () {\r\n            var value = $(this).attr(\'data" +
"-value\');\r\n            if (value == \"2\") {\r\n                $(\'.dataDataDb\').hid" +
"e();\r\n                $(\'.dataValue\').hide();\r\n                $(\'.dataDataItem\'" +
").show();\r\n            }\r\n            else if (value == \"3\") {\r\n                " +
"$(\'.dataDataItem\').hide();\r\n                $(\'.dataValue\').hide();\r\n           " +
"     $(\'.dataDataDb\').show();\r\n            }\r\n            else if (value == \"4\")" +
" {\r\n                $(\'.dataDataItem\').hide();\r\n                $(\'.dataDataDb\')" +
".hide();\r\n                $(\'.dataValue\').show();\r\n            }\r\n            el" +
"se {\r\n                $(\'.dataSources\').hide();\r\n            }\r\n        });\r\n   " +
"     //绑定数据表\r\n        $(\"#F_DbId\").comboBox({});\r\n        $(\"#F_DbTable\").comboB" +
"ox({});\r\n        $(\"#F_DbSaveFlied\").comboBox({});\r\n        $(\"#F_DbRelationFlie" +
"d\").comboBox({});\r\n        //数据字典\r\n        $(\"#F_DataItemEncode\").comboBoxTree({" +
"\r\n            url: \"../../SystemManage/DataItem/GetTreeJson\",\r\n            maxHe" +
"ight: \"120px\",\r\n            allowSearch:true\r\n        });\r\n        //数据库\r\n      " +
"  learun.getDataForm({\r\n            type: \"get\",\r\n            url: \"../../System" +
"Manage/DataBaseLink/GetListJson\",\r\n            async: true,\r\n            success" +
": function (data) {\r\n                $(\"#F_DbId\").unbind();\r\n                $(\"" +
"#F_DbId\").bind(\'change\', function () {\r\n                    var dbId = $(this).a" +
"ttr(\'data-value\');\r\n                    //数据表\r\n                    $(\"#F_DbTable" +
"\").unbind();\r\n                    $(\"#F_DbTable\").bind(\'change\', function () {\r\n" +
"                        var tableName = $(this).attr(\'data-value\');\r\n           " +
"             //数据字段\r\n                        learun.getDataForm({\r\n             " +
"               type: \"get\",\r\n                            url: \"../../SystemManag" +
"e/DataBaseTable/GetTableFiledListJson\",\r\n                            param: { da" +
"taBaseLinkId: dbId, tableName: tableName },\r\n                            async: " +
"true,\r\n                            success: function (filedData) {\r\n            " +
"                    $(\"#F_DbSaveFlied\").comboBox({\r\n                            " +
"        data: filedData,\r\n                                    id: \"f_column\",\r\n " +
"                                   text: \"f_column\",\r\n                          " +
"          selectOne: true,\r\n                                    maxHeight: \"160p" +
"x\",\r\n                                    description: \"\"\r\n                      " +
"          });\r\n                                $(\"#F_DbRelationFlied\").comboBox(" +
"{\r\n                                    data: filedData,\r\n                       " +
"             id: \"f_column\",\r\n                                    text: \"f_colum" +
"n\",\r\n                                    selectOne: true,\r\n                     " +
"               maxHeight: \"160px\",\r\n                                    descript" +
"ion: \"\"\r\n                                });\r\n                            }\r\n   " +
"                     });\r\n                    });\r\n                    $(\"#F_DbT" +
"able\").comboBox({\r\n                        url: \"../../SystemManage/DataBaseTabl" +
"e/GetTableListJson\",\r\n                        param: { dataBaseLinkId: dbId },\r\n" +
"                        id: \"f_name\",\r\n                        text: \"f_name\",\r\n" +
"                        selectOne: true,\r\n                        maxHeight: \"80" +
"px\",\r\n                        description: \"\",\r\n                        allowSea" +
"rch: true\r\n                    });\r\n                });\r\n                $(\"#F_D" +
"bId\").comboBox({\r\n                    data: data,\r\n                    id: \"F_Da" +
"tabaseLinkId\",\r\n                    text: \"F_DBAlias\",\r\n                    sele" +
"ctOne: true,\r\n                    maxHeight: \"140px\",\r\n                    descr" +
"iption: \"\"\r\n                });\r\n            }\r\n        });\r\n    }\r\n    //保存表单\r\n" +
"    function AcceptClick(callback) {\r\n        var postData = $(\"#form1\").GetWebC" +
"ontrols();\r\n        postData.F_DataItemName = $(\'#F_DataItemEncode\').attr(\'data-" +
"text\');\r\n        if (postData.F_RelationType == \"2\" && !postData.F_DataItemEncod" +
"e)\r\n        {\r\n            learun.dialogTop({ msg: \"请选择数据字典\", type: \"error\" });\r" +
"\n            return false;\r\n        }\r\n        if (postData.F_RelationType == \"4" +
"\" && !postData.F_Value) {\r\n            learun.dialogTop({ msg: \"请固定值\", type: \"er" +
"ror\" });\r\n            return false;\r\n        }\r\n        callback(postData);\r\n   " +
"     learun.dialogClose();\r\n    }\r\n</script>\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
