#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Infoearth.Application.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/JXGeoManage/Views/TBL_LANDSETTLEMENT/TBL_LANDSETTLEMENTForm.cshtml")]
    public partial class _Areas_JXGeoManage_Views_TBL_LANDSETTLEMENT_TBL_LANDSETTLEMENTForm_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_JXGeoManage_Views_TBL_LANDSETTLEMENT_TBL_LANDSETTLEMENTForm_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\JXGeoManage\Views\TBL_LANDSETTLEMENT\TBL_LANDSETTLEMENTForm.cshtml"
  
    ViewBag.Title = "表单页面";
    Layout = "~/Views/Shared/_Form.cshtml";

            
            #line default
            #line hidden
WriteLiteral(@"
<style>
    input {
        background: transparent !important;
        border-left: none !important;
        border-top: none !important;
        border-right: none !important;
    }

    .title .formValue input {
        border-left: none !important;
        border-top: none !important;
        border-right: none !important;
    }

    td {
        border: 1px solid #ccc;
        text-align: center !important;
    }

    .title td {
        border: none;
    }

    .formValue {
        background: #fff;
    }

    .formTitle {
        height: 30px;
        white-space: inherit !important;
    }

    #xgjl {
        position: relative;
    }

    .timeflag {
        width: 100px;
        display: inline-block;
        position: absolute;
        top: -10px;
    }

    .actives {
        background: #ccc!important;
    }

    .radio {
        display: inline-block;
        width: 20px;
        height: 20px;
        border-radius: 50%;
        border: 1px solid #5a5a5a;
        cursor: pointer;
        background: #fff;
    }
</style>
<div");

WriteLiteral(" style=\"height: 100%; overflow-x: hidden;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"xgjl\"");

WriteLiteral(" style=\"text-align: center; width: 80%; border-bottom: 1px solid #ddd; margin: 40" +
"px auto; display: none;\"");

WriteLiteral("></div>\r\n    <ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(">\r\n        <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(" id=\"li_FIRST\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#FIRST\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">第一页</a></li>\r\n        <li");

WriteLiteral(" id=\"li_DMT\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#DMT\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">多媒体</a></li>\r\n        <li");

WriteLiteral(" style=\"float: right; margin-right: 25px; display: none;\"");

WriteLiteral(" id=\"li_close\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" style=\"border: 1px solid #ccc; border-radius: 4px; margin-top: 5px; padding: 5px" +
" 10px;\"");

WriteLiteral(" onclick=\"thisClose(\'DZLSSJCX\')\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-close\"");

WriteLiteral("></i>关闭</a>\r\n        </li>\r\n    </ul>\r\n    <div");

WriteLiteral(" id=\"myTabContent\"");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(" style=\"height: calc(100% - 45px);\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"tab-pane fade in active\"");

WriteLiteral(" id=\"FIRST\"");

WriteLiteral(" style=\"height: 100%; width: 100%;\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" class=\"form\"");

WriteLiteral(" style=\"margin-top: 5px\"");

WriteLiteral(">\r\n                <tr");

WriteLiteral(" class=\"title\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">图幅名称</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral(" style=\"background: transparent\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"MAPNAME\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">图幅编号</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral(" style=\"background: transparent\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"MAPID\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral("><font>*</font>名称</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"DISASTERUNITNAME\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" isvalid=\"yes\"");

WriteLiteral(" checkexpession=\"NotNull\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" style=\"background: transparent; display: none\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"PROJECTID\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">野外编号</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"OUTDOORCODE\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">室内编号</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"INDOORCODE\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">发生时间</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"HAPPENTIME\"");

WriteLiteral(" class=\"form-control input-wdatepicker\"");

WriteLiteral(" onfocus=\"WdatePicker()\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">项目名称</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(" style=\"background: transparent\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"PROJECTNAME\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"单击选择项目\"");

WriteLiteral(" onclick=\"SelectPrj()\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral("><font>*</font>统一编号</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"UNIFIEDCODE\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" onclick=\"btn_Create()\"");

WriteLiteral(" placeholder=\"点击获取统一编号\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" isvalid=\"yes\"");

WriteLiteral(" checkexpession=\"NotNull\"");

WriteLiteral(" style=\"width: 172px!important; display: inline-block\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">地理位置</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"LOCATION\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" rowspan=\"6\"");

WriteLiteral(">地理位置</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"PROVINCE\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"PROVINCENAME\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">省</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"CITY\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"CITYNAME\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"COUNTY\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"COUNTYNAME\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">市（县）</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" id=\"districtControl\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"TOWN\"");

WriteLiteral(" type=\"select\"");

WriteLiteral(" class=\"ui-select\"");

WriteLiteral(" style=\"float: left;\"");

WriteLiteral(">\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"TOWN1\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"TOWNNAME\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">乡镇</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"VILLAGE\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">村</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"TEAM\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">组</td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" rowspan=\"3\"");

WriteLiteral(">坐标</td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">X</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"X\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" rowspan=\"2\"");

WriteLiteral(">经纬度</td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">经度</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"LONGITUDE\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" onblur=\"isJD(this)\"");

WriteLiteral(" placeholder=\"双击获取经纬度\"");

WriteLiteral(" ondblclick=\"position_select()\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" rowspan=\"1\"");

WriteLiteral(">分带</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"FD\"");

WriteLiteral(" type=\"select\"");

WriteLiteral(" class=\"ui-select\"");

WriteLiteral("></div>\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" onclick=\"xyChange();\"");

WriteLiteral(" style=\"background: #ccc; cursor: pointer; border-radius: 4px; margin-left: 7%;\"");

WriteLiteral(">XY->BL</div>\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">Y</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"Y\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">纬度</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"LATITUDE\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" onblur=\"isJD(this)\"");

WriteLiteral(" placeholder=\"双击获取经纬度\"");

WriteLiteral(" ondblclick=\"position_select()\"");

WriteLiteral(" />\r\n                    </td>\r\n\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" rowspan=\"1\"");

WriteLiteral(">坐标系</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"ZBX\"");

WriteLiteral(" type=\"select\"");

WriteLiteral(" class=\"ui-select\"");

WriteLiteral("></div>\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" onclick=\"lonChange();\"");

WriteLiteral(" style=\"background: #ccc; cursor: pointer; border-radius: 4px; margin-left: 7%;\"");

WriteLiteral(">BL->XY</div>\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">Z</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"Z\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n\r\n                </tr>\r\n                <tr>\r\n  " +
"                  <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" rowspan=\"3\"");

WriteLiteral(">沉降类型</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"9\"");

WriteLiteral(" rowspan=\"3\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"SETTLEMENTTYPE\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" rowspan=\"3\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">沉降中心位置</td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">行政区域</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"SETTLEMENTCENTERLOCATION\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" rowspan=\"2\"");

WriteLiteral(">经纬度</td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">经度</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"SETTLEMENTCENTERLONGITUDE\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">纬度</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"SETTLEMENTCENTERLATITUDE\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"18\"");

WriteLiteral(">沉降规模</td>\r\n                </tr>\r\n                <tr>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(">沉降区面积/km²</td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(">年平均沉降量/mm</td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">历年累计沉降量/mm</td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">平均沉降速率(mm/s)</td>\r\n                </tr>\r\n                <tr>\r\n                " +
"    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"SETTLEMENTAREA\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"AVERAGEYEARSETTLEMENTVOLUME\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"ACCUMULATIVESETTLEMENTVOLUME\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"AVERAGESETTLEMENTRATE\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">地形地貌</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"TOPOGRAPHY\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">地质构造及活动情况</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"GEOLOGICALSTRUCTURE\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral("></textarea>\r\n                    </td>\r\n                </tr>\r\n                <" +
"tr>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"18\"");

WriteLiteral(">第四系覆盖层特征</td>\r\n                </tr>\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">岩性</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"LITH\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">厚度</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"DEPTH\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">结构</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ARCH\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">空间变化规律</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"SPACECHANGELAW\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">水文地质特征</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"HYDROLOGYGEOLOGYFEATURE\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">主要沉降层位</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"MAINSETTLEMENTLOCATION\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"18\"");

WriteLiteral(">沉降区地下水概况</td>\r\n                </tr>\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">年开采量(m³)</td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">年补给量(m³)</td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">地下水埋深(m)</td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">年水位变化幅度(m³)</td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">其它</td>\r\n                </tr>\r\n                <tr>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"YEARMININGVOLUME\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"YEARSUPPLYVOLUME\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"GROUNDWATERDEPTH\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"YEARWATLEVCHANGEMARGIN\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"OTHER\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n    " +
"                <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"18\"");

WriteLiteral(">引发诱发沉降原因及变化规律</td>\r\n                </tr>\r\n                <tr>\r\n               " +
"     <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">诱发沉降原因</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"INDUCEDSUBSIDENCECAUSES\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral("></textarea>\r\n                    </td>\r\n                </tr>\r\n                <" +
"tr>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">变化规律</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"CHANGELAW\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral("></textarea>\r\n                    </td>\r\n                </tr>\r\n                <" +
"tr>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"18\"");

WriteLiteral(">沉降现状及发展趋势</td>\r\n                </tr>\r\n                <tr>\r\n                   " +
" <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">沉降现状</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"SETTLEMENTCURRENTSITUATION\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral("></textarea>\r\n                    </td>\r\n                </tr>\r\n                <" +
"tr>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">发展趋势</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"DEVELOPMENTTREND\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral("></textarea>\r\n                    </td>\r\n                </tr>\r\n                <" +
"tr>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"18\"");

WriteLiteral(">主要危害及经济损失</td>\r\n                </tr>\r\n                <tr>\r\n                   " +
" <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">主要危害</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"MAINHARM\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral("></textarea>\r\n                    </td>\r\n                </tr>\r\n                <" +
"tr>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">经济损失</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" id=\"ECONOMICLOSSES\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral("></textarea>\r\n                    </td>\r\n                </tr>\r\n                <" +
"tr>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"18\"");

WriteLiteral(">治理措施及效果</td>\r\n                </tr>\r\n                <tr>\r\n                    <" +
"td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">治理措施</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"CONTROLMEASURES\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral("></textarea>\r\n                    </td>\r\n                </tr>\r\n                <" +
"tr>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">治理效果</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"CONTROLEFFECT\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral("></textarea>\r\n                    </td>\r\n                </tr>\r\n                <" +
"tr>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">死亡人数（人）</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"DEATHSPEOPLE\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">直接损失（万元）</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"DIRECTLOSS\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">威胁房屋（户）</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"1\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"THREATENHOME\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">威胁人数（人）</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"THREATENPEOPLE\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">是否隐患点</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"HIDDENDANGER\"");

WriteLiteral("></div>\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" colspan=\"1\"");

WriteLiteral(">重大隐患点</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"ISZDYHD\"");

WriteLiteral("></div>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n" +
"                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">威胁财产（万元）</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"THREATENASSETS\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">灾险情规模等级</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"6\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"DISASTERRISKLEVEL\"");

WriteLiteral("></div>\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">目前稳定状态</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"CURSTABLESTATUS\"");

WriteLiteral("></div>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n" +
"                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">灾情等级</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"DISASTERLEVEL\"");

WriteLiteral("></div>\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">险情等级</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"DANGERLEVEL\"");

WriteLiteral("></div>\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">失踪人数</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"MISSINGPERSON\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">受伤人数</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"INJUREDPERSON\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n\r\n                <tr>\r\n  " +
"                  <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">威胁对象</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"THREATENOBJECT\"");

WriteLiteral("></div>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n" +
"                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">危害对象</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"DESTROYEDOBJECT\"");

WriteLiteral("></div>\r\n                    </td>\r\n                </tr>\r\n                ");

WriteLiteral("\r\n                <tr>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">野外记录信息</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"17\"");

WriteLiteral(">\r\n                        <textarea");

WriteLiteral(" id=\"OUTDOORRECORD\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral("></textarea>\r\n                    </td>\r\n                </tr>\r\n                <" +
"tr>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">遥感解译点</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"ISRSPNT\"");

WriteLiteral("></div>\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">勘查点</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"ISSURVEYPNT\"");

WriteLiteral("></div>\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">测绘点</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"ISMEASURINGPNT\"");

WriteLiteral("></div>\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">防灾预案</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"PREVENTIONPLAN\"");

WriteLiteral("></div>\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">监测点</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"ISMONITORPNT\"");

WriteLiteral("></div>\r\n                    </td>\r\n                </tr>\r\n                <tr");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">调查负责人:</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" style=\"background: transparent\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"SURVEYHEADER\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">填表人:</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(" style=\"background: transparent\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"FILLTABLEPEOPLE\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">审核人：</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(" style=\"background: transparent\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"VERIFYPEOPLE\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">调查日期:</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(" style=\"background: transparent\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"FILLTABLEDATE\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control input-wdatepicker\"");

WriteLiteral(" onfocus=\"WdatePicker()\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">\r\n                    <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">数据来源</td>\r\n                    <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"DATASOURCE\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n            </table>\r\n    " +
"    </div>\r\n        <div");

WriteLiteral(" class=\"tab-pane fade\"");

WriteLiteral(" id=\"DMT\"");

WriteLiteral(" style=\"height: 100%; width: 100%;\"");

WriteLiteral(">\r\n            <iframe");

WriteLiteral(" class=\"LRADMS_iframe\"");

WriteLiteral(" id=\"MultMedia\"");

WriteLiteral(" frameborder=\"0\"");

WriteLiteral(" src=\"\"");

WriteLiteral(" style=\"border: none; width: 100%; height: 100%;\"");

WriteLiteral("></iframe>\r\n        </div>\r\n    </div>\r\n\r\n</div>\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 25541), Tuple.Create("\"", 25609)
, Tuple.Create(Tuple.Create("", 25547), Tuple.Create<System.Object, System.Int32>(Href("~/Content/scripts/plugins/infoearthcustom/dictionaryControl.js")
, 25547), false)
);

WriteLiteral("></script>\r\n<script>\r\n    var keyValue = request(\'keyValue\');\r\n    var details = " +
"request(\'details\');\r\n    var guid = request(\'guid\');  //历史数据的GUID \r\n    var TYBH" +
" = request(\'TYBH\');  //编号\r\n    var authToken = getAuthorizationToken();\r\n    var" +
" callback = request(\'callback\');//\"返回\"跳转url\r\n    var showNew = request(\'showNew\'" +
");\r\n    var dmt = request(\'dmt\');\r\n    var DATASOURCE = request(\'DATASOURCE\');\r\n" +
"    var localname = \"\";\r\n    var townnames = \"\";\r\n    var villagenames = \"\";\r\n  " +
"  var teamnames = \"\";\r\n    $(function () {\r\n        $(\"#DISASTERLEVEL\").dictiona" +
"ryControl({ dicCode: \"DISASTERLEVEL\", type: \"radio\" });\r\n        $(\"#DANGERLEVEL" +
"\").dictionaryControl({ dicCode: \"DANGERLEVEL\", type: \"radio\" });\r\n        $(\"#HI" +
"DDENDANGER\").dictionaryControl({ dicCode: \"HIDDENDANGER\", type: \"radio\" }); \r\n  " +
"      $(\"#ISZDYHD\").dictionaryControl({ dicCode: \"HIDDENDANGER\", type: \"radio\" }" +
");\r\n        $(\"#CURSTABLESTATUS\").dictionaryControl({ dicCode: \"CURSTABLESTATUSH" +
"P\", type: \"radio\" });\r\n        $(\"#DISASTERRISKLEVEL\").dictionaryControl({ dicCo" +
"de: \"MONOCOLEVEL3TX\", type: \"radio\" });\r\n        $(\"#DESTROYEDOBJECT\").dictionar" +
"yControl({ dicCode: \"DESTROYEDOBJTX\", type: \"checkbox\" });\r\n        $(\"#THREATEN" +
"OBJECT\").dictionaryControl({ dicCode: \"DESTROYEDOBJTX\", type: \"checkbox\" });\r\n\r\n" +
"        $(\"#ISRSPNT\").dictionaryControl({ dicCode: \"HIDDENDANGER\", type: \"radio\"" +
" });\r\n        $(\"#ISSURVEYPNT\").dictionaryControl({ dicCode: \"HIDDENDANGER\", typ" +
"e: \"radio\" });\r\n        $(\"#ISMEASURINGPNT\").dictionaryControl({ dicCode: \"HIDDE" +
"NDANGER\", type: \"radio\" });\r\n        $(\"#ISMONITORPNT\").dictionaryControl({ dicC" +
"ode: \"HIDDENDANGER\", type: \"radio\" });\r\n        $(\"#PREVENTIONPLAN\").dictionaryC" +
"ontrol({ dicCode: \"HIDDENDANGER\", type: \"radio\" });\r\n        $(\"#FD\").comboBox({" +
"\r\n            data: [{ \"id\": 1, \"text\": \"6度分带\" }, { \"id\": 0, \"text\": \"3度分带\" }],\r" +
"\n            id: \"id\",\r\n            text: \"text\",\r\n            height: \"50px\"\r\n " +
"       });\r\n        $(\"#ZBX\").comboBox({\r\n            data: [{ \"id\": 1, \"text\": " +
"\"西安80坐标系\" }, { \"id\": 0, \"text\": \"北京54坐标系\" }],\r\n            id: \"id\",\r\n          " +
"  text: \"text\",\r\n            height: \"50px\"\r\n        });\r\n        if (callback) " +
"{\r\n            if (showNew) {\r\n                $(\"#li_close\").show();\r\n         " +
"   }\r\n            $(\"#xgjl\").show();\r\n            var flag = request(\'flag\');\r\n " +
"           if (flag.indexOf(\"false\") != -1) {\r\n                $(\"#xgjl\").hide()" +
";\r\n            }\r\n            if (TYBH) {\r\n                var queryJson = { \'Un" +
"ifyCode\': TYBH }\r\n                $.ajax({\r\n                    url: \"../../api/" +
"TBL_HAZARDBASICINFOApi/GetSingleFillListJson?queryJson=\" + JSON.stringify(queryJ" +
"son),\r\n                    beforeSend: function (a) {\r\n                        a" +
".setRequestHeader(\"Authorization\", authToken);\r\n                    },\r\n        " +
"            type: \'GET\',\r\n                    dataType: \"json\",\r\n               " +
"     success: function (data) {\r\n                        console.log(data);\r\n   " +
"                     if (data) {\r\n                            var str = \"\", clas" +
" = \'\';\r\n                            if (data.length > 0) {\r\n                    " +
"            var mag = ($(\'#xgjl\').width() - 100 * data.length) / (data.length + " +
"1)\r\n                                for (var i = 0; i < data.length; i++) {\r\n   " +
"                                 clas = i == data.length - 1 ? \'actives\' : \'\';\r\n" +
"                                    if (data[i].MODIFYTIME != null) {\r\n         " +
"                               data[i].MODIFYTIME = data[i].MODIFYTIME.slice(0, " +
"10);\r\n                                    } else {\r\n                            " +
"            data[i].MODIFYTIME = \"\";\r\n                                    }\r\n   " +
"                                 str += \'<div class=\"timeflag\" style=\"left:\' + m" +
"ag * (i + 1) + \'px\"><div class=\"radio \' + clas + \'\" onclick=\"radioGUID(\\\'\' + dat" +
"a[i].GUID + \',\' + i + \'\\\')\"></div><p>\' + data[i].MODIFYTIME + \'</p></div>\'\r\n    " +
"                            }\r\n                                $(\'#xgjl\').html(s" +
"tr);\r\n                            }\r\n                        }\r\n                " +
"    },\r\n                    cache: false\r\n\r\n                })\r\n            }\r\n " +
"       }\r\n        initControl();\r\n        $(\"#VILLAGE\").attr(\"disabled\", \"disabl" +
"ed\");\r\n        $(\"#TEAM\").attr(\"disabled\", \"disabled\");\r\n        $(\"#TOWNNAME\")." +
"blur(function () {\r\n            if ($(\"#TOWNNAME\").val() == \"\") {\r\n             " +
"   dialogMsg(\'请先填写乡镇！\', 0);\r\n                $(\"#VILLAGE\").attr(\"disabled\", \"dis" +
"abled\")\r\n                $(\"#VILLAGE\").val(\"\")\r\n            } else {\r\n          " +
"      $(\"#VILLAGE\").prop(\"disabled\", \"\");\r\n            }\r\n        })\r\n        $(" +
"\"#VILLAGE\").blur(function () {\r\n            if ($(\"#VILLAGE\").val() == \"\") {\r\n  " +
"              dialogMsg(\'请先填写村！\', 0);\r\n                $(\"#TEAM\").attr(\"disabled" +
"\", \"disabled\")\r\n                $(\"#TEAM\").val(\"\")\r\n            } else {\r\n      " +
"          $(\"#TEAM\").prop(\"disabled\", \"\")\r\n            }\r\n            $(\"#LOCATI" +
"ON\").val(dlwz + jcdname + $(\"#VILLAGE\").val());\r\n        });\r\n        $(\"#TEAM\")" +
".blur(function () {\r\n            $(\"#LOCATION\").val(dlwz + jcdname + $(\"#VILLAGE" +
"\").val() + $(\"#TEAM\").val());\r\n        });\r\n        if (details == \"01\") {\r\n    " +
"        $(\"input,.form-control\").attr(\"disabled\", \"disabled\")\r\n        }\r\n      " +
"  $(\".nav-tabs li\").click(function () {\r\n            var id = $(this).attr(\'id\')" +
".replace(\"li_\", \"\");\r\n            switch (id) {\r\n                case \"DMT\":\r\n  " +
"                  window.setTimeout(function () {\r\n                        mid =" +
" \"dcd1d0aa-1d51-4142-ae82-db812158b0da\";\r\n                        if (dmt) {\r\n  " +
"                          keyValue = dmt;\r\n                        }\r\n          " +
"              $(\'#MultMedia\').attr(\'src\', contentPath + \"/SystemManage/MultMedia" +
"/Index?moduleID=\" + mid + \"&belongObjectGuid=\" + keyValue + \"&details=\" + detail" +
"s);\r\n                    }, 300);\r\n\r\n                    break;\r\n               " +
" default:\r\n            }\r\n        });\r\n    });\r\n    //function townname(value) {" +
"\r\n    //    townnames = value;\r\n    //    var a = localname + townnames + villag" +
"enames + teamnames;\r\n    //    $(\"#LOCATION\").val(a);\r\n\r\n    //}\r\n    //function" +
" villagename(value) {\r\n    //    villagenames = value;\r\n    //    var a = localn" +
"ame + townnames + villagenames + teamnames;\r\n    //    $(\"#LOCATION\").val(a);\r\n " +
"   //}\r\n    //function teamname(value) {\r\n    //    teamnames = value;\r\n    //  " +
"  var a = localname + townnames + villagenames + teamnames;\r\n    //    $(\"#LOCAT" +
"ION\").val(a);\r\n    //}\r\n    function radioGUID(GUID) {\r\n        var GUID1 = GUID" +
".split(\",\")[0];\r\n        var a = GUID.split(\",\")[1];\r\n        $(\".timeflag div\")" +
".removeClass(\"actives\");\r\n        $($(\".timeflag\")[a].children[0]).attr(\"class\"," +
" \"radio actives\");\r\n        $(\"#form1 input\").val(\"\");\r\n        $(\"#form1 span\")" +
".text(\"\");\r\n        $(\"#form1 input\").attr(\"checked\", false);\r\n        // initSe" +
"lect();\r\n        $.SetForm({\r\n            url: \"../../api/TBL_LANDSETTLEMENT_HIS" +
"TORYApi/GetFormJson\",\r\n            param: { keyValue: GUID1 },\r\n            auth" +
"Token: authToken,\r\n            success: function (data) {\r\n                SetCo" +
"ntorl(data);\r\n            }\r\n        });\r\n    }\r\n    //初始化控件\r\n    function initC" +
"ontrol() {\r\n        //获取表单\r\n        if (!!keyValue) {\r\n            $.SetForm({\r\n" +
"                url: \"../../JXGeoManage/TBL_LANDSETTLEMENT/GetFormJson\",\r\n      " +
"          param: { keyValue: keyValue },\r\n                success: function (dat" +
"a) {\r\n                    $(\"#UNIFIEDCODE\").attr(\"disabled\", \"disabled\");\r\n     " +
"               SetContorl(data);\r\n                }\r\n            })\r\n        }\r\n" +
"        else if (!!guid) {\r\n            $.SetForm({\r\n                url: \"../.." +
"/api/TBL_LANDSETTLEMENT_HISTORYApi/GetFormJson\",\r\n                param: { keyVa" +
"lue: guid },\r\n                authToken: authToken,\r\n                success: fu" +
"nction (data) {\r\n                    SetContorl(data);\r\n                }\r\n     " +
"       });\r\n\r\n            $(\"input\").attr(\"disabled\", \"disabled\")\r\n        } els" +
"e if (TYBH) {\r\n            var queryJson = { \'UNIFIEDCODE\': TYBH }\r\n            " +
"$.SetForm({\r\n                //url: \"../../api/TBL_HAZARDBASICINFOApi/GetSingleF" +
"illListJson?queryJson=\" + JSON.stringify(queryJson),\r\n                url: \"../." +
"./JXGeoManage/TBL_LANDSETTLEMENT/GetFormJson\",\r\n                param: { keyValu" +
"e: TYBH },\r\n                authToken: authToken,\r\n                success: func" +
"tion (data) {\r\n                    if (data) {\r\n                        SetConto" +
"rl(data);\r\n                    }\r\n                }\r\n            });\r\n          " +
"  $(\"input\").attr(\"disabled\", \"disabled\")\r\n        }\r\n    }\r\n\r\n    function SetC" +
"ontorl(data) {\r\n\r\n        $(\"#form1\").SetWebControls(data);\r\n        if (data.CO" +
"UNTYCODE) {\r\n            $(\"#TOWN\").ComboBox({\r\n                url: \"../../Syst" +
"emManage/Area/GetAreaListJson\",\r\n                param: { parentId: data.COUNTYC" +
"ODE },\r\n                id: \"F_AreaCode\",\r\n                text: \"F_AreaName\",\r\n" +
"                description: \"选择乡/镇\",\r\n                height: \"170px\"\r\n        " +
"    }).bind(\"change\", function () {\r\n                $(\"#VILLAGE\").prop(\"disable" +
"d\", \"\");\r\n            });\r\n            $(\"#TOWN\").css(\"width\", \"100%\");\r\n       " +
"     $(\"#TOWN\").comboBoxSetValue(data.TOWN);\r\n        }\r\n        //$(\"#PROVINCEN" +
"AME\").val(data.LOCATION.split(\",\")[0]);\r\n        //$(\"#TOWNNAME\").val(data.LOCAT" +
"ION.split(\",\")[3]);\r\n        //$(\"#CITYNAME\").val(data.LOCATION.split(\",\")[1] + " +
"\",\" + data.LOCATION.split(\",\")[2]);\r\n        //获取项目信息\r\n        if (data && data." +
"PROJECTID) {\r\n            $.ajax({\r\n                url: \"../../api/JYGC_PROJECT" +
"BASEINFOApi/GetFormJson\",\r\n                data: { keyValue: data.PROJECTID },\r\n" +
"                type: \'GET\',\r\n                dataType: \"json\",\r\n               " +
" beforeSend: function (a) {\r\n                    a.setRequestHeader(\"Authorizati" +
"on\", authToken);\r\n                },\r\n                success: function (prj) {\r" +
"\n                    if (prj) {\r\n                        var webData = {};\r\n    " +
"                    webData[\"PROJECTNAME\"] = prj.PROJECTNAME;\r\n                 " +
"       $(\"#form1\").SetWebControls(webData);\r\n                    }\r\n            " +
"    },\r\n                cache: false\r\n\r\n            })\r\n        }\r\n    }\r\n    va" +
"r PROVINCE1 = \"\"; var jcdname = \"\", dlwz = \"\";\r\n    //生成统一编号\r\n    function btn_C" +
"reate() {\r\n        learun.dialogOpen({\r\n            id: \'Form2\',\r\n            ti" +
"tle: \'获取统一编号\',\r\n            url: \'../../JXGeoManage/TBL_HAZARDBASICINFO/CreateCo" +
"deWaterIndex?PROVINCE1=\' + $(\"#PROVINCE\").val() + \'&CITY1=\' + $(\"#CITY\").val() +" +
" \'&COUNTRY1=\' + $(\"#COUNTY\").val() + \'&tabhtml=04\',\r\n            width: \'500px\'," +
"\r\n            height: \'450px\',\r\n            isClose: true,\r\n            callBack" +
": function (iframeId) {\r\n                var data = getInfoTop().frames[iframeId" +
"].AcceptClick();\r\n                $(\"#PROVINCE\").val(data[\"provinceId\"]);\r\n     " +
"           $(\"#CITY\").val(data[\"cityId\"]);\r\n                $(\"#COUNTY\").val(dat" +
"a[\"countyId\"]);\r\n                $(\"#TOWN\").val(data[\"townId\"]);\r\n              " +
"  $(\"#UNIFIEDCODE\").val(data[\"UNIFIEDCODE\"]);\r\n                //省市县名称\r\n        " +
"        $(\"#PROVINCENAME\").val(data.provinceName);\r\n                $(\"#CITYNAME" +
"\").val(data.cityName + \",\" + data.countyName);\r\n                $(\"#COUNTYNAME\")" +
".val(data.countyName);\r\n                //localname = data.provinceName + data.c" +
"ityName + data.countyName;\r\n                $(\"#LOCATION\").val(data.provinceName" +
" + data.cityName + data.countyName);\r\n                dlwz = data.provinceName +" +
" data.cityName + data.countyName;\r\n                $(\"#TOWN\").css(\"width\", \"100%" +
"\");\r\n                $(\"#TOWN\").ComboBox({\r\n                    url: \"../../Syst" +
"emManage/Area/GetAreaListJson\",\r\n                    param: { parentId: data[\"co" +
"untyId\"] },\r\n                    id: \"F_AreaCode\",\r\n                    text: \"F" +
"_AreaName\",\r\n                    description: \"选择乡/镇\",\r\n                    heig" +
"ht: \"170px\"\r\n                }).bind(\"change\", function (ret) {\r\n               " +
"     $(\"#VILLAGE\").prop(\"disabled\", \"\");\r\n                    $(\"#LOCATION\").val" +
"(\"\");\r\n                    jcdname = ret.target.getAttribute(\"data-text\");\r\n    " +
"                $(\"#TOWNNAME\").val(jcdname);\r\n                    $(\"#LOCATION\")" +
".val(dlwz + jcdname);\r\n\r\n                });\r\n            }\r\n        });\r\n    }\r" +
"\n    //保存表单;\r\n    function AcceptClick() {\r\n        if (keyValue) {\r\n           " +
" var queryJson = { \'unifycode\': keyValue, \"type\": \"04\" }\r\n            $.ajax({\r\n" +
"                url: \"../../api/TBL_AUDITINFOApi/GetPageNoAuditListJson\",\r\n     " +
"           beforeSend: function (request) {\r\n                    request.setRequ" +
"estHeader(\"Authorization\", authToken);\r\n                },\r\n                data" +
": { queryJson: JSON.stringify(queryJson) },\r\n                type: \"get\",\r\n     " +
"           dataType: \"json\",\r\n                async: false,\r\n                suc" +
"cess: function (res) {\r\n                    if (res.rows.length > 0) {\r\n        " +
"                dialogMsg(\'该点存在未审核数据，请审核后再执行此操作！\', 0);\r\n                        " +
"return;\r\n                    } else {\r\n                        SaveInfo();\r\n    " +
"                }\r\n                },\r\n            });\r\n        } else {\r\n      " +
"      SaveInfo();\r\n        }\r\n\r\n    }\r\n    function SaveInfo() {\r\n        if (!$" +
"(\'#form1\').Validform()) {\r\n            return false;\r\n        }\r\n        var pos" +
"tData = $(\"#form1\").GetWebControls(keyValue);\r\n        if ($(\"#TOWN\").attr(\"data" +
"-text\") != undefined) {\r\n            postData.TOWNNAME = $(\"#TOWN\").text();\r\n   " +
"     }\r\n        if (postData.TOWN == \"\") {\r\n            //var Validatemsg = \"乡镇不" +
"能为空！\\n\";\r\n            //ValidationMessage($(\"#TOWN\"), Validatemsg); return false" +
";\r\n            dialogAlert(\'乡镇不能为空\', 0);\r\n            return false;\r\n        }\r\n" +
"        var dmtKey = postData.UNIFIEDCODE;\r\n        postData.DATASOURCE = DATASO" +
"URCE;\r\n        //console.log(JSON.stringify(postData))\r\n        //if ($(\"#VILLAG" +
"E\").val() == \"\") {\r\n        //    postData.LOCATION = postData.PROVINCENAME + \"," +
"\" + postData.CITYNAME + \",\" + postData.TOWNNAME;\r\n        //} else if ($(\"#TEAM\"" +
").val() == \"\") {\r\n        //    postData.LOCATION = postData.PROVINCENAME + \",\" " +
"+ postData.CITYNAME + \",\" + postData.TOWNNAME + \",\" + postData.VILLAGE;\r\n       " +
" //} else {\r\n        //    postData.LOCATION = postData.PROVINCENAME + \",\" + pos" +
"tData.CITYNAME + \",\" + postData.TOWNNAME + \",\" + postData.VILLAGE + \",\" + postDa" +
"ta.TEAM;\r\n        //}\r\n        $.SaveForm({\r\n            url: \"../../JXGeoManage" +
"/TBL_LANDSETTLEMENT/SaveForm?keyValue=\" + keyValue,\r\n            param: postData" +
",\r\n            loading: \"正在保存数据...\",\r\n            success: function (data) {\r\n  " +
"              if ($(\"#MultMedia\").attr(\"src\") != \"\") {\r\n                    $(\"#" +
"MultMedia\")[0].contentWindow.SaveFileInfo(dmtKey);\r\n                }\r\n         " +
"       try {\r\n                    getInfoTop().learun.currentIframe().$(\'#gridTa" +
"ble\').trigger(\'reloadGrid\');\r\n                } catch (e) {\r\n                   " +
" window.parent.$(\'#gridTable\').trigger(\'reloadGrid\');\r\n                }\r\n      " +
"      }\r\n        })\r\n    }\r\n    //加载项目\r\n    function SelectPrj() {\r\n        dial" +
"ogOpen({\r\n            id: \'ProjectForm\',\r\n            title: \'选择项目\',\r\n          " +
"  url: \'../../JXGeoManage/JYGC_PROJECTBASEINFO/JYGC_PROJECTBASEINFOIndex\',\r\n    " +
"        width: \'800px\',\r\n            height: \'500px\',\r\n            callBack: fun" +
"ction (iframeId) {\r\n                var data = getInfoTop().frames[iframeId].Acc" +
"eptClick();\r\n                if (data) {\r\n                    var webData = {};\r" +
"\n                    webData[\"PROJECTID\"] = data[\"PROJECTGUID\"];\r\n              " +
"      webData[\"PROJECTNAME\"] = data[\"PROJECTNAME\"];\r\n                    $(\"#for" +
"m1\").SetWebControls(webData);\r\n                }\r\n            }\r\n        });\r\n  " +
"  }\r\n    //获取经纬度\r\n    function position_select() {\r\n        var lon = $(\'#LONGIT" +
"UDE\').val();\r\n        var lat = $(\'#LATITUDE\').val();\r\n        if (!lon && !lat)" +
" {\r\n            var UNIFIEDCODE = $(\'#UNIFIEDCODE\').val();\r\n            if (UNIF" +
"IEDCODE) {\r\n                $.ajax({\r\n                    url: SSOURL + \"/api/Ad" +
"ministrativeApi/GetDistrctByCodes/\" + UNIFIEDCODE.slice(0, 6),\r\n                " +
"    beforeSend: function (request) {\r\n                        request.setRequest" +
"Header(\"Authorization\", authToken);\r\n                    },\r\n                   " +
" async: false,\r\n                    data: { keyValue: UNIFIEDCODE },\r\n          " +
"          type: \"GET\",\r\n                    success: function (res) {\r\n         " +
"               res = res.Result[0];\r\n                        lon = res.F_LONGITU" +
"DE;\r\n                        lat = res.F_LATITUDE;\r\n                    },\r\n    " +
"            });\r\n            }\r\n        }\r\n        dialogOpen({\r\n            id:" +
" \'TBL_YJBZ_POSITIONSelect\',\r\n            title: \'获取经纬度信息\',\r\n            url: \'.." +
"/../JXGeoManage/TBL_QCQF_ADMINISTRATIVE/TBL_YJBZ_POSITIONSelect?lon=\' + lon + \'&" +
"lat=\' + lat,\r\n            width: \'970px\',\r\n            height: \"450px\",\r\n       " +
"     isClose: true,\r\n            callBack: function (iframeId) {\r\n              " +
"  var dt1 = getInfoTop().frames[iframeId].$(\'#LONGITUDE\').val();\r\n              " +
"  var dt2 = getInfoTop().frames[iframeId].$(\'#LATITUDE\').val();\r\n               " +
" $(\'#LONGITUDE\').val(dt1);\r\n                $(\'#LATITUDE\').val(dt2);\r\n          " +
"      $(\"#X\").val(\"\");\r\n                $(\"#Y\").val(\"\");\r\n                $(\"#FD" +
"\").comboBoxSetValue(\"\");\r\n                $(\"#ZBX\").comboBoxSetValue(\"\");\r\n     " +
"       }\r\n        });\r\n    }\r\n    function xyChange() {\r\n        var x = \"\", y =" +
" \"\", csStr = \"\", numberNameStr = \"\";\r\n        x = $(\"#X\").val(); y = $(\"#Y\").val" +
"(); csStr = $($(\"#ZBX\")[0]).attr(\"data-text\"); numberNameStr = $($(\"#FD\")[0]).at" +
"tr(\"data-text\");\r\n        if (!x && !y) {\r\n            dialogAlert(\'请输入x,y的值！\');" +
"\r\n            return;\r\n        } else if (!x) {\r\n            dialogAlert(\'请输入x的值" +
"！\');\r\n            return;\r\n        } else if (!y) {\r\n            dialogAlert(\'请输" +
"入y的值！\');\r\n            return;\r\n        }\r\n        if (!numberNameStr && !csStr &" +
"& csStr != \"==请选择==\" && numberNameStr != \"==请选择==\") {\r\n            dialogAlert(\'" +
"请选择分带和坐标系！\');\r\n            return;\r\n        } else if (!numberNameStr && csStr !" +
"= \"==请选择==\") {\r\n            dialogAlert(\'请选择分带！\');\r\n            return;\r\n       " +
" } else if (!csStr && csStr != \"==请选择==\") {\r\n            dialogAlert(\'请选择坐标系！\');" +
"\r\n            return;\r\n        }\r\n        $.ajax({\r\n            url: \"../../JXGe" +
"oManage/TBL_HAZARDBASICINFO/btnXYtoBL\",\r\n            beforeSend: function (reque" +
"st) {\r\n                request.setRequestHeader(\"Authorization\", authToken);\r\n  " +
"          },\r\n            async: false,\r\n            data: { _x: x, _y: y, csStr" +
": csStr, numberNameStr: numberNameStr },\r\n            type: \"GET\",\r\n            " +
"success: function (res) {\r\n                var data = JSON.parse(res);\r\n        " +
"        if (data.lon != \"\") {\r\n                    $(\"#LONGITUDE\").val(data.lon)" +
"\r\n                }\r\n                if (data.lat != \"\") {\r\n                    " +
"$(\"#LATITUDE\").val(data.lat)\r\n                }\r\n            },\r\n        });\r\n  " +
"  }\r\n    function lonChange() {\r\n        var lon = \"\", lat = \"\", csStr = \"\", num" +
"berNameStr = \"\";\r\n        lon = $(\"#LONGITUDE\").val(); lat = $(\"#LATITUDE\").val(" +
"); csStr = $($(\"#ZBX\")[0]).attr(\"data-text\"); numberNameStr = $($(\"#FD\")[0]).att" +
"r(\"data-text\");\r\n        if (!lon && !lat) {\r\n            dialogAlert(\'请先选择经纬度！\'" +
");\r\n            return;\r\n        }\r\n        if (!numberNameStr && !csStr && csSt" +
"r == \"==请选择==\" && numberNameStr == \"==请选择==\") {\r\n            dialogAlert(\'请选择分带和" +
"坐标系！\');\r\n            return;\r\n        } else if (!numberNameStr && numberNameStr" +
" == \"==请选择==\") {\r\n            dialogAlert(\'请选择分带！\');\r\n            return;\r\n     " +
"   } else if (!csStr && csStr == \"==请选择==\") {\r\n            dialogAlert(\'请选择坐标系！\'" +
");\r\n            return;\r\n        }\r\n        $.ajax({\r\n            url: \"../../JX" +
"GeoManage/TBL_HAZARDBASICINFO/btnBLtoXY\",\r\n            beforeSend: function (req" +
"uest) {\r\n                request.setRequestHeader(\"Authorization\", authToken);\r\n" +
"            },\r\n            async: false,\r\n            data: { _lat: lat, _lon: " +
"lon, csStr: csStr, numberNameStr: numberNameStr },\r\n            type: \"GET\",\r\n  " +
"          success: function (res) {\r\n                var data = JSON.parse(res);" +
"\r\n                if (data.x != \"\") {\r\n                    $(\"#X\").val(data.x)\r\n" +
"                }\r\n                if (data.y != \"\") {\r\n                    $(\"#" +
"Y\").val(data.y)\r\n                }\r\n            },\r\n        });\r\n    }\r\n</script" +
">\r\n");

});

        }
    }
}
#pragma warning restore 1591
