#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Infoearth.Application.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/JXGeoManage/Views/TBL_QCQF_ADMINISTRATIVE/TBL_QCQF_ADMINISTRATIVESearch.c" +
        "shtml")]
    public partial class _Areas_JXGeoManage_Views_TBL_QCQF_ADMINISTRATIVE_TBL_QCQF_ADMINISTRATIVESearch_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_JXGeoManage_Views_TBL_QCQF_ADMINISTRATIVE_TBL_QCQF_ADMINISTRATIVESearch_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\JXGeoManage\Views\TBL_QCQF_ADMINISTRATIVE\TBL_QCQF_ADMINISTRATIVESearch.cshtml"
  
    ViewBag.Title = "列表页面";
    Layout = "~/Views/Shared/_Form.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n<script>\r\n    var authToken = getAuthorizationToken();\r\n    $(function () {\r\n  " +
"      InitialPage();\r\n        //查询条件\r\n        $(\"#queryCondition .dropdown-menu " +
"li\").click(function () {\r\n            var text = $(this).find(\'a\').html();\r\n    " +
"        var value = $(this).find(\'a\').attr(\'data-value\');\r\n            $(\"#query" +
"Condition .dropdown-text\").html(text).attr(\'data-value\', value)\r\n        });\r\n  " +
"      GetGrid();\r\n        //查询点击事件\r\n        $(\"#btn_Search\").click(function () {" +
"\r\n            SearchEvent();\r\n        });\r\n    });\r\n    //初始化页面\r\n    function In" +
"itialPage() {\r\n        //resize重设布局;\r\n        $(window).resize(function (e) {\r\n " +
"           window.setTimeout(function () {\r\n                $(\'#gridTable\').setG" +
"ridWidth(($(\'.gridPanel\').width()));\r\n                $(\'#gridTable\').setGridHei" +
"ght($(window).height() - 108.5);\r\n            }, 200);\r\n            e.stopPropag" +
"ation();\r\n        });\r\n    }\r\n    //加载表格\r\n    function GetGrid() {\r\n        var " +
"selectedRowIndex = 0;\r\n        var queryJson = $(\"#filter-form\").getWebControls(" +
");\r\n        var $gridTable = $(\'#gridTable\');\r\n        $gridTable.jqGrid({\r\n    " +
"        autowidth: true,\r\n            height: $(window).height() - 138.5,\r\n     " +
"       postData: { queryJson: JSON.stringify(queryJson) },\r\n            url: \".." +
"/../api/TBL_QCQF_ADMINISTRATIVEApi/GetPageListJsonnew\",\r\n            datatype: \"" +
"json\",\r\n            loadBeforeSend: function (a) {\r\n                a.setRequest" +
"Header(\"Authorization\", authToken);\r\n            },\r\n            colModel: [\r\n  " +
"              { label: \'GUID\', name: \'GUID\', index: \'GUID\', width: 100, align: \'" +
"left\', sortable: true, hidden: true },\r\n                { label: \'省\', name: \'PRO" +
"VINCENAME\', index: \'PROVINCENAME\', width: 50, align: \'left\', sortable: true },\r\n" +
"                { label: \'市\', name: \'CITYNAME\', index: \'CITYNAME\', width: 50, al" +
"ign: \'left\', sortable: true },\r\n                { label: \'县\', name: \'COUNTYNAME\'" +
", index: \'COUNTYNAME\', width: 50, align: \'left\', sortable: true },\r\n            " +
"    { label: \'乡镇\', name: \'TOWNNAME\', index: \'TOWNNAME\', width: 100, align: \'left" +
"\', sortable: true },\r\n                { label: \'联系人\', name: \'NAME\', index: \'NAME" +
"\', width: 150, align: \'left\', sortable: true },\r\n                { label: \'手机\', " +
"name: \'TELPHONE\', index: \'TELPHONE\', width: 200, align: \'left\', sortable: true }" +
",\r\n            ],\r\n            viewrecords: true,\r\n            rowNum: 30,\r\n    " +
"        rowList: [30, 50, 100],\r\n            pager: \"#gridPager\",\r\n            s" +
"ortname: \'GUID\',\r\n            sortorder: \'desc\',\r\n            rownumbers: true,\r" +
"\n            shrinkToFit: false,\r\n            gridview: true,\r\n            onSel" +
"ectRow: function (rowId, status) {\r\n                selectedRowIndex = $(\'#\' + t" +
"his.id).getGridParam(\'selrow\');\r\n                selectData = $gridTable.jqGrid(" +
"\"getRowData\", rowId);\r\n            },\r\n            gridComplete: function () {\r\n" +
"                $(\'#\' + this.id).setSelection(selectedRowIndex, false);\r\n       " +
"     }\r\n        });\r\n    }\r\n   \r\n\r\n    var selectData = {};\r\n\r\n    //保存表单;\r\n    " +
"function AcceptClick() {\r\n        learun.dialogClose();\r\n        return selectDa" +
"ta;\r\n    }\r\n\r\n    //查询表格函数\r\n    function SearchEvent() {\r\n        var condition " +
"= $(\"#queryCondition\").find(\'.dropdown-text\').attr(\'data-value\');\r\n        if (c" +
"ondition == undefined || condition == null || condition == \'\') {\r\n            co" +
"ndition = \'\';\r\n        }\r\n        //if (condition == \'\') {\r\n        //    learun" +
".dialogMsg({ msg: \'请选择需要查询关键字！\', type: 0 });\r\n        //}\r\n        var queryJson" +
" = $.extend($(\"#filter-form\").getWebControls(), { \"condition\": condition });\r\n  " +
"      $(\"#gridTable\").jqGrid(\'setGridParam\', {\r\n            postData: { queryJso" +
"n: JSON.stringify(queryJson) },\r\n            url: \"../../api/TBL_QCQF_ADMINISTRA" +
"TIVEApi/GetPageListJson\",\r\n            page: 1\r\n        }).trigger(\'reloadGrid\')" +
";\r\n    }\r\n</script>\r\n");

});

WriteLiteral("<div");

WriteLiteral(" class=\"titlePanel\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"title-search\"");

WriteLiteral(" id=\"filter-form\"");

WriteLiteral(">\r\n        <table>\r\n            <tr>\r\n\r\n                <td>\r\n                   " +
" <div");

WriteLiteral(" id=\"queryCondition\"");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" class=\"btn btn-default dropdown-text\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">选择条件</a>\r\n                        <a");

WriteLiteral(" class=\"btn btn-default dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-expanded=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></span></a>\r\n                        <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(">\r\n                            <li><a");

WriteLiteral(" data-value=\"UserName\"");

WriteLiteral(">名称</a></li>\r\n                            <li><a");

WriteLiteral(" data-value=\"Account\"");

WriteLiteral(">登陆名</a></li>\r\n                        </ul>\r\n                    </div>\r\n       " +
"         </td>\r\n                <td>\r\n                    <input");

WriteLiteral(" id=\"NAME\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"请输入责任人姓名！\"");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(" />\r\n                </td>\r\n                <td");

WriteLiteral(" style=\"padding-left: 5px;\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" id=\"btn_Search\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral("></i>查询</a>\r\n                </td>\r\n            </tr>\r\n        </table>\r\n    </di" +
"v>\r\n    <div");

WriteLiteral(" style=\"clear:both\"");

WriteLiteral("></div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"gridPanel\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" id=\"gridTable\"");

WriteLiteral("></table>\r\n    <div");

WriteLiteral(" id=\"gridPager\"");

WriteLiteral("></div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
