#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/SystemManage/Views/CodeRule/ItemForm.cshtml")]
    public partial class _Areas_SystemManage_Views_CodeRule_ItemForm_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_SystemManage_Views_CodeRule_ItemForm_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\SystemManage\Views\CodeRule\ItemForm.cshtml"
  
    ViewBag.Title = "规则设计项目表单";
    Layout = "~/Views/Shared/_Form.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n    var keyValue = learun.request(\'keyValue\');\r\n    $(function () {\r\n" +
"        $(\"#F_ItemType\").comboBox({}).bind(\"change\", function () {\r\n            " +
"var value = $(this).attr(\'data-value\');\r\n            var $formValue = $(\"#F_Form" +
"atStr\").parents(\'.formValue\');\r\n            $(\"#F_StepValue\").attr(\"readonly\", \"" +
"readonly\").attr(\'[isvalid=no]\');\r\n            $(\"#F_InitValue\").attr(\"readonly\"," +
" \"readonly\").attr(\'[isvalid=no]\');\r\n            switch (value) {\r\n              " +
"  case \"0\":\r\n                    $formValue.html(\'<input id=\"F_FormatStr\" type=\"" +
"text\" class=\"form-control\" isvalid=\"yes\" checkexpession=\"NotNull\" />\');\r\n       " +
"             break;\r\n                case \"1\":\r\n                    $formValue.h" +
"tml(\'<div id=\"F_FormatStr\" type=\"select\" class=\"ui-select\" isvalid=\"yes\" checkex" +
"pession=\"NotNull\"><ul>\'\r\n                        + \'<li data-value=\"mmdd\">mmdd</" +
"li>\'\r\n                        + \'<li data-value=\"ddmm\">ddmm</li>\'\r\n             " +
"           + \'<li data-value=\"mmyy\">mmyy</li>\'\r\n                        + \'<li d" +
"ata-value=\"yymm\">yymm</li>\'\r\n                        + \'<li data-value=\"yyyymm\">" +
"yyyymm</li>\'\r\n                        + \'<li data-value=\"yymmdd\">yymmdd</li>\'\r\n " +
"                       + \'<li data-value=\"yyyymmdd\">yyyymmdd</li>\'\r\n            " +
"            + \'</ul></div>\');\r\n                    $(\"#F_FormatStr\").comboBox({\r" +
"\n                        maxHeight: \"130px\",\r\n                    }).comboBoxSet" +
"Value(\'mmdd\');\r\n                    break;\r\n                case \"2\":\r\n         " +
"           $formValue.html(\'<div id=\"F_FormatStr\" type=\"select\" class=\"ui-select" +
"\" isvalid=\"yes\" checkexpession=\"NotNull\"><ul>\'\r\n                       + \'<li da" +
"ta-value=\"000\">000</li>\'\r\n                       + \'<li data-value=\"0000\">0000</" +
"li>\'\r\n                       + \'<li data-value=\"00000\">00000</li>\'\r\n            " +
"           + \'<li data-value=\"000000\">000000</li>\'\r\n                       + \'</" +
"ul></div>\');\r\n                    $(\"#F_FormatStr\").comboBox({\r\n                " +
"    }).comboBoxSetValue(\'000\');\r\n                    $(\"#F_StepValue\").removeAtt" +
"r(\"readonly\").attr(\'isvalid\', \'yes\');\r\n                    $(\"#F_InitValue\").rem" +
"oveAttr(\"readonly\").attr(\'isvalid\', \'yes\');\r\n                    break;\r\n       " +
"         case \"3\":\r\n                    $formValue.html(\'<div id=\"F_FormatStr\" t" +
"ype=\"select\" class=\"ui-select\" isvalid=\"yes\" checkexpession=\"NotNull\"><ul>\'\r\n   " +
"                    + \'<li data-value=\"code\">公司编号</li>\'\r\n                       " +
"+ \'<li data-value=\"name\">公司名称</li>\'\r\n                       + \'</ul></div>\');\r\n " +
"                   $(\"#F_FormatStr\").comboBox({\r\n                    }).comboBox" +
"SetValue(\'code\');\r\n                    break;\r\n                case \"4\":\r\n      " +
"              $formValue.html(\'<div id=\"F_FormatStr\" type=\"select\" class=\"ui-sel" +
"ect\" isvalid=\"yes\" checkexpession=\"NotNull\"><ul>\'\r\n                       + \'<li" +
" data-value=\"code\">部门编号</li>\'\r\n                       + \'<li data-value=\"name\">部" +
"门名称</li>\'\r\n                       + \'</ul></div>\');\r\n                    $(\"#F_F" +
"ormatStr\").comboBox({\r\n                    }).comboBoxSetValue(\'code\');\r\n       " +
"             break;\r\n                case \"5\":\r\n                    $formValue.h" +
"tml(\'<div id=\"F_FormatStr\" type=\"select\" class=\"ui-select\" isvalid=\"yes\" checkex" +
"pession=\"NotNull\"><ul>\'\r\n                       + \'<li data-value=\"code\">用户编号</l" +
"i>\'\r\n                       + \'<li data-value=\"name\">用户名称</li>\'\r\n               " +
"        + \'</ul></div>\');\r\n                    $(\"#F_FormatStr\").comboBox({\r\n   " +
"                 }).comboBoxSetValue(\'code\');\r\n                    break;\r\n     " +
"           default:\r\n                    break;\r\n            }\r\n        }).combo" +
"BoxSetValue(0);\r\n\r\n        //获取表单\r\n        if (!!keyValue) {\r\n            var ro" +
"wdata = getInfoTop().Form.$(\"#gridTable\").jqGridRow()[0];\r\n            $(\"#form1" +
"\").setWebControls(rowdata);\r\n            if (rowdata.ItemType == 2) {\r\n         " +
"       $(\"#F_StepValue\").removeAttr(\"readonly\").attr(\'isvalid\', \'yes\');\r\n       " +
"         $(\"#F_InitValue\").removeAttr(\"readonly\").attr(\'isvalid\', \'yes\');\r\n     " +
"       }\r\n        }\r\n    })\r\n\r\n    //保存表单\r\n    function AcceptClick() {\r\n       " +
" if (!$(\'#form1\').Validform()) {\r\n            return false;\r\n        }\r\n        " +
"var $gridTable = getInfoTop().Form.$(\"#gridTable\");\r\n        var postData = $(\"#" +
"form1\").getWebControls(\"\");\r\n        postData[\"F_ItemTypeName\"] = $(\"#F_ItemType" +
"\").attr(\'data-text\');\r\n        if (!!keyValue) {\r\n            $gridTable.setRowD" +
"ata(keyValue, postData);\r\n        } else {\r\n            $gridTable.addRowData(($" +
"gridTable.jqGrid(\"getRowData\").length + 1), postData);\r\n        }\r\n        learu" +
"n.dialogMsg({ msg: \"操作成功。\", type: 1 });\r\n        learun.dialogClose();\r\n    }\r\n<" +
"/script>\r\n<div");

WriteLiteral(" style=\"margin-top: 20px; margin-right: 30px;\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">前缀<font");

WriteLiteral(" face=\"宋体\"");

WriteLiteral(">*</font></th>\r\n            <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"F_ItemType\"");

WriteLiteral(" type=\"select\"");

WriteLiteral(" class=\"ui-select\"");

WriteLiteral(" isvalid=\"yes\"");

WriteLiteral(" checkexpession=\"NotNull\"");

WriteLiteral(">\r\n                    <ul>\r\n                        <li");

WriteLiteral(" data-value=\"0\"");

WriteLiteral(">自定义</li>\r\n                        <li");

WriteLiteral(" data-value=\"1\"");

WriteLiteral(">日期</li>\r\n                        <li");

WriteLiteral(" data-value=\"2\"");

WriteLiteral(">流水号</li>\r\n                        <li");

WriteLiteral(" data-value=\"3\"");

WriteLiteral(">公司</li>\r\n                        <li");

WriteLiteral(" data-value=\"4\"");

WriteLiteral(">部门</li>\r\n                        <li");

WriteLiteral(" data-value=\"5\"");

WriteLiteral(">用户</li>\r\n                    </ul>\r\n                </div>\r\n            </td>\r\n " +
"       </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">格式<font");

WriteLiteral(" face=\"宋体\"");

WriteLiteral(">*</font></th>\r\n            <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"F_FormatStr\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" isvalid=\"yes\"");

WriteLiteral(" checkexpession=\"NotNull\"");

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">步长</th>\r\n            <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"F_StepValue\"");

WriteLiteral(" readonly");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" isvalid=\"no\"");

WriteLiteral(" checkexpession=\"NotNull\"");

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">初始</th>\r\n            <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"F_InitValue\"");

WriteLiteral(" readonly");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" isvalid=\"no\"");

WriteLiteral(" checkexpession=\"NotNull\"");

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">说明\r\n            </th>\r\n            <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"F_Description\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n    </table>\r\n</div>\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
