#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Dept/DeptForm.cshtml")]
    public partial class _Views_Dept_DeptForm_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Dept_DeptForm_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Dept\DeptForm.cshtml"
  
    ViewBag.Title = "列表页面";
    Layout = "~/Views/Shared/_Index.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n    $(function () {\r\n        InitialPage();\r\n        GetGrid();\r\n    " +
"    //查询点击事件\r\n        $(\"#btn_Search\").click(function () {\r\n            SearchEv" +
"ent();\r\n        });\r\n    });\r\n    //初始化页面\r\n    function InitialPage() {\r\n       " +
" //resize重设布局;\r\n        $(window).resize(function (e) {\r\n            window.setT" +
"imeout(function () {\r\n                $(\'#gridTable\').setGridWidth(($(\'.gridPane" +
"l\').width()));\r\n                $(\'#gridTable\').setGridHeight($(window).height()" +
" - 108.5);\r\n            }, 200);\r\n            e.stopPropagation();\r\n        });\r" +
"\n    }\r\n    //加载表格\r\n    function GetGrid() {\r\n        var selectedRowIndex = 0;\r" +
"\n        var queryJson = $(\"#filter-form\").getWebControls();\r\n        var $gridT" +
"able = $(\'#gridTable\');\r\n        $gridTable.jqGrid({\r\n            autowidth: tru" +
"e,\r\n            height: $(window).height() - 138.5,\r\n            url: \"../../Dep" +
"t/GetAllDept\",\r\n            datatype: \"json\",\r\n            postData: { queryJson" +
": JSON.stringify(queryJson) },\r\n            colModel: [\r\n                { label" +
": \'DeptNo\', name: \'DeptNo\', index: \'DeptNo\', width: 100, align: \'left\', sortable" +
": true, hidden: true },\r\n                { label: \'部门名称\', name: \'DeptName\', inde" +
"x: \'DeptName\', width: 100, align: \'left\', sortable: true },\r\n                 { " +
"label: \'部门电话\', name: \'DeptPhone\', index: \'DeptPhone\', width: 100, align: \'left\'," +
" sortable: true },\r\n                { label: \'部门邮箱\', name: \'DeptEmail\', index: \'" +
"DeptEmail\', width: 100, align: \'left\', sortable: true },             \r\n         " +
"       { label: \'部门地址\', name: \'Address\', index: \'Address\', width: 100, align: \'l" +
"eft\', sortable: true }        \r\n            ],\r\n            viewrecords: true,\r\n" +
"            rowNum: 30,\r\n            rowList: [30, 50, 100],\r\n            pager:" +
" \"#gridPager\",\r\n            sortname: \'DeptNo\',\r\n            sortorder: \'desc\',\r" +
"\n            rownumbers: true,\r\n            shrinkToFit: false,\r\n            gri" +
"dview: true,\r\n            onSelectRow: function (rowId, status) {\r\n             " +
"   selectedRowIndex = $(\'#\' + this.id).getGridParam(\'selrow\');\r\n                " +
"selectData = $gridTable.jqGrid(\"getRowData\", rowId);\r\n            },\r\n          " +
"  gridComplete: function () {\r\n                $(\'#\' + this.id).setSelection(sel" +
"ectedRowIndex, false);\r\n            }\r\n        });\r\n    }\r\n\r\n    var selectData " +
"= {};\r\n\r\n    //保存表单;\r\n    function AcceptClick() {\r\n        learun.dialogClose()" +
";\r\n        return selectData;\r\n    }\r\n\r\n    //查询表格函数\r\n    function SearchEvent()" +
" {\r\n        var queryJson = $(\"#filter-form\").getWebControls();\r\n        $(\"#gri" +
"dTable\").jqGrid(\'setGridParam\', {\r\n            postData: { queryJson: JSON.strin" +
"gify(queryJson) },\r\n            url: \"../../Dept/GetAllDept\",\r\n            page:" +
" 1\r\n        }).trigger(\'reloadGrid\');\r\n    }\r\n</script>\r\n<div");

WriteLiteral(" class=\"titlePanel\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"title-search\"");

WriteLiteral(" id=\"filter-form\"");

WriteLiteral(">\r\n        <table>\r\n            <tr>\r\n                <td>\r\n                    <" +
"input");

WriteLiteral(" id=\"DeptName\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"请输入要查询部门\"");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(" />\r\n                </td>\r\n                <td");

WriteLiteral(" style=\"padding-left: 5px;\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" id=\"btn_Search\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral("></i>查询</a>\r\n                </td>\r\n            </tr>\r\n        </table>\r\n    </di" +
"v>\r\n    <div");

WriteLiteral(" style=\"clear:both\"");

WriteLiteral("></div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"gridPanel\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" id=\"gridTable\"");

WriteLiteral("></table>\r\n    <div");

WriteLiteral(" id=\"gridPager\"");

WriteLiteral("></div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
