#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Infoearth.Application.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/JXGeoManage/Views/TBL_RWJJ_GOVERNMENT/TBL_RWJJQueryBrowse.cshtml")]
    public partial class _Areas_JXGeoManage_Views_TBL_RWJJ_GOVERNMENT_TBL_RWJJQueryBrowse_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_JXGeoManage_Views_TBL_RWJJ_GOVERNMENT_TBL_RWJJQueryBrowse_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\JXGeoManage\Views\TBL_RWJJ_GOVERNMENT\TBL_RWJJQueryBrowse.cshtml"
  
    ViewBag.Title = "列表页面";
    Layout = "~/Views/Shared/_IndexMap.cshtml";

            
            #line default
            #line hidden
WriteLiteral(@"
<style>
    .ui-layout-resizer {
        background: #f5f5f5 !important;
    }

    .ui-jqgrid-view td {
        border-right: 1px solid #ccc !important;
    }

    .ui-jqgrid-view tr:nth-child(odd) {
        background: #DCDCDC;
    }

    .fa-folder-open {
        color: transparent !important;
        background: url(""../../Content/images/zTreeStandard.png"") no-repeat;
        background-position: -110px -16px;
        margin-right: 2px;
        width: 16px !important;
        height: 16px !important;
    }

    .fa-folder {
        color: transparent !important;
        background: url(""../../Content/images/zTreeStandard.png"") no-repeat;
        background-position: -110px 0;
        margin-right: 2px;
        width: 16px !important;
        height: 16px !important;
    }

    .fa-file-o {
        color: transparent !important;
        background: url(""../../Content/images/zTreeStandard.png"") no-repeat;
        background-position: -110px -32px;
        width: 16px !important;
        height: 16px !important;
    }
</style>
<div");

WriteLiteral(" class=\"ui-layout\"");

WriteLiteral(" id=\"layout\"");

WriteLiteral(" style=\"height: 100%; width: 100%;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui-layout-west\"");

WriteLiteral(" style=\"height:100%\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"west-Panel\"");

WriteLiteral(" style=\"margin:0px;height:100%\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel-Title\"");

WriteLiteral(" style=\"height:40px;line-height:40px;background-color: rgba(236, 247, 255, 1);col" +
"or:#000\"");

WriteLiteral(">行政区划</div>\r\n            <div");

WriteLiteral(" id=\"itemTree\"");

WriteLiteral("></div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"ui-layout-center\"");

WriteLiteral(" id=\"ui_center\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"center-Panel\"");

WriteLiteral(" style=\"height: 100%;width:100%;margin-top:0px;overflow-y:hidden;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"DZHJManage\"");

WriteLiteral(" style=\"width:100%;height:45px;background:#fff\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(" style=\"background:rgba(236, 247, 255, 1)\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(" id=\"li_GOV\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#GOV\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">政府</a></li>\r\n                    <li");

WriteLiteral(" id=\"li_ENTER\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#ENTER\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">企业</a></li>\r\n                    <li");

WriteLiteral(" id=\"li_HOSPITAL\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#HOSPITAL\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">医院</a></li>\r\n                    <li");

WriteLiteral(" id=\"li_SCHOOL\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#SCHOOL\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">学校</a></li>\r\n                    <li");

WriteLiteral(" id=\"li_RESIDENT\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#RESIDENT\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">居民住宅</a></li>\r\n                </ul>\r\n                <div");

WriteLiteral(" id=\"myTabContent\"");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(" style=\"height: 100%; width: 100%;\"");

WriteLiteral("></div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"ui-layout\"");

WriteLiteral(" id=\"layout2\"");

WriteLiteral(" style=\"height: 100%; width: 100%;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui-layout-north\"");

WriteLiteral(" id=\"ui_map\"");

WriteLiteral(" style=\"height: 350px;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"mapControl\"");

WriteLiteral(" style=\"height:350px;\"");

WriteLiteral("></div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"ui-layout-center\"");

WriteLiteral(" id=\"ui_grid\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"titlePanel\"");

WriteLiteral(" style=\"height:40px;line-height:40px\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"title-search\"");

WriteLiteral(" id=\"filter-form\"");

WriteLiteral(" style=\"height:40px;line-height:40px\"");

WriteLiteral(">\r\n                            <table>\r\n                                <tr>\r\n   " +
"                                 <td>\r\n                                        <" +
"input");

WriteLiteral(" id=\"NAME\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"请输入名称\"");

WriteLiteral(" style=\"width: 160px;\"");

WriteLiteral(" />\r\n                                    </td>\r\n                                 " +
"   <td");

WriteLiteral(" style=\"padding-left: 5px;\"");

WriteLiteral(">\r\n                                        <a");

WriteLiteral(" id=\"btn_Search\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral("></i>查询</a>\r\n                                    </td>\r\n                         " +
"       </tr>\r\n                            </table>\r\n                        </di" +
"v>\r\n                        <div");

WriteLiteral(" class=\"\"");

WriteLiteral(" style=\"float:right;margin-right:10px;height:40px;line-height:40px;display:flex;a" +
"lign-items: center;\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" id=\"lr-replace\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" onclick=\"reload()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-refresh\"");

WriteLiteral("></i>刷新</a>\r\n                                <a");

WriteLiteral(" id=\"lr-message\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" onclick=\"btn_message()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-pencil-square-o\"");

WriteLiteral("></i>详情</a>\r\n                                <a");

WriteLiteral(" id=\"lr-colgrid\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" onclick=\"ColDataGrid()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-down\"");

WriteLiteral("></i>列表</a>\r\n                                <a");

WriteLiteral(" id=\"lr-colmap\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" onclick=\"ColMapDiv()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-up\"");

WriteLiteral("></i>地图</a>\r\n                            </div>\r\n                        </div>\r\n" +
"                    </div>\r\n\r\n                    <div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"tab-pane fade in active\"");

WriteLiteral(" id=\"GOV\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"gridPanel\"");

WriteLiteral(" id=\"gridPanel1\"");

WriteLiteral(">\r\n                                <table");

WriteLiteral(" id=\"gridTable1\"");

WriteLiteral("></table>\r\n                                <div");

WriteLiteral(" id=\"gridPager1\"");

WriteLiteral("></div>\r\n                            </div>\r\n                        </div>\r\n    " +
"                    <div");

WriteLiteral(" class=\"tab-pane fade\"");

WriteLiteral(" id=\"ENTER\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"gridPanel\"");

WriteLiteral(" id=\"gridPanel2\"");

WriteLiteral(">\r\n                                <table");

WriteLiteral(" id=\"gridTable2\"");

WriteLiteral("></table>\r\n                                <div");

WriteLiteral(" id=\"gridPager2\"");

WriteLiteral("></div>\r\n                            </div>\r\n                        </div>\r\n    " +
"                    <div");

WriteLiteral(" class=\"tab-pane fade\"");

WriteLiteral(" id=\"HOSPITAL\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"gridPanel\"");

WriteLiteral(" id=\"gridPanel3\"");

WriteLiteral(">\r\n                                <table");

WriteLiteral(" id=\"gridTable3\"");

WriteLiteral("></table>\r\n                                <div");

WriteLiteral(" id=\"gridPager3\"");

WriteLiteral("></div>\r\n                            </div>\r\n                        </div>\r\n    " +
"                    <div");

WriteLiteral(" class=\"tab-pane fade\"");

WriteLiteral(" id=\"SCHOOL\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"gridPanel\"");

WriteLiteral(" id=\"gridPanel4\"");

WriteLiteral(">\r\n                                <table");

WriteLiteral(" id=\"gridTable4\"");

WriteLiteral("></table>\r\n                                <div");

WriteLiteral(" id=\"gridPager4\"");

WriteLiteral("></div>\r\n                            </div>\r\n                        </div>\r\n    " +
"                    <div");

WriteLiteral(" class=\"tab-pane fade\"");

WriteLiteral(" id=\"RESIDENT\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"gridPanel\"");

WriteLiteral(" id=\"gridPanel5\"");

WriteLiteral(">\r\n                                <table");

WriteLiteral(" id=\"gridTable5\"");

WriteLiteral("></table>\r\n                                <div");

WriteLiteral(" id=\"gridPager5\"");

WriteLiteral("></div>\r\n                            </div>\r\n                        </div>\r\n    " +
"                </div>\r\n                </div>\r\n            </div>\r\n        </di" +
"v>\r\n    </div>\r\n</div>\r\n\r\n\r\n\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n<script>\r\n    var layout2NorthH = 1;\r\n    var tabvalue = \"政府\";\r\n    var gridId " +
"= \"gridTable1\";\r\n    var authToken = getAuthorizationToken();\r\n    var dialog = " +
"request(\'dialog\');\r\n    var AreaCode = \"340000\", PROVINCE = \"\", CITY = \"\", COUNT" +
"Y = \"\";\r\n    var LATITUDE, LONGITUDE;\r\n    var linkUrl = \'/JXGeoManage/TBL_RWJJ_" +
"GOVERNMENT/TBL_RWJJ_GOVERNMENTForm\';\r\n    var delUrl = \'../../JXGeoManage/TBL_RW" +
"JJ_GOVERNMENT/RemoveForm\';\r\n    var queryUrl = \"../../JXGeoManage/TBL_RWJJ_GOVER" +
"NMENT/GetPageListJson\";\r\n    $(function () {\r\n        InitialPage();\r\n        Ge" +
"tMapData();\r\n        GetTree();\r\n        GetGovGrid();\r\n        BindMapMarkerGov" +
"();\r\n        //查询点击事件\r\n        $(\"#btn_Search\").click(function () {\r\n           " +
" SearchEvent();\r\n        });\r\n        $(\".nav-tabs li a\").click(function () {\r\n " +
"           tabvalue = this.innerHTML;\r\n            GetUrl(tabvalue);\r\n          " +
"  var queryJson = $(\"#filter-form\").getWebControls();\r\n            queryJson[\"DI" +
"SASTERTYPE\"] = tabvalue;\r\n            queryJson[\"PROVINCE\"] = PROVINCE;\r\n       " +
"     queryJson[\"CITY\"] = CITY;\r\n            queryJson[\"COUNTY\"] = COUNTY;\r\n     " +
"   })\r\n    });\r\n    //获取地址\r\n    function GetUrl(v) {\r\n        switch (v) {\r\n    " +
"        case \"政府\":\r\n                queryUrl = \"../../JXGeoManage/TBL_RWJJ_GOVER" +
"NMENT/GetPageListJson\";\r\n                linkUrl = \'/JXGeoManage/TBL_RWJJ_GOVERN" +
"MENT/TBL_RWJJ_GOVERNMENTForm\';\r\n                delUrl = \'../../JXGeoManage/TBL_" +
"RWJJ_GOVERNMENT/RemoveForm\';\r\n                GetGovGrid();\r\n                Bin" +
"dMapMarkerGov();\r\n                gridId = \"gridTable1\";\r\n                break;" +
"\r\n            case \"企业\":\r\n                queryUrl = \"../../JXGeoManage/TBL_RWJJ" +
"_ENTERPRISE/GetPageListJson\";\r\n                linkUrl = \'/JXGeoManage/TBL_RWJJ_" +
"ENTERPRISE/TBL_RWJJ_ENTERPRISEForm\';\r\n                delUrl = \'../../JXGeoManag" +
"e/TBL_RWJJ_ENTERPRISE/RemoveForm\';\r\n                GetEnterGrid();\r\n           " +
"     BindMapMarkerEnter();\r\n                gridId = \"gridTable2\";\r\n            " +
"    break;\r\n            case \"医院\":\r\n                queryUrl = \"../../JXGeoManag" +
"e/TBL_RWJJ_HOSPITAL/GetPageListJson\";\r\n                linkUrl = \'/JXGeoManage/T" +
"BL_RWJJ_HOSPITAL/TBL_RWJJ_HOSPITALForm\';\r\n                delUrl = \'../../JXGeoM" +
"anage/TBL_RWJJ_HOSPITAL/RemoveForm\';\r\n                GetHospitalGrid();\r\n      " +
"          BindMapMarkerHospital();\r\n                gridId = \"gridTable3\";\r\n    " +
"            break;\r\n            case \"学校\":\r\n                queryUrl = \"../../JX" +
"GeoManage/TBL_RWJJ_SCHOOL/GetPageListJson\";\r\n                linkUrl = \'/JXGeoMa" +
"nage/TBL_RWJJ_SCHOOL/TBL_RWJJ_SCHOOLForm\';\r\n                delUrl = \'../../JXGe" +
"oManage/TBL_RWJJ_SCHOOL/RemoveForm\';\r\n                GetSchoolGrid();\r\n        " +
"        BindMapMarkerSchool();\r\n                gridId = \"gridTable4\";\r\n        " +
"        break;\r\n            case \"居民住宅\":\r\n                queryUrl = \"../../JXGe" +
"oManage/TBL_RWJJ_RESIDENTIALAREA/GetPageListJson\";\r\n                linkUrl = \'/" +
"JXGeoManage/TBL_RWJJ_RESIDENTIALAREA/TBL_RWJJ_RESIDENTIALAREAForm\';\r\n           " +
"     delUrl = \'../../JXGeoManage/TBL_RWJJ_RESIDENTIALAREA/RemoveForm\';\r\n        " +
"        GetResidentGrid();\r\n                BindMapMarkerResident();\r\n          " +
"      gridId = \"gridTable5\";\r\n                break;\r\n            default:\r\n    " +
"            break;\r\n        }\r\n    }\r\n    //初始化页面\r\n    function InitialPage() {\r" +
"\n        //layout布局\r\n        $(\'#layout\').layout({\r\n            west__size: 190," +
"\r\n            applyDemoStyles: true,\r\n            onresize: function () {\r\n     " +
"           if (isResize < 10) {\r\n                    isResize++;\r\n              " +
"  }\r\n                resize();\r\n            }\r\n        });\r\n        var isResize" +
" = 0;\r\n        var count = 0;\r\n        var resized = 0;\r\n        var layout = $(" +
"\'#layout2\').layout({\r\n            applyDemoStyles: true,\r\n            onresize: " +
"function () {\r\n                resize();\r\n                if (isResize > 1) {\r\n " +
"                   resized = 1;\r\n                } else {\r\n                    i" +
"f (count == 1 || resized == 0) {\r\n                        $(\'#layout2 .ui-layout" +
"-center\').height($(\'#layout2 .ui-layout-center\').height() - 18);\r\n              " +
"      }\r\n                }\r\n                count++;\r\n            }\r\n        });" +
"\r\n\r\n        //layout.sizePane(\"\")\r\n        //resize重设布局;\r\n        $(window).resi" +
"ze(function (e) {\r\n            if (isResize < 10) {\r\n                isResize++;" +
"\r\n            }\r\n            resize();\r\n            e.stopPropagation();\r\n      " +
"  });\r\n        function resize() {\r\n            window.setTimeout(function () {\r" +
"\n                if (mapCtlExt != null) {\r\n                    mapCtlExt.setHeig" +
"ht($(\'#mapControl\').parent().height() - 4);\r\n                }\r\n                " +
"$(\'#layout2 .ui-layout-center\').width($(\'#layout2 .ui-layout-center\').parent().w" +
"idth());\r\n                $(\'.ui-jqgrid-bdiv\').height($(\'#layout2 .ui-layout-cen" +
"ter\').height() - 60 - 60);\r\n                $(\'#layout2 .ui-layout-center\').heig" +
"ht($(\'#layout2\').height() - $(\'#layout2 .ui-layout-north\').height() - 15);\r\n    " +
"            $(\'#gridTable1\').setGridWidth(($(\'.tab-content\').width()));\r\n       " +
"         $(\'#gridTable1\').setGridHeight($(\'#layout2 .ui-layout-center\').height()" +
" - 145 + 12);\r\n                $(\'#gridTable2\').setGridWidth(($(\'.tab-content\')." +
"width()));\r\n                $(\'#gridTable2\').setGridHeight($(\'#layout2 .ui-layou" +
"t-center\').height() - 145 + 12);\r\n                $(\'#gridTable3\').setGridWidth(" +
"($(\'.tab-content\').width()));\r\n                $(\'#gridTable3\').setGridHeight($(" +
"\'#layout2 .ui-layout-center\').height() - 145 + 12);\r\n                $(\'#gridTab" +
"le4\').setGridWidth(($(\'.tab-content\').width()));\r\n                $(\'#gridTable4" +
"\').setGridHeight($(\'#layout2 .ui-layout-center\').height() - 145 + 12);\r\n        " +
"        $(\'#gridTable5\').setGridWidth(($(\'.tab-content\').width()));\r\n           " +
"     $(\'#gridTable5\').setGridHeight($(\'#layout2 .ui-layout-center\').height() - 1" +
"45 + 12);\r\n                $(\'#layout2 .ui-layout-center\').css(\'overflow\', \'hidd" +
"en\');\r\n            }, 200);\r\n        };\r\n        $(window).resize();\r\n        $(" +
"\'#layout2 .ui-layout-center\').height($(\'#layout2 .ui-layout-center\').height() - " +
"18);\r\n        layout2NorthH = $(\"#layout2 .ui-layout-north\").height();\r\n    }\r\n " +
"   //加载行政区划树\r\n    function GetTree() {\r\n        var item = {\r\n            height" +
": $(window).height() - 52,\r\n            isAllExpand: false,\r\n            url: \"." +
"./../Map/GetTreeJsonForMap\",\r\n            onnodeclick: function (item) {\r\n      " +
"          AreaCode = item.id;\r\n                var level = item.value.split(\',\')" +
"[1];\r\n                if (level == 1) {\r\n                    PROVINCE = item.id;" +
"\r\n                    CITY = \"\";\r\n                    COUNTY = \"\";\r\n            " +
"    } else if (level == 2) {\r\n                    PROVINCE = item.id.substring(0" +
", 2) + \"0000\";\r\n                    CITY = item.id;\r\n                    COUNTY " +
"= \"\";\r\n                } else if (level == 3) {\r\n                    PROVINCE = " +
"item.id.substring(0, 2) + \"0000\";\r\n                    CITY = item.id.substring(" +
"0, 4) + \"00\";\r\n                    COUNTY = item.id;\r\n                }\r\n       " +
"         var data = [{\r\n                    latitude: item.value.split(\',\')[3],\r" +
"\n                    longitude: item.value.split(\',\')[2],\r\n                    p" +
"opupHtml: \"\"\r\n                }]\r\n                mapCtlExt.addLocation(data, fa" +
"lse, level);\r\n                $(\'#btn_Search\').trigger(\"click\");\r\n            }," +
"\r\n        };\r\n        //初始化\r\n        $(\"#itemTree\").treeview(item);\r\n    };\r\n   " +
" //加载地图\r\n    var mapCtlExt = null;\r\n    function GetMapData() {\r\n        mapCtlE" +
"xt = $(\"#mapControl\").mapCtl(\r\n            cfGetMapData({\r\n            })\n      " +
"  );\r\n    };\r\n    //加载政府表格\r\n    function GetGovGrid() {\r\n        var selectedRow" +
"Index = 0;\r\n        var queryJson = $(\"#filter-form\").getWebControls();\r\n       " +
" queryJson[\"DISASTERTYPE\"] = tabvalue;\r\n        queryJson[\"PROVINCE\"] = PROVINCE" +
";\r\n        queryJson[\"CITY\"] = CITY;\r\n        queryJson[\"COUNTY\"] = COUNTY;\r\n   " +
"     var $gridTable = $(\'#gridTable1\');\r\n        $gridTable.jqGrid({\r\n          " +
"  autowidth: true,\r\n            postData: { queryJson: JSON.stringify(queryJson)" +
" },\r\n            height: $(\'#layout2 .ui-layout-center\').height() - 145 + 12,\r\n " +
"           url: queryUrl,\r\n            datatype: \"json\",\r\n            loadBefore" +
"Send: function (a) {\r\n                a.setRequestHeader(\"Authorization\", authTo" +
"ken);\r\n            },\r\n            colModel: [\r\n                { label: \'ID\', n" +
"ame: \'UNIFIEDCODE\', index: \'UNIFIEDCODE\', width: 300, align: \'left\', sortable: f" +
"alse, hidden: true },\r\n                { label: \'单位名称\', name: \'NAME\', index: \'NA" +
"ME\', width: 180, align: \'left\', sortable: false },\r\n                { label: \'身份" +
"证号\', name: \'CARDID\', index: \'CARDID\', width: 140, align: \'left\', sortable: false" +
", hidden: true },\r\n                { label: \'经度\', name: \'LONGITUDE\', index: \'LON" +
"GITUDE\', width: 100, align: \'left\', sortable: true, hidden: true },\r\n           " +
"     { label: \'纬度\', name: \'LATITUDE\', index: \'LATITUDE\', width: 100, align: \'lef" +
"t\', sortable: true, hidden: true },\r\n                { label: \'区县\', name: \'CITY\'" +
", index: \'CITY\', width: 140, align: \'left\', sortable: false },\r\n                " +
"{ label: \'乡镇\', name: \'TOWN\', index: \'TOWN\', width: 140, align: \'left\', sortable:" +
" false },\r\n                { label: \'村组\', name: \'VILLAGE\', index: \'VILLAGE\', wid" +
"th: 140, align: \'left\', sortable: false },\r\n                { label: \'电话\', name:" +
" \'PHONE\', index: \'PHONE\', width: 140, align: \'left\', sortable: false, hidden: tr" +
"ue },\r\n                { label: \'手机\', name: \'MOBILE\', index: \'MOBILE\', width: 14" +
"0, align: \'left\', sortable: false, hidden: true },\r\n                { label: \'联系" +
"人\', name: \'CONTACTPERSON\', index: \'CONTACTPERSON\', width: 140, align: \'left\', so" +
"rtable: false },\r\n                { label: \'机构级别\', name: \'ORGANIZATIONLEVEL\', in" +
"dex: \'ORGANIZATIONLEVEL\', width: 140, align: \'left\', sortable: false },\r\n       " +
"         { label: \'政府ID\', name: \'NAMEID\', index: \'NAMEID\', width: 100, align: \'l" +
"eft\', sortable: false, hidden: true },\r\n                { label: \'联系人编号\', name: " +
"\'CONTACTPERSONID\', index: \'CONTACTPERSONID\', width: 100, align: \'left\', sortable" +
": false, hidden: true },\r\n            ],\r\n            viewrecords: true,\r\n      " +
"      rowNum: 30,\r\n            rowList: [30, 50, 100],\r\n            pager: \"#gri" +
"dPager1\",\r\n            sortname: \'UNIFIEDCODE\',\r\n            sortorder: \'desc\',\r" +
"\n            rownumbers: true,\r\n            shrinkToFit: true,\r\n            grid" +
"view: true,\r\n            onSelectRow: function (rowId, status) {\r\n              " +
"  selectedRowIndex = $(\'#\' + this.id).getGridParam(\'selrow\');\r\n                v" +
"ar dt = $gridTable.jqGrid(\"getRowData\", rowId);\r\n                var data = [];\r" +
"\n                var longitude = 0, latitude = 0;\r\n                if (dt.LONGIT" +
"UDE) {\r\n                    longitude = parseFloat(DFMZH(dt.LONGITUDE));\r\n      " +
"          }\r\n                if (dt.LATITUDE) {\r\n                    latitude = " +
"parseFloat(DFMZH(dt.LATITUDE));\r\n                }\r\n                data.push({ " +
"longitude: longitude, latitude: latitude });\r\n                mapCtlExt.addLocat" +
"ion(data,true);\r\n            },\r\n            gridComplete: function () {\r\n      " +
"          $(\'#\' + this.id).setSelection(selectedRowIndex, false);\r\n            }" +
"\r\n        });\r\n    }\r\n    //加载企业表格\r\n    function GetEnterGrid() {\r\n        var s" +
"electedRowIndex = 0;\r\n        var queryJson = $(\"#filter-form\").getWebControls()" +
";\r\n        queryJson[\"DISASTERTYPE\"] = tabvalue;\r\n        queryJson[\"PROVINCE\"] " +
"= PROVINCE;\r\n        queryJson[\"CITY\"] = CITY;\r\n        queryJson[\"COUNTY\"] = CO" +
"UNTY;\r\n        var $gridTable = $(\'#gridTable2\');\r\n        $gridTable.jqGrid({\r\n" +
"            autowidth: true,\r\n            postData: { queryJson: JSON.stringify(" +
"queryJson) },\r\n            height: $(\'#layout2 .ui-layout-center\').height() - 14" +
"5 + 12,\r\n            url: queryUrl,\r\n            datatype: \"json\",\r\n            " +
"loadBeforeSend: function (a) {\r\n                a.setRequestHeader(\"Authorizatio" +
"n\", authToken);\r\n            },\r\n            colModel: [\r\n                { labe" +
"l: \'ID\', name: \'UNIFIEDCODE\', index: \'UNIFIEDCODE\', width: 300, align: \'left\', s" +
"ortable: false, hidden: true },\r\n                { label: \'企业名称\', name: \'NAME\', " +
"index: \'NAME\', width: 300, align: \'left\', sortable: false },\r\n                { " +
"label: \'身份证号\', name: \'CARDID\', index: \'CARDID\', width: 140, align: \'left\', sorta" +
"ble: false, hidden: true },\r\n                { label: \'经度\', name: \'LONGITUDE\', i" +
"ndex: \'LONGITUDE\', width: 100, align: \'left\', sortable: true, hidden: true },\r\n " +
"               { label: \'纬度\', name: \'LATITUDE\', index: \'LATITUDE\', width: 100, a" +
"lign: \'left\', sortable: true, hidden: true },\r\n                { label: \'区县\', na" +
"me: \'CITY\', index: \'CITY\', width: 120, align: \'left\', sortable: false },\r\n      " +
"          { label: \'乡镇\', name: \'TOWN\', index: \'TOWN\', width: 120, align: \'left\'," +
" sortable: false },\r\n                { label: \'村组\', name: \'VILLAGE\', index: \'VIL" +
"LAGE\', width: 120, align: \'left\', sortable: false },\r\n                { label: \'" +
"修建时间\', name: \'CREATETIME\', index: \'CREATETIME\', width: 120, align: \'left\', sorta" +
"ble: false, hidden: true },\r\n                { label: \'建筑面积\', name: \'AREASTRUCTU" +
"RE\', index: \'AREASTRUCTURE\', width: 100, align: \'left\', sortable: false },\r\n    " +
"            { label: \'结构类型\', name: \'STRUCTURETYPE\', index: \'STRUCTURETYPE\', widt" +
"h: 100, align: \'left\', sortable: false, hidden: true },\r\n                { label" +
": \'电话\', name: \'PHONE\', index: \'PHONE\', width: 100, align: \'left\', sortable: fals" +
"e, hidden: true },\r\n                { label: \'手机\', name: \'MOBILE\', index: \'MOBIL" +
"E\', width: 100, align: \'left\', sortable: false, hidden: true },\r\n               " +
" { label: \'职工总数\', name: \'WORKFORCE\', index: \'WORKFORCE\', width: 100, align: \'lef" +
"t\', sortable: false },\r\n                { label: \'日人流量\', name: \'VISITORSRATE\', i" +
"ndex: \'VISITORSRATE\', width: 100, align: \'left\', sortable: false, hidden: true }" +
",\r\n                { label: \'总资产\', name: \'TOTALASSETS\', index: \'TOTALASSETS\', wi" +
"dth: 100, align: \'left\', sortable: false },\r\n                { label: \'建筑层数\', na" +
"me: \'STOREYNUMBER\', index: \'STOREYNUMBER\', width: 100, align: \'left\', sortable: " +
"false, hidden: true },\r\n                { label: \'法人\', name: \'LEGALPERSON\', inde" +
"x: \'LEGALPERSON\', width: 120, align: \'left\', sortable: false },\r\n               " +
" { label: \'企业ID\', name: \'NAMEID\', index: \'NAMEID\', width: 100, align: \'left\', so" +
"rtable: false, hidden: true },\r\n                { label: \'法人ID\', name: \'LEGALPER" +
"SONID\', index: \'LEGALPERSONID\', width: 100, align: \'left\', sortable: false, hidd" +
"en: true },\r\n            ],\r\n            viewrecords: true,\r\n            rowNum:" +
" 30,\r\n            rowList: [30, 50, 100],\r\n            pager: \"#gridPager2\",\r\n  " +
"          sortname: \'UNIFIEDCODE\',\r\n            sortorder: \'desc\',\r\n            " +
"rownumbers: true,\r\n            shrinkToFit: true,\r\n            gridview: true,\r\n" +
"            onSelectRow: function (rowId, status) {\r\n                selectedRow" +
"Index = $(\'#\' + this.id).getGridParam(\'selrow\');\r\n                var dt = $grid" +
"Table.jqGrid(\"getRowData\", rowId);\r\n                var data = [];\r\n            " +
"    var longitude = 0, latitude = 0;\r\n                if (dt.LONGITUDE) {\r\n     " +
"               longitude = parseFloat(DFMZH(dt.LONGITUDE));\r\n                }\r\n" +
"                if (dt.LATITUDE) {\r\n                    latitude = parseFloat(DF" +
"MZH(dt.LATITUDE));\r\n                }\r\n                data.push({ longitude: lo" +
"ngitude, latitude: latitude });\r\n                mapCtlExt.addLocation(data,true" +
");\r\n            },\r\n            gridComplete: function () {\r\n                $(\'" +
"#\' + this.id).setSelection(selectedRowIndex, false);\r\n            }\r\n        });" +
"\r\n    }\r\n    //加载医院表格\r\n    function GetHospitalGrid() {\r\n        var selectedRow" +
"Index = 0;\r\n        var queryJson = $(\"#filter-form\").getWebControls();\r\n       " +
" queryJson[\"DISASTERTYPE\"] = tabvalue;\r\n        queryJson[\"PROVINCE\"] = PROVINCE" +
";\r\n        queryJson[\"CITY\"] = CITY;\r\n        queryJson[\"COUNTY\"] = COUNTY;\r\n   " +
"     var $gridTable = $(\'#gridTable3\');\r\n        $gridTable.jqGrid({\r\n          " +
"  autowidth: true,\r\n            postData: { queryJson: JSON.stringify(queryJson)" +
" },\r\n            height: $(\'#layout2 .ui-layout-center\').height() - 145 + 12,\r\n " +
"           url: queryUrl,\r\n            datatype: \"json\",\r\n            loadBefore" +
"Send: function (a) {\r\n                a.setRequestHeader(\"Authorization\", authTo" +
"ken);\r\n            },\r\n            colModel: [\r\n                { label: \'ID\', n" +
"ame: \'UNIFIEDCODE\', index: \'UNIFIEDCODE\', width: 300, align: \'left\', sortable: f" +
"alse, hidden: true },\r\n                { label: \'医院名称\', name: \'NAME\', index: \'NA" +
"ME\', width: 200, align: \'left\', sortable: false },\r\n                { label: \'身份" +
"证号\', name: \'CARDID\', index: \'CARDID\', width: 140, align: \'left\', sortable: false" +
", hidden: true },\r\n                { label: \'经度\', name: \'LONGITUDE\', index: \'LON" +
"GITUDE\', width: 100, align: \'left\', sortable: true, hidden: true },\r\n           " +
"     { label: \'纬度\', name: \'LATITUDE\', index: \'LATITUDE\', width: 100, align: \'lef" +
"t\', sortable: true, hidden: true },\r\n                { label: \'区县\', name: \'CITY\'" +
", index: \'CITY\', width: 120, align: \'left\', sortable: false },\r\n                " +
"{ label: \'乡镇\', name: \'TOWN\', index: \'TOWN\', width: 120, align: \'left\', sortable:" +
" false },\r\n                { label: \'村组\', name: \'VILLAGE\', index: \'VILLAGE\', wid" +
"th: 120, align: \'left\', sortable: false },\r\n                { label: \'修建时间\', nam" +
"e: \'CREATETIME\', index: \'CREATETIME\', width: 140, align: \'left\', sortable: false" +
", hidden: true },\r\n                { label: \'建筑面积\', name: \'AREASTRUCTURE\', index" +
": \'AREASTRUCTURE\', width: 100, align: \'left\', sortable: false },\r\n              " +
"  { label: \'结构类型\', name: \'STRUCTURETYPE\', index: \'STRUCTURETYPE\', width: 100, al" +
"ign: \'left\', sortable: false, hidden: true },\r\n                { label: \'电话\', na" +
"me: \'PHONE\', index: \'PHONE\', width: 140, align: \'left\', sortable: false, hidden:" +
" true },\r\n                { label: \'手机\', name: \'MOBILE\', index: \'MOBILE\', width:" +
" 140, align: \'left\', sortable: false, hidden: true },\r\n                { label: " +
"\'职工人数\', name: \'HOSPITALPEOPLE\', index: \'HOSPITALPEOPLE\', width: 100, align: \'lef" +
"t\', sortable: false, hidden: true },\r\n                { label: \'总资产\', name: \'TOT" +
"ALASSETS\', index: \'TOTALASSETS\', width: 100, align: \'left\', sortable: false },\r\n" +
"                { label: \'占地面积\', name: \'FLOORSPACE\', index: \'FLOORSPACE\', width:" +
" 100, align: \'left\', sortable: false, hidden: true },\r\n                { label: " +
"\'日就诊人\', name: \'AVERAGEDAILY\', index: \'AVERAGEDAILY\', width: 100, align: \'left\', " +
"sortable: false, hidden: true },\r\n                { label: \'病床数\', name: \'SICKBED" +
"NUMBER\', index: \'SICKBEDNUMBER\', width: 100, align: \'left\', sortable: false, hid" +
"den: true },\r\n                { label: \'医护人员数\', name: \'MEDICALWORKERS\', index: \'" +
"MEDICALWORKERS\', width: 100, align: \'left\', sortable: false },\r\n                " +
"{ label: \'救护车辆数\', name: \'AMBULANCE\', index: \'AMBULANCE\', width: 100, align: \'lef" +
"t\', sortable: false, hidden: true },\r\n                { label: \'医院等级\', name: \'HO" +
"SPITALRANK\', index: \'HOSPITALRANK\', width: 100, align: \'left\', sortable: false }" +
",\r\n                { label: \'法人\', name: \'LEGALPERSON\', index: \'LEGALPERSON\', wid" +
"th: 120, align: \'left\', sortable: false },\r\n                { label: \'医院ID\', nam" +
"e: \'NAMEID\', index: \'NAMEID\', width: 100, align: \'left\', sortable: false, hidden" +
": true },\r\n                { label: \'法人ID\', name: \'LEGALPERSONID\', index: \'LEGAL" +
"PERSONID\', width: 100, align: \'left\', sortable: false, hidden: true },\r\n        " +
"    ],\r\n            viewrecords: true,\r\n            rowNum: 30,\r\n            row" +
"List: [30, 50, 100],\r\n            pager: \"#gridPager3\",\r\n            sortname: \'" +
"UNIFIEDCODE\',\r\n            sortorder: \'desc\',\r\n            rownumbers: true,\r\n  " +
"          shrinkToFit: true,\r\n            gridview: true,\r\n            onSelectR" +
"ow: function (rowId, status) {\r\n                selectedRowIndex = $(\'#\' + this." +
"id).getGridParam(\'selrow\');\r\n                var dt = $gridTable.jqGrid(\"getRowD" +
"ata\", rowId);\r\n                var data = [];\r\n                var longitude = 0" +
", latitude = 0;\r\n                if (dt.LONGITUDE) {\r\n                    longit" +
"ude = parseFloat(DFMZH(dt.LONGITUDE));\r\n                }\r\n                if (d" +
"t.LATITUDE) {\r\n                    latitude = parseFloat(DFMZH(dt.LATITUDE));\r\n " +
"               }\r\n                data.push({ longitude: longitude, latitude: la" +
"titude });\r\n                //data.push({ longitude: dt.LONGITUDE, latitude: dt." +
"LATITUDE });\r\n                mapCtlExt.addLocation(data,true);\r\n            },\r" +
"\n            gridComplete: function () {\r\n                $(\'#\' + this.id).setSe" +
"lection(selectedRowIndex, false);\r\n            }\r\n        });\r\n    }\r\n    //加载学校" +
"表格\r\n    function GetSchoolGrid() {\r\n        var selectedRowIndex = 0;\r\n        v" +
"ar queryJson = $(\"#filter-form\").getWebControls();\r\n        queryJson[\"DISASTERT" +
"YPE\"] = tabvalue;\r\n        queryJson[\"PROVINCE\"] = PROVINCE;\r\n        queryJson[" +
"\"CITY\"] = CITY;\r\n        queryJson[\"COUNTY\"] = COUNTY;\r\n        var $gridTable =" +
" $(\'#gridTable4\');\r\n        $gridTable.jqGrid({\r\n            autowidth: true,\r\n " +
"           postData: { queryJson: JSON.stringify(queryJson) },\r\n            heig" +
"ht: $(\'#layout2 .ui-layout-center\').height() - 145 + 12,\r\n            url: query" +
"Url,\r\n            datatype: \"json\",\r\n            loadBeforeSend: function (a) {\r" +
"\n                a.setRequestHeader(\"Authorization\", authToken);\r\n            }," +
"\r\n            colModel: [\r\n                { label: \'ID\', name: \'UNIFIEDCODE\', i" +
"ndex: \'UNIFIEDCODE\', width: 300, align: \'left\', sortable: false, hidden: true }," +
"\r\n                { label: \'学校名称\', name: \'NAME\', index: \'NAME\', width: 180, alig" +
"n: \'left\', sortable: false, hidden: true },\r\n                { label: \'身份证号\', na" +
"me: \'CARDID\', index: \'CARDID\', width: 140, align: \'left\', sortable: false },\r\n  " +
"              { label: \'经度\', name: \'LONGITUDE\', index: \'LONGITUDE\', width: 100, " +
"align: \'left\', sortable: true, hidden: true },\r\n                { label: \'纬度\', n" +
"ame: \'LATITUDE\', index: \'LATITUDE\', width: 100, align: \'left\', sortable: true, h" +
"idden: true },\r\n                { label: \'区县\', name: \'CITY\', index: \'CITY\', widt" +
"h: 120, align: \'left\', sortable: false },\r\n                { label: \'乡镇\', name: " +
"\'TOWN\', index: \'TOWN\', width: 120, align: \'left\', sortable: false },\r\n          " +
"      { label: \'村组\', name: \'VILLAGE\', index: \'VILLAGE\', width: 120, align: \'left" +
"\', sortable: false },\r\n                { label: \'修建时间\', name: \'CREATETIME\', inde" +
"x: \'CREATETIME\', width: 140, align: \'left\', sortable: false, hidden: true },\r\n  " +
"              { label: \'建筑面积\', name: \'AREASTRUCTURE\', index: \'AREASTRUCTURE\', wi" +
"dth: 100, align: \'left\', sortable: false},\r\n                { label: \'结构类型\', nam" +
"e: \'STRUCTURETYPE\', index: \'STRUCTURETYPE\', width: 120, align: \'left\', sortable:" +
" false, hidden: true },\r\n                { label: \'电话\', name: \'PHONE\', index: \'P" +
"HONE\', width: 140, align: \'left\', sortable: false, hidden: true },\r\n            " +
"    { label: \'手机\', name: \'MOBILE\', index: \'MOBILE\', width: 140, align: \'left\', s" +
"ortable: false, hidden: true },\r\n                { label: \'学校人数\', name: \'SCHOOLP" +
"EOPLE\', index: \'SCHOOLPEOPLE\', width: 100, align: \'left\', sortable: false},\r\n   " +
"             { label: \'住校人数\', name: \'RESIDENCENUM\', index: \'RESIDENCENUM\', width" +
": 100, align: \'left\', sortable: false, hidden: true },\r\n                { label:" +
" \'学校总资产\', name: \'TOTALASSETS\', index: \'TOTALASSETS\', width: 100, align: \'left\', " +
"sortable: false},\r\n                { label: \'占地面积\', name: \'FLOORSPACE\', index: \'" +
"FLOORSPACE\', width: 100, align: \'left\', sortable: false, hidden: true },\r\n      " +
"          { label: \'责任人\', name: \'LEGALPERSON\', index: \'LEGALPERSON\', width: 120," +
" align: \'left\', sortable: false },\r\n                { label: \'学校ID\', name: \'NAME" +
"ID\', index: \'NAMEID\', width: 100, align: \'left\', sortable: false, hidden: true }" +
",\r\n                { label: \'责任人ID\', name: \'LEGALPERSONID\', index: \'LEGALPERSONI" +
"D\', width: 100, align: \'left\', sortable: false, hidden: true },\r\n            ],\r" +
"\n            viewrecords: true,\r\n            rowNum: 30,\r\n            rowList: [" +
"30, 50, 100],\r\n            pager: \"#gridPager4\",\r\n            sortname: \'UNIFIED" +
"CODE\',\r\n            sortorder: \'desc\',\r\n            rownumbers: true,\r\n         " +
"   shrinkToFit: true,\r\n            gridview: true,\r\n            onSelectRow: fun" +
"ction (rowId, status) {\r\n                selectedRowIndex = $(\'#\' + this.id).get" +
"GridParam(\'selrow\');\r\n                var dt = $gridTable.jqGrid(\"getRowData\", r" +
"owId);\r\n                var data = [];\r\n                var longitude = 0, latit" +
"ude = 0;\r\n                if (dt.LONGITUDE) {\r\n                    longitude = p" +
"arseFloat(DFMZH(dt.LONGITUDE));\r\n                }\r\n                if (dt.LATIT" +
"UDE) {\r\n                    latitude = parseFloat(DFMZH(dt.LATITUDE));\r\n        " +
"        }\r\n                data.push({ longitude: longitude, latitude: latitude " +
"});\r\n                mapCtlExt.addLocation(data,true);\r\n            },\r\n        " +
"    gridComplete: function () {\r\n                $(\'#\' + this.id).setSelection(s" +
"electedRowIndex, false);\r\n            }\r\n        });\r\n    }\r\n    //加载居民住宅表格\r\n   " +
" function GetResidentGrid() {\r\n        var selectedRowIndex = 0;\r\n        var qu" +
"eryJson = $(\"#filter-form\").getWebControls();\r\n        queryJson[\"DISASTERTYPE\"]" +
" = tabvalue;\r\n        queryJson[\"PROVINCE\"] = PROVINCE;\r\n        queryJson[\"CITY" +
"\"] = CITY;\r\n        queryJson[\"COUNTY\"] = COUNTY;\r\n        var $gridTable = $(\'#" +
"gridTable5\');\r\n        $gridTable.jqGrid({\r\n            autowidth: true,\r\n      " +
"      postData: { queryJson: JSON.stringify(queryJson) },\r\n            height: $" +
"(\'#layout2 .ui-layout-center\').height() - 145 + 12,\r\n            url: queryUrl,\r" +
"\n            datatype: \"json\",\r\n            loadBeforeSend: function (a) {\r\n    " +
"            a.setRequestHeader(\"Authorization\", authToken);\r\n            },\r\n   " +
"         colModel: [\r\n                { label: \'ID\', name: \'UNIFIEDCODE\', index:" +
" \'UNIFIEDCODE\', width: 300, align: \'left\', sortable: false, hidden: true },\r\n   " +
"             { label: \'户主\', name: \'NAME\', index: \'NAME\', width: 180, align: \'lef" +
"t\', sortable: false },\r\n                { label: \'身份证号\', name: \'CARDID\', index: " +
"\'CARDID\', width: 140, align: \'left\', sortable: false, hidden: true },\r\n         " +
"       { label: \'经度\', name: \'LONGITUDE\', index: \'LONGITUDE\', width: 100, align: " +
"\'left\', sortable: true, hidden: true },\r\n                { label: \'纬度\', name: \'L" +
"ATITUDE\', index: \'LATITUDE\', width: 100, align: \'left\', sortable: true, hidden: " +
"true },\r\n                { label: \'区县\', name: \'CITY\', index: \'CITY\', width: 120," +
" align: \'left\', sortable: false },\r\n                { label: \'乡镇\', name: \'TOWN\'," +
" index: \'TOWN\', width: 120, align: \'left\', sortable: false },\r\n                {" +
" label: \'村组\', name: \'VILLAGE\', index: \'VILLAGE\', width: 120, align: \'left\', sort" +
"able: false },\r\n                { label: \'电话\', name: \'PHONE\', index: \'PHONE\', wi" +
"dth: 140, align: \'left\', sortable: false, hidden: true },\r\n                { lab" +
"el: \'手机\', name: \'MOBILE\', index: \'MOBILE\', width: 140, align: \'left\', sortable: " +
"false, hidden: true },\r\n                { label: \'户数\', name: \'HOUSEHOLD\', index:" +
" \'HOUSEHOLD\', width: 100, align: \'left\', sortable: false, hidden: true },\r\n     " +
"           { label: \'家庭人口\', name: \'FAMILYNUMBER\', index: \'FAMILYNUMBER\', width: " +
"100, align: \'left\', sortable: false},\r\n                { label: \'人年均收入\', name: \'" +
"AVERAGEINCOME\', index: \'AVERAGEINCOME\', width: 100, align: \'left\', sortable: fal" +
"se, hidden: true },\r\n                { label: \'修建时间\', name: \'CREATETIME\', index:" +
" \'CREATETIME\', width: 140, align: \'left\', sortable: false, hidden: true },\r\n    " +
"            { label: \'房屋层数\', name: \'STOREYNUMBER\', index: \'STOREYNUMBER\', width:" +
" 100, align: \'left\', sortable: false, hidden: true },\r\n                { label: " +
"\'建筑面积\', name: \'AREASTRUCTURE\', index: \'AREASTRUCTURE\', width: 100, align: \'left\'" +
", sortable: false},\r\n                { label: \'单位造价\', name: \'UNITPRICE\', index: " +
"\'UNITPRICE\', width: 100, align: \'left\', sortable: false},\r\n                { lab" +
"el: \'结构类型\', name: \'STRUCTURETYPE\', index: \'HOUSEHOLD\', width: 120, align: \'left\'" +
", sortable: false },\r\n                { label: \'户主编号\', name: \'NAMEID\', index: \'N" +
"AMEID\', width: 100, align: \'left\', sortable: false, hidden: true }\r\n            " +
"],\r\n            viewrecords: true,\r\n            rowNum: 30,\r\n            rowList" +
": [30, 50, 100],\r\n            pager: \"#gridPager5\",\r\n            sortname: \'UNIF" +
"IEDCODE\',\r\n            sortorder: \'desc\',\r\n            rownumbers: true,\r\n      " +
"      shrinkToFit: true,\r\n            gridview: true,\r\n            onSelectRow: " +
"function (rowId, status) {\r\n                selectedRowIndex = $(\'#\' + this.id)." +
"getGridParam(\'selrow\');\r\n                var dt = $gridTable.jqGrid(\"getRowData\"" +
", rowId);\r\n                var data = [];\r\n                var longitude = 0, la" +
"titude = 0;\r\n                if (dt.LONGITUDE) {\r\n                    longitude " +
"= parseFloat(DFMZH(dt.LONGITUDE));\r\n                }\r\n                if (dt.LA" +
"TITUDE) {\r\n                    latitude = parseFloat(DFMZH(dt.LATITUDE));\r\n     " +
"           }\r\n                data.push({ longitude: longitude, latitude: latitu" +
"de });\r\n                //data.push({ longitude: dt.LONGITUDE, latitude: dt.LATI" +
"TUDE });\r\n                mapCtlExt.addLocation(data,true);\r\n            },\r\n   " +
"         gridComplete: function () {\r\n                $(\'#\' + this.id).setSelect" +
"ion(selectedRowIndex, false);\r\n            }\r\n        });\r\n    }\r\n    //加载地图mark" +
"er\r\n    function BindMapMarkerGov() {\r\n        var queryJson = $(\"#filter-form\")" +
".getWebControls();\r\n        queryJson[\"AreaCode\"] = AreaCode;\r\n        $.ajax({\r" +
"\n            url: \"../../JXGeoManage/TBL_RWJJ_GOVERNMENT/GetListJson\",\r\n        " +
"    data: { queryJson: JSON.stringify(queryJson) },\r\n            beforeSend: fun" +
"ction (a) {\r\n                if (authToken != null)\r\n                    a.setRe" +
"questHeader(\"Authorization\", authToken);\r\n            },\r\n            type: \"GET" +
"\",\r\n            dataType: \'json\',\r\n            success: function (data) {\r\n     " +
"           var returnValue = [];\r\n                var type = [];\r\n              " +
"  for (var i = 0; i < data.length; i++) {\r\n                    //详情页面\r\n         " +
"           var divhtml = \'<div style=\"font-weight: bold;\"></div>\';\r\n            " +
"        divhtml += \'<div style=\"font-weight: bold;margin-bottom:5px;\"><span styl" +
"e=\"margin-left:10px;\">单位名称：</span><span>\' + data[i].NAME + \'</span></div>\';\r\n   " +
"                 divhtml += \'<div style=\"margin-bottom:5px;\"><span style=\"margin" +
"-left:10px;\">机构级别：</span><span>\' + data[i].ORGANIZATIONLEVEL + \'</span></div>\';\r" +
"\n                    divhtml += \'<div style=\"margin-bottom:5px;\"><span style=\"ma" +
"rgin-left:10px;\">联系人：</span><span>\' + data[i].CONTACTPERSON + \'</span></div>\';\r\n" +
"                    //divhtml += \'<span style=\"margin-right:20px; float:right; c" +
"ursor: pointer;\"><a onclick=\"MapViewDetail(\\\'\' + data[i].UNIFIEDCODE + \'\\\')\" hre" +
"f=\"#\" class=\"link-detail\">详细信息</a></span>\';\r\n                    returnValue.pus" +
"h({ id: \"all\", url: \"../../Content/images/人文经济-政府16.png\", location: [data[i].LON" +
"GITUDE, data[i].LATITUDE], popupHtml: divhtml });\r\n                }\r\n          " +
"      mapCtlExt.addMarker(returnValue);\r\n            }, error: function (e) {\r\n " +
"           },\r\n            cache: false\r\n        });\r\n\r\n    };\r\n    function Bin" +
"dMapMarkerEnter() {\r\n        var queryJson = $(\"#filter-form\").getWebControls();" +
"\r\n        queryJson[\"AreaCode\"] = AreaCode;\r\n        $.ajax({\r\n            url: " +
"\"../../JXGeoManage/TBL_RWJJ_ENTERPRISE/GetListJson\",\r\n            data: { queryJ" +
"son: JSON.stringify(queryJson) },\r\n            beforeSend: function (a) {\r\n     " +
"           if (authToken != null)\r\n                    a.setRequestHeader(\"Autho" +
"rization\", authToken);\r\n            },\r\n            type: \"GET\",\r\n            da" +
"taType: \'json\',\r\n            success: function (data) {\r\n                var ret" +
"urnValue = [];\r\n                var type = [];\r\n                for (var i = 0; " +
"i < data.length; i++) {\r\n                    //详情页面\r\n                    var div" +
"html = \'<div style=\"font-weight: bold;\"></div>\';\r\n                    divhtml +=" +
" \'<div style=\"font-weight: bold;margin-bottom:5px;\"><span style=\"margin-left:10p" +
"x;\">企业名称：</span><span>\' + data[i].NAME + \'</span></div>\';\r\n                    d" +
"ivhtml += \'<div style=\"margin-bottom:5px;\"><span style=\"margin-left:10px;\">建筑面积：" +
"</span><span>\' + data[i].AREASTRUCTURE + \'</span></div>\';\r\n                    d" +
"ivhtml += \'<div style=\"margin-bottom:5px;\"><span style=\"margin-left:10px;\">总资产：<" +
"/span><span>\' + data[i].TOTALASSETS + \'</span></div>\';\r\n                    divh" +
"tml += \'<div style=\"margin-bottom:5px;\"><span style=\"margin-left:10px;\">法人：</spa" +
"n><span>\' + data[i].LEGALPERSON + \'</span></div>\';\r\n                    //divhtm" +
"l += \'<span style=\"margin-right:20px; float:right; cursor: pointer;\"><a onclick=" +
"\"MapViewDetail(\\\'\' + data[i].UNIFIEDCODE + \'\\\')\" href=\"#\" class=\"link-detail\">详细" +
"信息</a></span>\';\r\n                    returnValue.push({ id: \"all\", url: \"../../C" +
"ontent/images/人文经济-企业16.png\", location: [data[i].LONGITUDE, data[i].LATITUDE], p" +
"opupHtml: divhtml });\r\n                }\r\n                mapCtlExt.addMarker(re" +
"turnValue);\r\n            }, error: function (e) {\r\n            },\r\n            c" +
"ache: false\r\n        });\r\n    }\r\n    function BindMapMarkerHospital() {\r\n       " +
" var queryJson = $(\"#filter-form\").getWebControls();\r\n        queryJson[\"AreaCod" +
"e\"] = AreaCode;\r\n        $.ajax({\r\n            url: \"../../JXGeoManage/TBL_RWJJ_" +
"HOSPITAL/GetListJson\",\r\n            data: { queryJson: JSON.stringify(queryJson)" +
" },\r\n            beforeSend: function (a) {\r\n                if (authToken != nu" +
"ll)\r\n                    a.setRequestHeader(\"Authorization\", authToken);\r\n      " +
"      },\r\n            type: \"GET\",\r\n            dataType: \'json\',\r\n            s" +
"uccess: function (data) {\r\n                var returnValue = [];\r\n              " +
"  var type = [];\r\n                for (var i = 0; i < data.length; i++) {\r\n     " +
"               //详情页面\r\n                    var divhtml = \'<div style=\"font-weigh" +
"t: bold;\"></div>\';\r\n                    divhtml += \'<div style=\"font-weight: bol" +
"d;margin-bottom:5px;\"><span style=\"margin-left:10px;\">医院名称：</span><span>\' + data" +
"[i].NAME + \'</span></div>\';\r\n                    divhtml += \'<div style=\"margin-" +
"bottom:5px;\"><span style=\"margin-left:10px;\">医院等级：</span><span>\' + data[i].HOSPI" +
"TALRANK + \'</span></div>\';\r\n                    divhtml += \'<div style=\"margin-b" +
"ottom:5px;\"><span style=\"margin-left:10px;\">建筑面积：</span><span>\' + data[i].AREAST" +
"RUCTURE + \'</span></div>\';\r\n                    divhtml += \'<div style=\"margin-b" +
"ottom:5px;\"><span style=\"margin-left:10px;\">总资产：</span><span>\' + data[i].TOTALAS" +
"SETS + \'</span></div>\';\r\n                    //divhtml += \'<span style=\"margin-r" +
"ight:20px; float:right; cursor: pointer;\"><a onclick=\"MapViewDetail(\\\'\' + data[i" +
"].UNIFIEDCODE + \'\\\')\" href=\"#\" class=\"link-detail\">详细信息</a></span>\';\r\n          " +
"          returnValue.push({ id: \"all\", url: \"../../Content/images/人文经济-医院16.png" +
"\", location: [data[i].LONGITUDE, data[i].LATITUDE], popupHtml: divhtml });\r\n    " +
"            }\r\n                mapCtlExt.addMarker(returnValue);\r\n            }," +
" error: function (e) {\r\n            },\r\n            cache: false\r\n        });\r\n " +
"   }\r\n    function BindMapMarkerSchool() {\r\n        var queryJson = $(\"#filter-f" +
"orm\").getWebControls();\r\n        queryJson[\"AreaCode\"] = AreaCode;\r\n        $.aj" +
"ax({\r\n            url: \"../../JXGeoManage/TBL_RWJJ_SCHOOL/GetListJson\",\r\n       " +
"     data: { queryJson: JSON.stringify(queryJson) },\r\n            beforeSend: fu" +
"nction (a) {\r\n                if (authToken != null)\r\n                    a.setR" +
"equestHeader(\"Authorization\", authToken);\r\n            },\r\n            type: \"GE" +
"T\",\r\n            dataType: \'json\',\r\n            success: function (data) {\r\n    " +
"            var returnValue = [];\r\n                var type = [];\r\n             " +
"   for (var i = 0; i < data.length; i++) {\r\n                    //详情页面\r\n        " +
"            var divhtml = \'<div style=\"font-weight: bold;\"></div>\';\r\n           " +
"         divhtml += \'<div style=\"font-weight: bold;margin-bottom:5px;\"><span sty" +
"le=\"margin-left:10px;\">学校名称：</span><span>\' + data[i].NAME + \'</span></div>\';\r\n  " +
"                  divhtml += \'<div style=\"margin-bottom:5px;\"><span style=\"margi" +
"n-left:10px;\">学校人数：</span><span>\' + data[i].SCHOOLPEOPLE + \'</span></div>\';\r\n   " +
"                 divhtml += \'<div style=\"margin-bottom:5px;\"><span style=\"margin" +
"-left:10px;\">建筑面积：</span><span>\' + data[i].AREASTRUCTURE + \'</span></div>\';\r\n   " +
"                 divhtml += \'<div style=\"margin-bottom:5px;\"><span style=\"margin" +
"-left:10px;\">总资产：</span><span>\' + data[i].TOTALASSETS + \'</span></div>\';\r\n      " +
"              //divhtml += \'<span style=\"margin-right:20px; float:right; cursor:" +
" pointer;\"><a onclick=\"MapViewDetail(\\\'\' + data[i].UNIFIEDCODE + \'\\\')\" href=\"#\" " +
"class=\"link-detail\">详细信息</a></span>\';\r\n                    returnValue.push({ id" +
": \"all\", url: \"../../Content/images/人文经济-学校16.png\", location: [data[i].LONGITUDE" +
", data[i].LATITUDE], popupHtml: divhtml });\r\n                }\r\n                " +
"mapCtlExt.addMarker(returnValue);\r\n            }, error: function (e) {\r\n       " +
"     },\r\n            cache: false\r\n        });\r\n    }\r\n    function BindMapMarke" +
"rResident() {\r\n        var queryJson = $(\"#filter-form\").getWebControls();\r\n    " +
"    queryJson[\"AreaCode\"] = AreaCode;\r\n        $.ajax({\r\n            url: \"../.." +
"/JXGeoManage/TBL_RWJJ_RESIDENTIALAREA/GetListJson\",\r\n            data: { queryJs" +
"on: JSON.stringify(queryJson) },\r\n            beforeSend: function (a) {\r\n      " +
"          if (authToken != null)\r\n                    a.setRequestHeader(\"Author" +
"ization\", authToken);\r\n            },\r\n            type: \"GET\",\r\n            dat" +
"aType: \'json\',\r\n            success: function (data) {\r\n                var retu" +
"rnValue = [];\r\n                var type = [];\r\n                for (var i = 0; i" +
" < data.length; i++) {\r\n                    //详情页面\r\n                    var divh" +
"tml = \'<div style=\"font-weight: bold;\"></div>\';\r\n                    divhtml += " +
"\'<div style=\"font-weight: bold;margin-bottom:5px;\"><span style=\"margin-left:10px" +
";\">户主：</span><span>\' + data[i].NAME + \'</span></div>\';\r\n                    divh" +
"tml += \'<div style=\"margin-bottom:5px;\"><span style=\"margin-left:10px;\">家庭人口：</s" +
"pan><span>\' + data[i].FAMILYNUMBER + \'</span></div>\';\r\n                    divht" +
"ml += \'<div style=\"margin-bottom:5px;\"><span style=\"margin-left:10px;\">建筑面积：</sp" +
"an><span>\' + data[i].AREASTRUCTURE + \'</span></div>\';\r\n                    divht" +
"ml += \'<div style=\"margin-bottom:5px;\"><span style=\"margin-left:10px;\">单位造价：</sp" +
"an><span>\' + data[i].UNITPRICE + \'</span></div>\';\r\n                    //divhtml" +
" += \'<span style=\"margin-right:20px; float:right; cursor: pointer;\"><a onclick=\"" +
"MapViewDetail(\\\'\' + data[i].UNIFIEDCODE + \'\\\')\" href=\"#\" class=\"link-detail\">详细信" +
"息</a></span>\';\r\n                    returnValue.push({ id: \"all\", url: \"../../Co" +
"ntent/images/人文经济-居民16.png\", location: [data[i].LONGITUDE, data[i].LATITUDE], po" +
"pupHtml: divhtml });\r\n                }\r\n                mapCtlExt.addMarker(ret" +
"urnValue);\r\n            }, error: function (e) {\r\n            },\r\n            ca" +
"che: false\r\n        });\r\n    }\r\n    function btn_message() {\r\n        var keyVal" +
"ue = $(\"#\" + gridId).jqGridRowValue(\'UNIFIEDCODE\');\r\n        if (checkedRow(keyV" +
"alue)) {\r\n            ViewMonitorDetail(keyValue);\r\n        }\r\n    }\r\n    functi" +
"on ViewMonitorDetail(keyValue) {\r\n        var url = document.location.protocol +" +
" \"//\" + document.location.host + linkUrl + \"?keyValue=\" + keyValue + \'&IdetIfrem" +
"=Idetnew&UNIFIEDCODE=\' + keyValue + \'&XQing=01\' + \"&callback=\" + document.URL;\r\n" +
"        document.location.href = url;\r\n    }\r\n    //地图详情\r\n    function MapViewDe" +
"tail(type) {\r\n        console.log(type)\r\n        var keyValue = type.split(\",\")[" +
"1];\r\n        var types = type.split(\",\")[0];\r\n        var title = types;\r\n      " +
"  if (types == \"滑坡\") {\r\n            types = \"001\"\r\n        } else if (types == \"" +
"崩塌\") {\r\n            types = \"002\"\r\n        } else if (types == \"泥石流\") {\r\n       " +
"     types = \"003\"\r\n        } else if (types == \"地面沉降\") {\r\n            types = \"" +
"004\"\r\n        } else if (types == \"地面塌陷\") {\r\n            types = \"005\"\r\n        " +
"} else if (types == \"地裂缝\") {\r\n            types = \"006\"\r\n        } else if (type" +
"s == \"斜坡\") {\r\n            types = \"007\"\r\n        }\r\n        if (checkedRow(keyVa" +
"lue)) {\r\n            //top.tablist.newTab({\r\n            //    id: \'DetailForm\'," +
"\r\n            //    title: title + \'详情表\',\r\n            //    icon: \"fa fa-file-t" +
"ext-o\",\r\n            //    url: \"/JXGeoManage/TBL_HAZARDBASICINFO/DETAIL?keyValu" +
"e=\" + keyValue + \"&types=\" + types,\r\n            //    width: \'1300px\',\r\n       " +
"     //    height: \'\',\r\n            //    callBack: function (iframeId) {\r\n     " +
"       //        getInfoTop().frames[iframeId].AcceptClick();\r\n            //   " +
" },\r\n            //    btn: []\r\n            //});\r\n            var url = documen" +
"t.location.protocol + \"//\" + document.location.host + \"/JXGeoManage/TBL_HAZARDBA" +
"SICINFO/DETAIL?keyValue=\" + keyValue + \"&types=\" + types + \"&callback=\" + window" +
".document.URL;\r\n            window.document.location.href = url;\r\n        }\r\n   " +
" }\r\n\r\n    \r\n\r\n    //查询表格函数\r\n    function SearchEvent() {\r\n        var queryJson " +
"= $(\"#filter-form\").getWebControls();\r\n        queryJson[\"DISASTERTYPE\"] = tabva" +
"lue\r\n        queryJson[\"PROVINCE\"] = PROVINCE;\r\n        queryJson[\"CITY\"] = CITY" +
";\r\n        queryJson[\"COUNTY\"] = COUNTY;\r\n        $(\"#\" + gridId).jqGrid(\'setGri" +
"dParam\', {\r\n            postData: { queryJson: JSON.stringify(queryJson) },\r\n   " +
"         url: queryUrl,\r\n            page: 1\r\n        }).trigger(\'reloadGrid\');\r" +
"\n\r\n        BindMapMarker();\r\n    }\r\n\r\n    function ColDataGrid() {\r\n        var " +
"centerHeight = $(\"#layout2\").height();\r\n        var layout2 = $(\'#layout2\').layo" +
"ut();\r\n        if ($(\"#lr-colgrid i\").hasClass(\"fa-chevron-down\")) {\r\n          " +
"  var northH = centerHeight - 105;\r\n            layout2.sizePane(\"north\", northH" +
");\r\n            $(\"#lr-colgrid i\").removeClass(\"fa-chevron-down\");\r\n            " +
"$(\"#lr-colgrid i\").addClass(\"fa-chevron-up\");\r\n            if ($(\"#lr-colmap i\")" +
".hasClass(\"fa-chevron-down\")) {\r\n                $(\"#lr-colmap i\").removeClass(\"" +
"fa-chevron-down\");\r\n                $(\"#lr-colmap i\").addClass(\"fa-chevron-up\");" +
"\r\n            }\r\n        }\r\n        else {\r\n            layout2.sizePane(\"north\"" +
", layout2NorthH);\r\n            $(\"#lr-colgrid i\").removeClass(\"fa-chevron-up\");\r" +
"\n            $(\"#lr-colgrid i\").addClass(\"fa-chevron-down\");\r\n        }\r\n       " +
" mapCtlExt.updateSize();\r\n    }\r\n\r\n    function ColMapDiv() {\r\n        var layou" +
"t2 = $(\'#layout2\').layout();\r\n        if ($(\"#lr-colmap i\").hasClass(\"fa-chevron" +
"-up\")) {\r\n            layout2.sizePane(\"north\", 1);\r\n            $(\"#lr-colmap i" +
"\").removeClass(\"fa-chevron-up\");\r\n            $(\"#lr-colmap i\").addClass(\"fa-che" +
"vron-down\");\r\n            if ($(\"#lr-colgrid i\").hasClass(\"fa-chevron-up\")) {\r\n " +
"               $(\"#lr-colgrid i\").removeClass(\"fa-chevron-up\");\r\n               " +
" $(\"#lr-colgrid i\").addClass(\"fa-chevron-down\");\r\n            }\r\n        }\r\n    " +
"    else {\r\n            layout2.sizePane(\"north\", layout2NorthH);\r\n            $" +
"(\"#lr-colmap i\").removeClass(\"fa-chevron-down\");\r\n            $(\"#lr-colmap i\")." +
"addClass(\"fa-chevron-up\");\r\n            if (mapCtlExt != null) {\r\n              " +
"  mapCtlExt.setHeight($(\"#mapControl\").parent().height() - 32 - 4);\r\n           " +
" }\r\n        }\r\n        mapCtlExt.updateSize();\r\n    }\r\n</script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
