#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/SystemManage/Views/DataItemList/Form.cshtml")]
    public partial class _Areas_SystemManage_Views_DataItemList_Form_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_SystemManage_Views_DataItemList_Form_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\SystemManage\Views\DataItemList\Form.cshtml"
  
    ViewBag.Title = "辅助资料";
    Layout = "~/Views/Shared/_Form.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n    var keyValue = request(\'keyValue\');\r\n    var itemId = request(\'it" +
"emId\');\r\n    var parentId = request(\'parentId\');\r\n    $(function () {\r\n        i" +
"nitControl();\r\n    })\r\n    //初始化控件\r\n    function initControl() {\r\n        //获取表单" +
"\r\n        if (!!keyValue) {\r\n            $.SetForm({\r\n                url: \"../." +
"./SystemManage/DataItemList/GetFormJson\",\r\n                param: { keyValue: ke" +
"yValue },\r\n                success: function (data) {\r\n                    $(\"#f" +
"orm1\").SetWebControls(data);\r\n                }\r\n            });\r\n        } else" +
" {\r\n            $(\"#F_ParentId\").val(parentId);\r\n            $(\"#F_ItemId\").val(" +
"itemId);\r\n        }\r\n    }\r\n    //保存表单\r\n    function AcceptClick() {\r\n        if" +
" (!$(\'#form1\').Validform()) {\r\n            return false;\r\n        }\r\n        var" +
" postData = $(\"#form1\").GetWebControls(keyValue);\r\n        if (postData[\"F_Paren" +
"tId\"] == \"\") {\r\n            postData[\"F_ParentId\"] = 0;\r\n        }\r\n        $.Sa" +
"veForm({\r\n            url: \"../../SystemManage/DataItemList/SaveForm?keyValue=\" " +
"+ keyValue,\r\n            param: postData,\r\n            loading: \"正在保存数据...\",\r\n  " +
"          success: function () {\r\n                if (getInfoTop().DataItemList " +
"== undefined) {\r\n                    $.currentIframe().$(\"#gridTable\").resetSele" +
"ction();\r\n                    $.currentIframe().$(\"#gridTable\").trigger(\"reloadG" +
"rid\");\r\n                } else {\r\n                    getInfoTop().DataItemList." +
"$(\"#gridTable\").resetSelection();\r\n                    getInfoTop().DataItemList" +
".$(\"#gridTable\").trigger(\"reloadGrid\");\r\n                }\r\n            }\r\n     " +
"   })\r\n    }\r\n    //验证：项目值、项目名 不能重复\r\n    function OverrideExistField(id, url) {\r" +
"\n        $.ExistField(id, url, { itemId: itemId });\r\n    }\r\n</script>\r\n<div");

WriteLiteral(" style=\"margin-top: 20px; margin-right: 30px;\"");

WriteLiteral(">\r\n    <input");

WriteLiteral(" id=\"F_ParentId\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" />\r\n    <input");

WriteLiteral(" id=\"F_ItemId\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" />\r\n    <table");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n        <tr>\r\n            <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">项目名<font");

WriteLiteral(" face=\"宋体\"");

WriteLiteral(">*</font></td>\r\n            <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"F_ItemName\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" onblur=\"OverrideExistField(this.id,\'../../SystemManage/DataItemDetail/ExistItemN" +
"ame\')\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"请输入项目名\"");

WriteLiteral(" isvalid=\"yes\"");

WriteLiteral(" checkexpession=\"NotNull\"");

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">项目值<font");

WriteLiteral(" face=\"宋体\"");

WriteLiteral(">*</font></td>\r\n            <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"F_ItemValue\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" onblur=\"OverrideExistField(this.id,\'../../SystemManage/DataItemDetail/ExistItemV" +
"alue\')\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"请输入项目值\"");

WriteLiteral(" isvalid=\"yes\"");

WriteLiteral(" checkexpession=\"NotNull\"");

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(">排序<font");

WriteLiteral(" face=\"宋体\"");

WriteLiteral(">*</font></th>\r\n            <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"F_SortCode\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" isvalid=\"yes\"");

WriteLiteral(" checkexpession=\"Num\"");

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" style=\"height: 37px;\"");

WriteLiteral("></th>\r\n            <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n                    <label>\r\n                        <input");

WriteLiteral(" id=\"F_EnabledMark\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" checked=\"checked\"");

WriteLiteral(" />\r\n                        有效\r\n                    </label>\r\n                </" +
"div>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"formTitle\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" style=\"padding-top: 4px;\"");

WriteLiteral(">备注\r\n            </th>\r\n            <td");

WriteLiteral(" class=\"formValue\"");

WriteLiteral(">\r\n                <textarea");

WriteLiteral(" id=\"F_Description\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" style=\"height: 70px;\"");

WriteLiteral("></textarea>\r\n            </td>\r\n        </tr>\r\n    </table>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
