#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Infoearth.Application.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/JXGeoManage/Views/TBL_HAZARDBASICINFO/HarzardTrendAnalyse.cshtml")]
    public partial class _Areas_JXGeoManage_Views_TBL_HAZARDBASICINFO_HarzardTrendAnalyse_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_JXGeoManage_Views_TBL_HAZARDBASICINFO_HarzardTrendAnalyse_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\JXGeoManage\Views\TBL_HAZARDBASICINFO\HarzardTrendAnalyse.cshtml"
  
    ViewBag.Title = "列表页面";
    Layout = "~/Views/Shared/_IndexMap.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<style>\r\n    /*.ui-th-column, .ui-jqgrid .ui-jqgrid-htable th.ui-th-column " +
"{\r\n    border-top:1px solid #ccc\r\n        }*/\r\n    body, html {\r\n        backgro" +
"und: #fff;\r\n    }\r\n\r\n    .ui-layout-center {\r\n        overflow-x: hidden !import" +
"ant;\r\n    }\r\n\r\n    .ui-layout-resizer {\r\n        background-color: #f0f3f4 !impo" +
"rtant;\r\n    }\r\n\r\n    .diaochabiao {\r\n        text-align: center;\r\n    }\r\n\r\n\r\n   " +
" .table-top, .table-main, table-bottom {\r\n        margin: 0 20px;\r\n    }\r\n\r\n    " +
"    .table-main td {\r\n            border: 1px solid #D6D6D6;\r\n        }\r\n\r\n    ." +
"formValue input[type=text] {\r\n        border: 0;\r\n        border-bottom: 1px sol" +
"id #E0E0E0;\r\n    }\r\n\r\n    .diaochabiao .formValue textarea {\r\n        /*height:8" +
"0px;*/\r\n        border: none;\r\n    }\r\n\r\n    .diaochabiao .formTitle {\r\n        t" +
"ext-align: center !important;\r\n        /*width: 135px !important;*/\r\n        bac" +
"kground-color: #F5F5F5;\r\n        white-space: inherit;\r\n    }\r\n\r\n    .diaochabia" +
"o .formCategory {\r\n        font-size: 15px;\r\n        /*color: #3F549E;*/\r\n    }\r" +
"\n\r\n    .diaochabiao .required {\r\n        color: red;\r\n        padding-left: 5px;" +
"\r\n        vertical-align: middle;\r\n    }\r\n\r\n    .diaochabiao select {\r\n        b" +
"order: none;\r\n    }\r\n\r\n    .diaochabiao label {\r\n        margin: 0 2px;\r\n    }\r\n" +
"\r\n    #TOWN {\r\n        display: none;\r\n    }\r\n\r\n    #tab_content {\r\n        over" +
"flow-x: auto;\r\n        overflow-y: hidden;\r\n    }\r\n\r\n    #TjItem .ui-select-text" +
" {\r\n        border-radius: 4px;\r\n    }\r\n\r\n    #TjItem input {\r\n        border-ra" +
"dius: 4px;\r\n    }\r\n\r\n    #deviceTypeListA tr > td > label {\r\n        margin: 10p" +
"x 20px 0px 5px;\r\n    }\r\n\r\n    label {\r\n        margin-left: 20px;\r\n    }\r\n\r\n    " +
"body, html {\r\n        margin: 0;\r\n        height: 100%;\r\n    }\r\n\r\n    #myTabCont" +
"ent .spans {\r\n        padding: 0 20px !important;\r\n        width: 9%;\r\n        t" +
"ext-align: center;\r\n        height: 28px;\r\n        line-height: 28px;\r\n        m" +
"in-width: 113px;\r\n    }\r\n\r\n    #myTabContent .divselect {\r\n        width: 21%;\r\n" +
"    }\r\n\r\n    #myModal2 .spans {\r\n        float: left;\r\n        padding: 0px 10px" +
";\r\n        width: 9%;\r\n        text-align: center;\r\n        height: 28px;\r\n     " +
"   line-height: 28px;\r\n    }\r\n\r\n    #myModal2 .divselect {\r\n        width: 16%;\r" +
"\n    }\r\n\r\n    .ui-select-text {\r\n        border-radius: 4px;\r\n    }\r\n\r\n    #grid" +
"Table td, #gridTableA td {\r\n        border-right: 1px solid #ccc !important;\r\n  " +
"  }\r\n\r\n    .ui-jqgrid-btable tr:nth-child(odd) {\r\n        background: #DCDCDC\r\n " +
"   }\r\n\r\n    .nav-tabs a:hover {\r\n        border-bottom: none;\r\n    }\r\n\r\n    .nav" +
"-tabs {\r\n        margin-bottom: -1px;\r\n    }\r\n\r\n    .ui-priority-secondary, .ui-" +
"widget-content .ui-priority-secondary {\r\n        opacity: 1 !important;\r\n    }\r\n" +
"</style>\r\n\r\n<div>\r\n    <div");

WriteLiteral(" id=\"filter-form\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" style=\"width:100%;border: 1px solid #ccc;height:45px;line-height:45px;background" +
":#fff;display:flex;align-items: center;\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" style=\"font-size:14px;padding-left:20px; font-family:微软雅黑;color:#000;\"");

WriteLiteral(">行政区划:</span>\r\n            <div");

WriteLiteral(" id=\"districtsCtls\"");

WriteLiteral(" style=\"padding-left:30px;width:90%\"");

WriteLiteral("></div>\r\n        </div>\r\n        <div");

WriteLiteral(" style=\"width:100%;border: 1px solid #ccc;border-top:none;height:45px;line-height" +
":45px;background:#fff;display:flex\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" style=\"font-size:14px;padding-left:20px; font-family:微软雅黑;color:#000;\"");

WriteLiteral(">分析条件:</span>\r\n            <div");

WriteLiteral(" style=\"width:90%;height:100%;display:flex;align-items: center;padding-left:30px\"" +
"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"spans\"");

WriteLiteral("></span>\r\n                <div><input");

WriteLiteral(" id=\"startYear\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control input-wdatepicker\"");

WriteLiteral(" onfocus=\"WdatePicker({ dateFmt: \'yyyy\' })\"");

WriteLiteral(" /></div>\r\n                <span");

WriteLiteral(" class=\"spans\"");

WriteLiteral(">对比：</span>\r\n                <div><input");

WriteLiteral(" id=\"endYear\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control input-wdatepicker\"");

WriteLiteral(" onfocus=\"WdatePicker({ dateFmt: \'yyyy\' })\"");

WriteLiteral(" /></div>\r\n            </div>\r\n            ");

WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" style=\"width:100%;border: 1px solid #ccc;height:45px;border-top:none;background:" +
"#fff;display:flex;align-items: center;\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" style=\"font-size:14px;padding-left:20px; font-family:微软雅黑;color:#000;\"");

WriteLiteral(">分析内容:</span>\r\n            <div");

WriteLiteral(" style=\"width:65%;height:45px;margin-left:30px;display: flex;align-items: center;" +
"flex-wrap: wrap;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"lableall\"");

WriteLiteral(" style=\"width:100%;height:45px;display:flex;align-items: center;flex-wrap: wrap;m" +
"argin-left:30px;justify-content: start\"");

WriteLiteral(">\r\n                    <label><input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"Type\"");

WriteLiteral(" value=\"zqs\"");

WriteLiteral(" checked=\"checked\"");

WriteLiteral(">总趋势</label>\r\n                    <label><input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"Type\"");

WriteLiteral(" value=\"yhdgmqs\"");

WriteLiteral(">隐患点规模趋势</label>\r\n                    <label><input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"Type\"");

WriteLiteral(" value=\"zhlxjgmqs\"");

WriteLiteral(">灾害类型及规模趋势</label>\r\n                    ");

WriteLiteral("\r\n                    <label><input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"Type\"");

WriteLiteral(" value=\"nxhd\"");

WriteLiteral(">拟销号点</label>\r\n                    <label><input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"Type\"");

WriteLiteral(" value=\"gmdjdb\"");

WriteLiteral(">灾情、险情、规模等级对比</label>\r\n                </div>\r\n\r\n            </div>\r\n            " +
"<a");

WriteLiteral(" style=\"margin-left:50px\"");

WriteLiteral(" id=\"btn_Search\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-save\"");

WriteLiteral("></i>&nbsp;统计</a>\r\n            <a");

WriteLiteral(" id=\"lr-export\"");

WriteLiteral(" style=\"float: right;margin: 8px;\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" onclick=\"btn_export()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-file-excel-o\"");

WriteLiteral("></i>&nbsp;导出</a>\r\n        </div>\r\n\r\n    </div>\r\n    <ul");

WriteLiteral(" class=\"nav nav-tabs njyltj\"");

WriteLiteral(">\r\n        <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(" id=\"nav_dzhjwt\"");

WriteLiteral(" title=\"统计结果\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#tab_1\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(" onclick=\"$(\'.nav-tabs\').css(\'border-bottom\',\'none\')\"");

WriteLiteral(">统计结果</a></li>\r\n        <li");

WriteLiteral(" id=\"nav_yfsdzzh\"");

WriteLiteral(" title=\"统计图表\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#tab_2\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(" onclick=\"$(\'.nav-tabs\').css(\'border-bottom\',\'1px solid #ccc\')\"");

WriteLiteral(">统计图表</a></li>\r\n    </ul>\r\n    <div");

WriteLiteral(" id=\"myTabContent\"");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"tab-pane in active\"");

WriteLiteral(" id=\"tab_1\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"divGrid\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"gridTable\"");

WriteLiteral(" style=\"width:100%;height:100%\"");

WriteLiteral("></table>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"tab-pane in \"");

WriteLiteral(" id=\"tab_2\"");

WriteLiteral(" style=\"position: relative;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"TJTB\"");

WriteLiteral(" style=\"width:1650px;margin-top:20px;\"");

WriteLiteral(">\r\n\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"TREETYPE\"");

WriteLiteral(" type=\"select\"");

WriteLiteral(" class=\"ui-select\"");

WriteLiteral(" style=\"display:inline-block;width:230px;position:absolute;top:28px;right:50px;\"");

WriteLiteral("></div>\r\n        </div>\r\n    </div>\r\n\r\n</div>\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

            
            #line 207 "..\..\Areas\JXGeoManage\Views\TBL_HAZARDBASICINFO\HarzardTrendAnalyse.cshtml"
Write(System.Web.Optimization.Styles.Render(
    "~/Content/styles/report.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 209 "..\..\Areas\JXGeoManage\Views\TBL_HAZARDBASICINFO\HarzardTrendAnalyse.cshtml"
Write(System.Web.Optimization.Scripts.Render(
    "~/Content/scripts/plugins/districts/multiDistricts.js",
    "~/Content/scripts/plugins/echarts/echarts.min.js",
    "~/Content/report.js"
));

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n     var authToken = getAuthorizationToken();\r\n    var gridHeight = 2" +
"23;\r\n    $(function () {\r\n        InitialPage();\r\n        initControl();\r\n      " +
"  var date = new Date()\r\n        $(\'#startime\').val(date.getFullYear() - 1);\r\n  " +
"      GetGrid();\r\n        //查询点击事件\r\n        $(\"#btn_Search\").click(function () {" +
"\r\n            seachEvent();\r\n        });\r\n        $(window).resize(function () {" +
"\r\n            setTimeout(function () {\r\n                try {\r\n                 " +
"   myChart1.resize();\r\n                } catch (err) { }\r\n            }, 200);\r\n" +
"        });\r\n        $(\"#TREETYPE\").on(\"change\", function () {\r\n            tree" +
"type = $(\"#TREETYPE\").attr(\'data-value\');\r\n            seachEvent();\r\n        })" +
";\r\n\r\n    });\r\n    //初始化页面\r\n    function InitialPage() {\r\n        //resize重设布局;\r\n" +
"        var isResize = 0;\r\n        $(\"#TJTB\").height($(window).height() - 200);\r" +
"\n        $(\'#TJTB\').width($(window).width() - 100);\r\n        $(window).resize(fu" +
"nction (e) {\r\n            $(\"#TJTB\").height($(window).height() - 200);\r\n        " +
"    $(\'#TJTB\').width($(window).width() - 100);\r\n            window.setTimeout(fu" +
"nction () {\r\n                $(\'#gridTable\').setGridWidth(($(\'.gridPanel\').width" +
"()));\r\n                $(\'#gridTable\').setGridHeight($(window).height() - gridHe" +
"ight);\r\n            }, 200);\r\n            e.stopPropagation();\r\n        });\r\n   " +
" }\r\n    //初始化控件\r\n    function initControl() {\r\n        var date = new Date;\r\n   " +
"     var year = date.getFullYear();\r\n        $(\"#startYear\").val(year-1);\r\n     " +
"   $(\"#endYear\").val(year);\r\n\r\n        //行政区划加载\r\n        var html = \" <table><tr" +
"><td class=\\\"formTitle\\\" style=\\\"display: none;\\\">省:</td><td> <div id=\\\"PROVINCE" +
"\\\" multiples=\\\"true\\\" type=\\\"select\\\" class=\\\"ui-select\\\" style=\\\"float: left; w" +
"idth: 140px; margin: 8px; display: none;\\\"></div></td>\" +\r\n                     " +
" \"<td class=\\\"formTitle\\\">市:</td><td><div id=\\\"CITY\\\" multiples=\\\"true\\\" type=\\\"" +
"select\\\" class=\\\"ui-select\\\" style=\\\"float: left; width: 140px; margin: 8px;\\\"><" +
"/div></td>\" +\r\n                   \"<td class=\\\"formTitle\\\">区:</td><td><div id=\\\"" +
"COUNTY\\\" multiples=\\\"true\\\" type=\\\"select\\\" class=\\\"ui-select\\\" style=\\\"float: l" +
"eft; width: 140px; margin: 8px;\\\"></div> </td></tr></table>\";\r\n        var userc" +
"ode = usercodes();\r\n        var district = $(\"#districtsCtls\").mulDistrictsCtl({" +
"\r\n            provinceId: usercode.provinceId,\n            selectProviceId: user" +
"code.provinceId,\r\n            selectCityId: usercode.selectCityId,\r\n            " +
"type: \'B\',\r\n            showTown: false\r\n        });\r\n        $(\'input[type=radi" +
"o][name=Type]\').change(function () {\r\n            var selectRadio= $(this).attr(" +
"\'value\');\r\n            if (selectRadio == \"yhdgmqs\" || selectRadio == \"nxhd\") {\r" +
"\n                $(\"#startYear\").attr(\"disabled\", false);\r\n                $(\"#e" +
"ndYear\").attr(\"disabled\", true);\r\n            }\r\n            else {\r\n           " +
"     $(\"#startYear\").attr(\"disabled\", false);\r\n                $(\"#endYear\").att" +
"r(\"disabled\", false);\r\n            }\r\n        });\r\n        $(\"#TREETYPE\").ComboB" +
"ox({\r\n            description: \"\",\r\n            id: \"key\",\r\n            text: \"v" +
"alue\",\r\n            data: [{ key: \'1\', value: \'灾害点数\' }, { key: \'2\', value: \'拟销号灾" +
"害点数\' }],\r\n            height: \'200px\'\r\n        });\r\n        $(\"#TREETYPE\").combo" +
"BoxSetValue(\"1\");\r\n        treetype = \"1\";\r\n\r\n    };\r\n    //查询事件\r\n    function s" +
"eachEvent() {\r\n        GetGrid();\r\n    }\r\n    function GetGrid() {\r\n        grid" +
"Height = $(\"#filter-form\").height()+37+60+10;\r\n        var queryJson = getQueryJ" +
"son();\r\n        var typeFlag = $(\"input[name=\'Type\']:checked\").val();\r\n        i" +
"f (typeFlag == \"zqs\") {\r\n            $(\"#nav_yfsdzzh\").css(\"display\", \"block\");\r" +
"\n        } else {\r\n            $(\"#nav_yfsdzzh\").css(\"display\", \"none\");\r\n      " +
"  }\r\n        if (typeFlag == \"zqs\" && !YZCanShu(queryJson)) {\r\n            dialo" +
"gMsg(\'统计项目不能相同！\', 0);\r\n            return;\r\n        }\r\n        $(\"#divGrid\").emp" +
"ty();\r\n        $(\"#divGrid\").append(\'<table id=\"gridTable\"></table><div id=\"grid" +
"Pager\"></div>\');\r\n        var $gridTable = $(\'#gridTable\');\r\n        var colMode" +
"lArr = [];\r\n\r\n        $.ajax({\r\n            url: \"../../api/TBL_HAZARDBASICINFOA" +
"pi/QueryStatistics\",\r\n            data: { queryJson: JSON.stringify(queryJson) }" +
",\r\n            type: \"get\",\r\n            beforeSend: function (request) {\r\n     " +
"           request.setRequestHeader(\"Authorization\", authToken);\r\n              " +
"  learun.loading({ isShow: true, text: \"正在加载，请稍等...\" });\r\n            },\r\n      " +
"      complete: function () {\r\n                learun.loading({ isShow: false })" +
";\r\n            },\r\n            success: function (data) {\r\n                //dat" +
"a = JSON.parse(data);\r\n               // console.log(data);\r\n                var" +
" gridConfig;\r\n                if (typeFlag == \"nxhd\") {\r\n                    col" +
"ModelArr = [\r\n                        { label: \"灾害点名称\", name: \"disastername\", in" +
"dex: \"disastername\", width: columnWidth, align: \"center\", sortable: false },\r\n  " +
"                      { label: \"野外编号\", name: \"outdoorcode\", index: \"outdoorcode\"" +
", width: columnWidth, align: \"center\", sortable: false },\r\n                     " +
"   { label: \"位置\", name: \"location\", index: \"location\", width: columnWidth, align" +
": \"center\", sortable: false },\r\n                        { label: \"灾害类型\", name: \"" +
"disastertype\", index: \"disastertype\", width: columnWidth, align: \"center\", sorta" +
"ble: false },\r\n                        {\r\n                            label: \"销号" +
"理由\", name: \"zlgcly\", index: \"zlgcly\", width: columnWidth, align: \"center\", sorta" +
"ble: false\r\n                            //, formatter: function (cellvalue, opti" +
"ons, rowObject) {\r\n                            //    var returnValue = \"\";\r\n    " +
"                        //    if (rowObject.zlgcly) {\r\n                         " +
"   //        returnValue = rowObject.zlgcly + \",\";\r\n                            " +
"//    }\r\n                            //    if (rowObject.bqbrly) {\r\n            " +
"                //        returnValue += rowObject.bqbrly + \",\";\r\n              " +
"              //    }\r\n                            //    if (returnValue) {\r\n   " +
"                         //        return returnValue.substring(0, returnValue.l" +
"ength - 1);\r\n                            //    }\r\n                            //" +
"    return returnValue;\r\n                            //}\r\n                      " +
"  },\r\n                        {\r\n                            label: \"治理（搬迁避让）时间\"" +
", name: \"zlgcsj\", index: \"zlgcsj\", width: columnWidth, align: \"center\", sortable" +
": false\r\n                            //, formatter: function (cellvalue, options" +
", rowObject) {\r\n                            //    var returnValue = \"\";\r\n       " +
"                     //    if (rowObject.zlgcsj) {\r\n                            " +
"//        returnValue = rowObject.zlgcsj + \",\";\r\n                            // " +
"   }\r\n                            //    if (rowObject.bqbrsj) {\r\n               " +
"             //        returnValue += rowObject.bqbrsj + \",\";\r\n                 " +
"           //    }\r\n                            //    if (returnValue) {\r\n      " +
"                      //        return returnValue.substring(0, returnValue.leng" +
"th - 1);\r\n                            //    }\r\n                            //   " +
" return returnValue;\r\n                            //}\r\n                        }" +
",\r\n                        { label: \"治理配套资金（万元）\", name: \"zlptzj\", index: \"zlptzj" +
"\", width: columnWidth, align: \"center\", sortable: false },\r\n\r\n                  " +
"  ];\r\n                    gridConfig = { height: $(window).height() - gridHeight" +
", rownumbers: true, rowNum: 30, pager: \"#gridPager\", shrinkToFit: true };\r\n     " +
"               pageInit2(\'gridTable\', gridConfig, colModelArr, data.Data, null, " +
"null, null);\r\n                }\r\n                else if (typeFlag == \"gmdjdb\") " +
"{\r\n                    var hbCol2 = [];\r\n                    var columnWidth = 2" +
"00;\r\n                    $.each(data.Columns, function (i, e) {\r\n               " +
"         if (e.colFrom == e.colTo) {\r\n                            var obj = {\r\n " +
"                               label: e.columnNameReplace, name: e.columnName, i" +
"ndex: e.columnName, width: columnWidth, align: \"center\", sortable: false,\r\n     " +
"                           cellattr: function (rowId, tv, rawObject, cm, rdata) " +
"{\r\n                                    //合并单元格\r\n                                " +
"    return \'id=\\\'gridTableMergerRow\' + e.columnName + rowId + \"\\\'\";\r\n           " +
"                     }\r\n                            };\r\n                        " +
"    colModelArr.push(obj);\r\n                        }\r\n                        e" +
"lse {\r\n                            columnWidth = 95;\r\n                          " +
"  var item = data.Columns[i + 1];\r\n                            hbCol2.push({ sta" +
"rtColumnName: item.columnName, numberOfColumns: (e.colTo - e.colFrom) + 1, title" +
"Text: e.columnNameReplace });\r\n                        }\r\n                    })" +
";\r\n                    gridConfig = { height: $(window).height() - gridHeight, r" +
"ownumbers: true, rowNum: 30, pager: \"#gridPager\", shrinkToFit: false };\r\n       " +
"             pageInit2(\'gridTable\', gridConfig, colModelArr, data.Data, hbCol2, " +
"null, null);\r\n                }\r\n                else {//多表头\r\n                  " +
"  var hbCol2 = [];\r\n                    var columnWidth = 70;\r\n                 " +
"   $.each(data.Columns, function (i, e) {\r\n                        if (e.colFrom" +
" == e.colTo) {\r\n                            var obj = {\r\n                       " +
"         label: e.columnNameReplace, name: e.columnName, index: e.columnName, wi" +
"dth: columnWidth, align: \"center\", sortable: false,\r\n                           " +
"     cellattr: function (rowId, tv, rawObject, cm, rdata) {\r\n                   " +
"                 //合并单元格\r\n                                    return \'id=\\\'gridT" +
"ableMergerRow\' + e.columnName + rowId + \"\\\'\";\r\n                                }" +
"\r\n                            };\r\n                            colModelArr.push(o" +
"bj);\r\n                        }\r\n                        else {\r\n               " +
"             columnWidth = 95;\r\n                            var item = data.Colu" +
"mns[i + 1];\r\n                            hbCol2.push({ startColumnName: item.col" +
"umnName, numberOfColumns: (e.colTo - e.colFrom) + 1, titleText: e.columnNameRepl" +
"ace });\r\n                        }\r\n                    });\r\n                   " +
" gridConfig = { height: $(window).height() - gridHeight, rownumbers: true, rowNu" +
"m: 10000, pager: \"\",shrinkToFit:false };\r\n                    if (typeFlag == \"z" +
"hlxjgmqs\") {\r\n                        pageInit2(\'gridTable\', gridConfig, colMode" +
"lArr, data.Data, hbCol2, { defaluColumn: \"year\", column2: data.Columns[data.Colu" +
"mns.length - 1].columnName }, null);\r\n                    }\r\n                   " +
" else {\r\n                        //console.log(hbCol2);\r\n                       " +
" pageInit2(\'gridTable\', gridConfig, colModelArr, data.Data, hbCol2, null, null);" +
"\r\n\r\n                    }\r\n                }\r\n\r\n                if (typeFlag == " +
"\"zqs\") {\r\n                    var colArr = [];\r\n                    var dataDevi" +
"cename = [];\r\n                    var dataSeriesShowNew = [];\r\n                 " +
"   var data2 = data.Data;\r\n                    var dataArrA = [];\r\n             " +
"       var dataArr = [];\r\n                    var dataArr1 = [];\r\n              " +
"      var dataArr2 = [];\r\n                    var dataArr3 = [];\r\n              " +
"      var dataArr4 = [];\r\n                    var dataArr5 = [];\r\n              " +
"      for (var i = 0; i < data2.length; i++) {\r\n                        dataArr." +
"push(data2[i][\'灾害点数(处)\' + $(\"#endYear\").val() + \'年\']);\r\n                        " +
"dataArr1.push(data2[i][\'灾害点数(处)\' + $(\"#startYear\").val() + \'年\']);\r\n             " +
"           dataArr2.push(data2[i][\'灾害点数(处)新增点\']);\r\n                        dataA" +
"rr3.push(data2[i][\'拟销号灾害点数(处)\' + $(\"#endYear\").val() + \'年\']);\r\n                 " +
"       dataArr4.push(data2[i][\'拟销号灾害点数(处)\' + $(\"#startYear\").val() + \'年\']);\r\n   " +
"                     dataArr5.push(data2[i][\'拟销号灾害点数(处)新增点\']);\r\n                " +
"        colArr.push(data2[i].省 ? data2[i].省 : data2[i].市);\r\n                    " +
"}\r\n                    if (treetype == \"1\") {\r\n                        dataDevic" +
"ename.push(data.Columns[3].columnName, data.Columns[4].columnName, data.Columns[" +
"5].columnName);\r\n                        dataArrA.push(dataArr);\r\n              " +
"          dataArrA.push(dataArr1);\r\n                        dataArrA.push(dataAr" +
"r2);\r\n                    } else {\r\n                        dataDevicename.push(" +
"data.Columns[7].columnName, data.Columns[8].columnName, data.Columns[9].columnNa" +
"me);\r\n                        dataArrA.push(dataArr3);\r\n                        " +
"dataArrA.push(dataArr4);\r\n                        dataArrA.push(dataArr5);\r\n    " +
"                }\r\n\r\n\r\n                    for (var j = 0; j < dataDevicename.le" +
"ngth; j++) {\r\n                        dataSeriesShowNew.push({\r\n                " +
"            data: dataArrA[j], name: dataDevicename[j], type: \"line\", smooth: tr" +
"ue\r\n                        });\r\n                    }\r\n\r\n\r\n                    " +
"var myChart = echarts.init(document.getElementById(\"TJTB\"));\r\n                  " +
"  option = {\r\n                        tooltip: {\r\n                            tr" +
"igger: \'axis\',\r\n                            axisPointer: {            // 坐标轴指示器，" +
"坐标轴触发有效\r\n                                type: \'shadow\'        // 默认为直线，可选为：\'lin" +
"e\' | \'shadow\'\r\n                            },\r\n                        },\r\n     " +
"                   legend: {\r\n                            data: dataDevicename,\r" +
"\n                            x: \'center\',\r\n                            y: 30,\r\n " +
"                           padding: [5, 35, 5, 5]\r\n                        },\r\n " +
"                       grid: {\r\n                            \"borderWidth\": 0,\r\n " +
"                           top: 100,\r\n                            containLabel: " +
"true\r\n                        },\r\n                        xAxis: {\r\n            " +
"                type: \'category\',\r\n                            data: colArr,\r\n  " +
"                      },\r\n                        yAxis: {\r\n                    " +
"        type: \'value\',\r\n                            name: \'\',\r\n                 " +
"       },\r\n                        series: dataSeriesShowNew\r\n                  " +
"  }\r\n                    myChart.setOption(option, true);\r\n\r\n                }\r\n" +
"\r\n                //var legend = [\'灾害点数\', \'拟销号灾害点数\',\'完成搬迁点数\',\'完成治理点数\',\'有责任主体的点数\'" +
"];\r\n                //var series = [\r\n                //               {\r\n      " +
"          //                   name: \'矿山\',\r\n                //                  " +
" type: \'bar\',\r\n                //                   data: [574, 544, 564, 446, 8" +
"9, 1487, 526, 514, 499, 615, 551, 268, 1596, 228, 242, 240, 447],\r\n             " +
"   //                   //markPoint: {\r\n                //                   // " +
"   data: [\r\n                //                   //        { type: \'max\', name: " +
"\'最大值\' },\r\n                //                   //        { type: \'min\', name: \'最" +
"小值\' }\r\n                //                   //    ]\r\n                //         " +
"          //},\r\n                //                   //markLine: {\r\n            " +
"    //                   //    data: [\r\n                //                   // " +
"       { type: \'average\', name: \'平均值\' }\r\n                //                   //" +
"    ]\r\n                //                   //}\r\n                //             " +
"  },\r\n                //                {\r\n                //                   " +
" name: \'非煤矿山\',\r\n                //                    type: \'bar\',\r\n\r\n          " +
"      //                    data: [414, 431, 365, 381, 46, 1075, 461, 381, 295, " +
"503, 359, 174, 1336, 181, 230, 195, 353],\r\n                //                   " +
" //markPoint: {\r\n                //                    //    data: [\r\n          " +
"      //                    //        { type: \'max\', name: \'最大值\' },\r\n           " +
"     //                    //        { type: \'min\', name: \'最小值\' }\r\n             " +
"   //                    //    ]\r\n                //                    //},\r\n  " +
"              //                    //markLine: {\r\n                //           " +
"         //    data: [\r\n                //                    //        { type: " +
"\'average\', name: \'平均值\' }\r\n                //                    //    ]\r\n       " +
"         //                    //}\r\n                //                }\r\n       " +
"         //];\r\n               // _zzt(\'chartsdata\', \'地址灾害趋势分析\', legend, series)\r" +
"\n            },\r\n            error: function (e) {\r\n                dialogMsg(\'统" +
"计失败！\', 0);\r\n                learun.loading({ isShow: false });\r\n            }\r\n " +
"       });\r\n\r\n    }\r\n\r\n    //柱状图 legend:名称，yData:Y轴数据,data:X轴数据\r\n    function _z" +
"zt(echartID, text, legend, series) {\r\n      var myChart1 = echarts.init(document" +
".getElementById(echartID));\r\n        var option = {\r\n            //grid: {\r\n\r\n  " +
"          //    top: \'20%\',\r\n            //    left:\'20%\',\r\n            //},\r\n  " +
"          title: {\r\n                text: text,\r\n                //top:3,\r\n     " +
"           textStyle: {\r\n                    //color: \'#fff\',\r\n                }" +
",\r\n                x: \'center\'\r\n            },\r\n            color: [\'#19cc9f\', \'" +
"#2ec7c9\'],\r\n            tooltip: {\r\n                trigger: \'axis\',\r\n          " +
"      axisPointer: {\r\n                    type: \'shadow\'\r\n                },\r\n\r\n" +
"            },\r\n            legend: {\r\n                data: legend,\r\n          " +
"      letf: \'center\',\r\n                top: 30,\r\n            },\r\n            cal" +
"culable: true,\r\n            grid: {\r\n                left: \'20%\',\r\n             " +
"   top: \'8%\'\r\n            }\r\n            , yAxis: [\r\n                {\r\n        " +
"            type: \'value\',\r\n                    axisLine: {\r\n                   " +
"     lineStyle: {\r\n                            color: \'#fff\'\r\n                  " +
"      }\r\n                    },\r\n                    splitLine: {\r\n             " +
"           show: false\r\n                    }\r\n                }\r\n            ]," +
"\r\n            xAxis: [\r\n                {\r\n                    type: \'category\'," +
"\r\n                    //data: yData,\r\n                    data: [\'济南\', \'青岛\', \'淄博" +
"\', \'枣庄\', \'东营\', \'烟台\', \'潍坊\', \'济宁\', \'泰安\', \'威海\', \'日照\', \'莱芜\', \'临沂\', \'德州\', \'聊城\', \'滨州\'," +
" \'菏泽\'],\r\n                    axisLine: {\r\n                        lineStyle: {\r\n" +
"                            color: \'#fff\'\r\n                        }\r\n          " +
"          }\r\n                }\r\n            ],\r\n            series: series\r\n    " +
"    };\r\n        myChart1.setOption(option);\r\n    }\r\n\r\n    function YZCanShu(quer" +
"yJson) {\r\n        var returnValue = false;\r\n        $.ajax({\r\n            url: \"" +
"../../api/JYGC_PROJECTBASEINFOApi/GetListByDateDiff\",\r\n            data: { query" +
"Json: JSON.stringify(queryJson) },\r\n            type: \"get\",\r\n            async:" +
"false,\r\n            beforeSend: function (request) {\r\n                request.se" +
"tRequestHeader(\"Authorization\", authToken);\r\n            },\r\n            success" +
": function (data) {\r\n                //if (data.length>1) {\r\n                   " +
" returnValue = true;\r\n                //}\r\n            },\r\n            error: fu" +
"nction (e) {\r\n                console.log(e);\r\n            }\r\n        });\r\n     " +
"   return returnValue;\r\n    }\r\n\r\n    function pageInit2(id, gridConfig, colModel" +
", mydata, hbCol, hbRowColumnName, type) {\r\n        $(\"#\" + id).jqGrid(\r\n        " +
"    {\r\n                altRows: true,//启用隔行换色\r\n                datatype: \"local\"" +
",\r\n                autowidth: true,\r\n                shrinkToFit: gridConfig.shr" +
"inkToFit,\r\n                colModel: colModel,\r\n                height: gridConf" +
"ig.height,\r\n                rowNum: gridConfig.rowNum,\r\n                pager: g" +
"ridConfig.pager,\r\n                gridview: true,\r\n                shrinkToFit: " +
"true,\r\n                rownumbers: gridConfig.rownumbers,\r\n                gridC" +
"omplete: function () {\r\n                    if (hbRowColumnName) {\r\n            " +
"            MergerStatistics(id, hbRowColumnName, mydata.length);\r\n             " +
"       }\r\n                }\r\n            });\r\n        //for (var i = 0; i <= myd" +
"ata.length; i++) {\r\n        //    $(\"#\" + id).jqGrid(\'addRowData\', i + 1, mydata" +
"[i]);\r\n        //}\r\n        $(\"#\" + id).jqGrid(\'setGridParam\', {\r\n            da" +
"tatype: \"local\",\r\n            data: mydata,\r\n        }).trigger(\'reloadGrid\');\r\n" +
"        //二级表头\r\n        if (hbCol) {\r\n            $(\"#\" + id).jqGrid(\'setGroupHe" +
"aders\', {\r\n                useColSpanStyle: true,\r\n                groupHeaders:" +
" hbCol\r\n            });\r\n        }\r\n        if (mydata.length > 0) {\r\n          " +
"  $(\".unwritten\").hide();\r\n        }\r\n    }\r\n    function MergerStatistics(gridN" +
"ame, hbRowColumnName, dataCount) {\r\n        //得到显示到界面的id集合\r\n        var mya = $(" +
"\"#\" + gridName + \"\").getDataIDs();\r\n        //当前显示多少条\r\n        var length = mya." +
"length;\r\n        var rowSpanTaxCount = 1; var startRow = 0;\r\n        if (length " +
"< dataCount) {\r\n            return;\r\n        }\r\n        for (var i = 0; i < leng" +
"th; i++) {\r\n            //从上到下获取一条信息\r\n            var startCellValue = $(\"#\" + g" +
"ridName + \"\").jqGrid(\'getRowData\', mya[i]);\r\n            for (var j = i + 1; j <" +
"= length; j++) {\r\n                var endCellValue = $(\"#\" + gridName + \"\").jqGr" +
"id(\'getRowData\', mya[j]);\r\n                if (startCellValue[hbRowColumnName.de" +
"faluColumn] == endCellValue[hbRowColumnName.defaluColumn]) {\r\n                  " +
"  rowSpanTaxCount++;\r\n                    $(\"#\" + gridName + \"\").setCell(mya[j]," +
" hbRowColumnName.defaluColumn, \'\', { display: \'none\' });\r\n                    if" +
" (hbRowColumnName.column2) {\r\n                        $(\"#\" + gridName + \"\").set" +
"Cell(mya[j], hbRowColumnName.column2, \'\', { display: \'none\' });\r\n               " +
"     }\r\n                }\r\n                else {\r\n                    $(\"#\" + g" +
"ridName + \"MergerRow\" + hbRowColumnName.defaluColumn + (i + 1) + \"\").attr(\"rowsp" +
"an\", rowSpanTaxCount);//最后合并需要合并的行与合并的行数\r\n                    if (hbRowColumnNam" +
"e.column2) {\r\n                        $(\"#\" + gridName + \"MergerRow\" + hbRowColu" +
"mnName.column2 + (i + 1) + \"\").attr(\"rowspan\", rowSpanTaxCount);//最后合并需要合并的行与合并的" +
"行数\r\n                    }\r\n                    i = j - 1;\r\n                    r" +
"owSpanTaxCount = 1;\r\n                    break;\r\n                }\r\n\r\n          " +
"  }\r\n        }\r\n        //$(\"#\" + gridName + \"\").jqGrid(\'setLabel\', CellName, \'&" +
"nbsp;\', { \'text-align\': \'left\' }, \"\");\r\n        //$(\"#\" + gridName + \"\").trigger" +
"(\"reloadGrid\");\r\n    }\r\n    //导出excel\r\n    function btn_export() {\r\n        var " +
"queryJson = getQueryJson();\r\n        location.href = \"../../JXGeoManage/TBL_HAZA" +
"RDBASICINFO/ExcelDownloadQueryStatistics?queryJson=\" + JSON.stringify(queryJson)" +
";\r\n    }\r\n    function getQueryJson() {\r\n        var queryJson = $(\"#filter-form" +
"\").getWebControls();\r\n       // queryJson[\"StatisticsLevel\"] = \"省\";\r\n        if " +
"(DefalutCode == \"0\") {\r\n            queryJson[\"StatisticsLevel\"] = \"省\";\r\n       " +
" } else  if (queryJson[\"PROVINCE\"]) {\r\n            queryJson[\"StatisticsLevel\"] " +
"= \"市\";\r\n        } else if (queryJson[\"CITY\"]) {\r\n            queryJson[\"Statisti" +
"csLevel\"] = \"县\";\r\n        } \r\n        return queryJson;\r\n    }\r\n</script>\r\n");

});

WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
